//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for DeliveryResultStatus.
const (
	DeliveryResultStatusError DeliveryResultStatus = "error"
	DeliveryResultStatusOk    DeliveryResultStatus = "ok"
)

// Valid indicates whether the value is a known member of the DeliveryResultStatus enum.
func (e DeliveryResultStatus) Valid() bool {
	switch e {
	case DeliveryResultStatusError:
		return true
	case DeliveryResultStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for Platform.
const (
	Android Platform = "android"
	Ios     Platform = "ios"
)

// Valid indicates whether the value is a known member of the Platform enum.
func (e Platform) Valid() bool {
	switch e {
	case Android:
		return true
	case Ios:
		return true
	default:
		return false
	}
}

// Defines values for SendNotificationRequestInterruptionLevel.
const (
	Active        SendNotificationRequestInterruptionLevel = "active"
	Critical      SendNotificationRequestInterruptionLevel = "critical"
	Passive       SendNotificationRequestInterruptionLevel = "passive"
	TimeSensitive SendNotificationRequestInterruptionLevel = "time-sensitive"
)

// Valid indicates whether the value is a known member of the SendNotificationRequestInterruptionLevel enum.
func (e SendNotificationRequestInterruptionLevel) Valid() bool {
	switch e {
	case Active:
		return true
	case Critical:
		return true
	case Passive:
		return true
	case TimeSensitive:
		return true
	default:
		return false
	}
}

// Defines values for SendNotificationRequestPriority.
const (
	High   SendNotificationRequestPriority = "high"
	Normal SendNotificationRequestPriority = "normal"
)

// Valid indicates whether the value is a known member of the SendNotificationRequestPriority enum.
func (e SendNotificationRequestPriority) Valid() bool {
	switch e {
	case High:
		return true
	case Normal:
		return true
	default:
		return false
	}
}

// DeliveryResult 端末ごとの送信結果。同じ端末が複数の宛先 (ログイン ID / installationId) に該当しても 1 通にまとめる
type DeliveryResult struct {
	// Error プッシュサービスからのエラー内容
	Error          *string `json:"error,omitempty"`
	InstallationId string  `json:"installationId"`

	// LoginIds リクエストの loginIds のうち、この端末に紐付いていたもの。
	// `installationIds` / `broadcast` だけで選ばれた端末では空配列
	LoginIds []string             `json:"loginIds"`
	Status   DeliveryResultStatus `json:"status"`

	// Unregistered トークン失効により端末登録を削除した場合 true
	Unregistered *bool `json:"unregistered,omitempty"`
}

// DeliveryResultStatus defines model for DeliveryResult.Status.
type DeliveryResultStatus string

// Device defines model for Device.
type Device struct {
	AppId          *string   `json:"appId,omitempty"`
	AppVersion     *string   `json:"appVersion,omitempty"`
	BuildNumber    *string   `json:"buildNumber,omitempty"`
	CreatedAt      time.Time `json:"createdAt"`
	DeviceModel    *string   `json:"deviceModel,omitempty"`
	DeviceToken    *string   `json:"deviceToken,omitempty"`
	Id             int64     `json:"id"`
	InstallationId string    `json:"installationId"`
	Locale         *string   `json:"locale,omitempty"`

	// LoginIds この端末に紐付いているログイン ID (多対多)
	LoginIds  []string  `json:"loginIds"`
	OsVersion *string   `json:"osVersion,omitempty"`
	Platform  Platform  `json:"platform"`
	PushToken *string   `json:"pushToken,omitempty"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// DeviceInfo 端末情報 (ログイン ID を含まない DeviceRegistration)
type DeviceInfo struct {
	AppId          *string  `json:"appId,omitempty"`
	AppVersion     *string  `json:"appVersion,omitempty"`
	BuildNumber    *string  `json:"buildNumber,omitempty"`
	DeviceModel    *string  `json:"deviceModel,omitempty"`
	DeviceToken    *string  `json:"deviceToken,omitempty"`
	InstallationId string   `json:"installationId"`
	Locale         *string  `json:"locale,omitempty"`
	OsVersion      *string  `json:"osVersion,omitempty"`
	Platform       Platform `json:"platform"`
	PushToken      *string  `json:"pushToken,omitempty"`
}

// DeviceRegistration `pushToken` (Expo Push Token) と `deviceToken` (FCM / APNs のネイティブトークン) は
// どちらか一方以上が必須。バックエンドの `PUSH_PROVIDER` が `expo` なら pushToken、
// `native` なら deviceToken が送信に使われる。
type DeviceRegistration struct {
	// AppId バンドル ID / パッケージ名
	AppId       *string `json:"appId,omitempty"`
	AppVersion  *string `json:"appVersion,omitempty"`
	BuildNumber *string `json:"buildNumber,omitempty"`
	DeviceModel *string `json:"deviceModel,omitempty"`

	// DeviceToken ネイティブのデバイストークン (Android は FCM registration token、iOS は APNs device token の hex)。`PUSH_PROVIDER=native` で使う
	DeviceToken *string `json:"deviceToken,omitempty"`

	// InstallationId アプリインストールごとに生成される安定した ID
	InstallationId string  `json:"installationId"`
	Locale         *string `json:"locale,omitempty"`

	// LoginId Web アプリのログイン ID (postMessage で受け取ったもの)
	LoginId   string   `json:"loginId"`
	OsVersion *string  `json:"osVersion,omitempty"`
	Platform  Platform `json:"platform"`

	// PushToken Expo Push Token (`ExponentPushToken[...]`)。`PUSH_PROVIDER=expo` で使う
	PushToken *string `json:"pushToken,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Code Example: invalid_request
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	// Status Example: ok
	Status string `json:"status"`
}

// NotificationFilter 宛先端末の絞り込み条件。指定した条件はすべて満たす (AND) 必要があり、
// 各条件の配列内は「いずれかに一致」(OR) になる。
type NotificationFilter struct {
	// Locales 端末の `locale` に対する BCP 47 タグの前置一致 (大文字小文字を区別しない、タグ境界で判定)。
	// `ja` は `ja` と `ja-JP` に一致するが `jav` には一致しない。`ja-JP` は `ja-JP` (と `ja-JP-...`) にだけ一致する。
	// `locale` が未登録の端末はどのロケール指定にも一致しない
	Locales *[]string `json:"locales,omitempty"`

	// Platforms このプラットフォームの端末だけに送る
	Platforms *[]Platform `json:"platforms,omitempty"`
}

// Platform defines model for Platform.
type Platform string

// SendNotificationRequest 宛先は `loginIds` / `installationIds` / `broadcast: true` のうち少なくとも 1 つが必須。
// `broadcast: true` は `loginIds` / `installationIds` と併用できない (400)。
//
// `silent` が false (既定) のときは `title` が必須。`silent: true` のときは `title` / `body` /
// `sound` / `badge` / `subtitle` / `image` を指定できない (データのみのサイレント通知)。
type SendNotificationRequest struct {
	Badge *int    `json:"badge,omitempty"`
	Body  *string `json:"body,omitempty"`

	// Broadcast true なら登録済みの全端末に送る (`filter` で絞り込み可)。`loginIds` / `installationIds` とは併用できない
	Broadcast *bool `json:"broadcast,omitempty"`

	// ChannelId Android の通知チャンネル ID
	ChannelId *string `json:"channelId,omitempty"`

	// CollapseKey 同じキーの未配信の通知を 1 つにまとめる (最新のものだけ残す)。
	// FCM は `android.collapse_key`、APNs は `apns-collapse-id` に対応する。
	// **Expo は非対応のため無視される**
	CollapseKey *string `json:"collapseKey,omitempty"`

	// Data 任意の付加データ (アプリ側に `data` としてそのまま渡る)
	Data *map[string]interface{} `json:"data,omitempty"`

	// Filter 宛先端末の絞り込み条件。指定した条件はすべて満たす (AND) 必要があり、
	// 各条件の配列内は「いずれかに一致」(OR) になる。
	Filter *NotificationFilter `json:"filter,omitempty"`

	// Image 通知に表示する画像の URL (絶対 http(s) URL)。
	// Expo は `richContent.image`、FCM は `notification.image` に対応する。
	// **APNs は Notification Service Extension なしでは表示できないため無視される**
	Image *string `json:"image,omitempty"`

	// InstallationIds この installationId の端末に直接送る。`loginIds` と併用した場合は和集合
	// (同じ端末には 1 通だけ送る)。存在しない installationId は黙って無視する
	InstallationIds *[]string `json:"installationIds,omitempty"`

	// InterruptionLevel iOS 15 以降の割り込みレベル。Expo は `interruptionLevel`、APNs は `aps.interruption-level` に対応する。
	// **FCM (Android) は非対応のため無視される**
	InterruptionLevel *SendNotificationRequestInterruptionLevel `json:"interruptionLevel,omitempty"`

	// LoginIds このログイン ID に紐づく全端末に送る
	LoginIds *[]string `json:"loginIds,omitempty"`

	// Priority 配信優先度。`high` (既定、従来どおりの挙動) は即時配信、`normal` は省電力を優先して遅延することがある。
	// Expo は `priority`、FCM は `android.priority` (`high` / `normal`)、APNs は `apns-priority` (10 / 5) に対応する。
	// `silent: true` の APNs は Apple の要件により常に 5 になる
	Priority *SendNotificationRequestPriority `json:"priority,omitempty"`

	// Silent true ならサイレント通知 (データのみの通知)。画面には何も表示せず、`data` だけをアプリに届ける。
	// Expo は `title` / `body` / `sound` / `badge` を省いて `_contentAvailable: true` を付け、
	// FCM は `notification` を省いて `data` だけ送り、
	// APNs は `apns-push-type: background` / `apns-priority: 5` / `aps.content-available: 1` で送る。
	// `title` / `body` / `sound` / `badge` / `subtitle` / `image` とは併用できない (400)。`data` は空でもよい
	Silent *bool `json:"silent,omitempty"`

	// Sound iOS のサウンド ("default" など)
	Sound *string `json:"sound,omitempty"`

	// Subtitle 通知のサブタイトル (iOS)。Expo は `subtitle`、APNs は `aps.alert.subtitle` に対応する。
	// **FCM (Android) は非対応のため無視される**
	Subtitle *string `json:"subtitle,omitempty"`

	// ThreadId iOS の通知グループ化 ID。APNs の `aps.thread-id` に対応する。
	// **Expo と FCM は非対応のため無視される**
	ThreadId *string `json:"threadId,omitempty"`

	// Title 通知タイトル。`silent` が false のときは必須
	Title *string `json:"title,omitempty"`

	// Ttl 通知を保持する秒数 (0 〜 2419200 = 28 日)。この時間内に端末へ届けられなければ破棄される。
	// Expo は `ttl`、FCM は `android.ttl`、APNs は `apns-expiration` (現在時刻 + ttl の UNIX 秒) に対応する。
	// 未指定ならプッシュサービスの既定値に従う
	Ttl *int `json:"ttl,omitempty"`

	// Url 通知タップ時に WebView で開く URL
	Url *string `json:"url,omitempty"`
}

// SendNotificationRequestInterruptionLevel iOS 15 以降の割り込みレベル。Expo は `interruptionLevel`、APNs は `aps.interruption-level` に対応する。
// **FCM (Android) は非対応のため無視される**
type SendNotificationRequestInterruptionLevel string

// SendNotificationRequestPriority 配信優先度。`high` (既定、従来どおりの挙動) は即時配信、`normal` は省電力を優先して遅延することがある。
// Expo は `priority`、FCM は `android.priority` (`high` / `normal`)、APNs は `apns-priority` (10 / 5) に対応する。
// `silent: true` の APNs は Apple の要件により常に 5 になる
type SendNotificationRequestPriority string

// SendNotificationResult defines model for SendNotificationResult.
type SendNotificationResult struct {
	Failed int `json:"failed"`

	// Requested 宛先端末数 (`filter` 適用後)
	Requested int              `json:"requested"`
	Results   []DeliveryResult `json:"results"`
	Sent      int              `json:"sent"`
}

// InstallationId defines model for InstallationId.
type InstallationId = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// RegisterDeviceJSONRequestBody defines body for RegisterDevice for application/json ContentType.
type RegisterDeviceJSONRequestBody = DeviceRegistration

// SendNotificationJSONRequestBody defines body for SendNotification for application/json ContentType.
type SendNotificationJSONRequestBody = SendNotificationRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// Healthz ヘルスチェック
	//
	// Corresponds with GET /healthz (the `Healthz` operationId).
	Healthz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RegisterDeviceWithBody 端末を登録 / 更新する
	//
	// `installationId` をキーに端末を upsert し、`loginId` をその端末に紐付ける。
	// 端末とログイン ID は多対多 (1 端末に複数アカウント、1 アカウントに複数端末)。
	// 既に紐付いている場合は端末情報 (トークン等) だけ更新する。Web アプリのログイン時にアプリが呼び出す。
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/devices (the `RegisterDevice` operationId).
	RegisterDeviceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RegisterDevice 端末を登録 / 更新する
	//
	// `installationId` をキーに端末を upsert し、`loginId` をその端末に紐付ける。
	// 端末とログイン ID は多対多 (1 端末に複数アカウント、1 アカウントに複数端末)。
	// 既に紐付いている場合は端末情報 (トークン等) だけ更新する。Web アプリのログイン時にアプリが呼び出す。
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/devices (the `RegisterDevice` operationId).
	RegisterDevice(ctx context.Context, body RegisterDeviceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UnregisterDevice 端末の登録を解除する (全ログイン ID の紐付けごと削除)
	//
	// Corresponds with DELETE /v1/devices/{installationId} (the `UnregisterDevice` operationId).
	UnregisterDevice(ctx context.Context, installationId InstallationId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDevice 端末を取得する
	//
	// Corresponds with GET /v1/devices/{installationId} (the `GetDevice` operationId).
	GetDevice(ctx context.Context, installationId InstallationId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UnregisterDeviceLogin 端末から特定のログイン ID の紐付けだけを外す (そのユーザーのログアウト時)
	//
	// 端末自体とトークンは残るので、別のアカウントでログイン中ならそちらの通知は届き続ける。
	// アプリから呼ぶほか、Web アプリのバックエンドがセッション失効時に API キーで呼んでもよい
	// (installationId は bridge の `ready` イベントで Web アプリに渡る)。
	//
	// Corresponds with DELETE /v1/devices/{installationId}/logins/{loginId} (the `UnregisterDeviceLogin` operationId).
	UnregisterDeviceLogin(ctx context.Context, installationId InstallationId, loginId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UnregisterLogin ログイン ID を全端末から外す (サーバー間)
	//
	// Web アプリ側でセッションが失効・無効化された (全端末ログアウト、退会など) ときに
	// Web アプリのバックエンドから呼ぶ。以後そのログイン ID 宛の通知はどの端末にも届かない。
	// 端末自体とトークンは残る (別アカウントの通知には影響しない)。
	//
	// Corresponds with DELETE /v1/logins/{loginId} (the `UnregisterLogin` operationId).
	UnregisterLogin(ctx context.Context, loginId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SendNotificationWithBody プッシュ通知を送る (ログイン ID / installationId / 全端末)
	//
	// 宛先は `loginIds` (そのログイン ID に紐づく全端末)、`installationIds` (端末を直接指定)、
	// `broadcast: true` (登録済みの全端末) のいずれか。`loginIds` と `installationIds` は併用でき、
	// その場合は和集合を端末単位で重複排除して 1 端末 1 通だけ送る。`broadcast` は他の宛先と併用できない。
	// `filter` で宛先をプラットフォームやロケールで絞り込める。
	// `url` を指定するとアプリは通知タップ時にその URL を WebView で開く。
	// TTL・優先度・サイレント通知などの配信オプションは `SendNotificationRequest` を参照。
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/notifications (the `SendNotification` operationId).
	SendNotificationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SendNotification プッシュ通知を送る (ログイン ID / installationId / 全端末)
	//
	// 宛先は `loginIds` (そのログイン ID に紐づく全端末)、`installationIds` (端末を直接指定)、
	// `broadcast: true` (登録済みの全端末) のいずれか。`loginIds` と `installationIds` は併用でき、
	// その場合は和集合を端末単位で重複排除して 1 端末 1 通だけ送る。`broadcast` は他の宛先と併用できない。
	// `filter` で宛先をプラットフォームやロケールで絞り込める。
	// `url` を指定するとアプリは通知タップ時にその URL を WebView で開く。
	// TTL・優先度・サイレント通知などの配信オプションは `SendNotificationRequest` を参照。
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/notifications (the `SendNotification` operationId).
	SendNotification(ctx context.Context, body SendNotificationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// Healthz ヘルスチェック
//
// Corresponds with GET /healthz (the `Healthz` operationId).
func (c *Client) Healthz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthzRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RegisterDeviceWithBody 端末を登録 / 更新する
//
// `installationId` をキーに端末を upsert し、`loginId` をその端末に紐付ける。
// 端末とログイン ID は多対多 (1 端末に複数アカウント、1 アカウントに複数端末)。
// 既に紐付いている場合は端末情報 (トークン等) だけ更新する。Web アプリのログイン時にアプリが呼び出す。
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/devices (the `RegisterDevice` operationId).
func (c *Client) RegisterDeviceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterDeviceRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RegisterDevice 端末を登録 / 更新する
//
// `installationId` をキーに端末を upsert し、`loginId` をその端末に紐付ける。
// 端末とログイン ID は多対多 (1 端末に複数アカウント、1 アカウントに複数端末)。
// 既に紐付いている場合は端末情報 (トークン等) だけ更新する。Web アプリのログイン時にアプリが呼び出す。
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/devices (the `RegisterDevice` operationId).
func (c *Client) RegisterDevice(ctx context.Context, body RegisterDeviceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterDeviceRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UnregisterDevice 端末の登録を解除する (全ログイン ID の紐付けごと削除)
//
// Corresponds with DELETE /v1/devices/{installationId} (the `UnregisterDevice` operationId).
func (c *Client) UnregisterDevice(ctx context.Context, installationId InstallationId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUnregisterDeviceRequest(c.Server, installationId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetDevice 端末を取得する
//
// Corresponds with GET /v1/devices/{installationId} (the `GetDevice` operationId).
func (c *Client) GetDevice(ctx context.Context, installationId InstallationId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDeviceRequest(c.Server, installationId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UnregisterDeviceLogin 端末から特定のログイン ID の紐付けだけを外す (そのユーザーのログアウト時)
//
// 端末自体とトークンは残るので、別のアカウントでログイン中ならそちらの通知は届き続ける。
// アプリから呼ぶほか、Web アプリのバックエンドがセッション失効時に API キーで呼んでもよい
// (installationId は bridge の `ready` イベントで Web アプリに渡る)。
//
// Corresponds with DELETE /v1/devices/{installationId}/logins/{loginId} (the `UnregisterDeviceLogin` operationId).
func (c *Client) UnregisterDeviceLogin(ctx context.Context, installationId InstallationId, loginId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUnregisterDeviceLoginRequest(c.Server, installationId, loginId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UnregisterLogin ログイン ID を全端末から外す (サーバー間)
//
// Web アプリ側でセッションが失効・無効化された (全端末ログアウト、退会など) ときに
// Web アプリのバックエンドから呼ぶ。以後そのログイン ID 宛の通知はどの端末にも届かない。
// 端末自体とトークンは残る (別アカウントの通知には影響しない)。
//
// Corresponds with DELETE /v1/logins/{loginId} (the `UnregisterLogin` operationId).
func (c *Client) UnregisterLogin(ctx context.Context, loginId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUnregisterLoginRequest(c.Server, loginId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SendNotificationWithBody プッシュ通知を送る (ログイン ID / installationId / 全端末)
//
// 宛先は `loginIds` (そのログイン ID に紐づく全端末)、`installationIds` (端末を直接指定)、
// `broadcast: true` (登録済みの全端末) のいずれか。`loginIds` と `installationIds` は併用でき、
// その場合は和集合を端末単位で重複排除して 1 端末 1 通だけ送る。`broadcast` は他の宛先と併用できない。
// `filter` で宛先をプラットフォームやロケールで絞り込める。
// `url` を指定するとアプリは通知タップ時にその URL を WebView で開く。
// TTL・優先度・サイレント通知などの配信オプションは `SendNotificationRequest` を参照。
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/notifications (the `SendNotification` operationId).
func (c *Client) SendNotificationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendNotificationRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SendNotification プッシュ通知を送る (ログイン ID / installationId / 全端末)
//
// 宛先は `loginIds` (そのログイン ID に紐づく全端末)、`installationIds` (端末を直接指定)、
// `broadcast: true` (登録済みの全端末) のいずれか。`loginIds` と `installationIds` は併用でき、
// その場合は和集合を端末単位で重複排除して 1 端末 1 通だけ送る。`broadcast` は他の宛先と併用できない。
// `filter` で宛先をプラットフォームやロケールで絞り込める。
// `url` を指定するとアプリは通知タップ時にその URL を WebView で開く。
// TTL・優先度・サイレント通知などの配信オプションは `SendNotificationRequest` を参照。
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/notifications (the `SendNotification` operationId).
func (c *Client) SendNotification(ctx context.Context, body SendNotificationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendNotificationRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewHealthzRequest constructs an http.Request for the Healthz method
func NewHealthzRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/healthz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRegisterDeviceRequest calls the generic RegisterDevice builder with application/json body
func NewRegisterDeviceRequest(server string, body RegisterDeviceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRegisterDeviceRequestWithBody(server, "application/json", bodyReader)
}

// NewRegisterDeviceRequestWithBody constructs an http.Request for the RegisterDevice method, with any body, and a specified content type
func NewRegisterDeviceRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/devices")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUnregisterDeviceRequest constructs an http.Request for the UnregisterDevice method
func NewUnregisterDeviceRequest(server string, installationId InstallationId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "installationId", installationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/devices/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDeviceRequest constructs an http.Request for the GetDevice method
func NewGetDeviceRequest(server string, installationId InstallationId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "installationId", installationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/devices/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUnregisterDeviceLoginRequest constructs an http.Request for the UnregisterDeviceLogin method
func NewUnregisterDeviceLoginRequest(server string, installationId InstallationId, loginId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "installationId", installationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "loginId", loginId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/devices/%s/logins/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUnregisterLoginRequest constructs an http.Request for the UnregisterLogin method
func NewUnregisterLoginRequest(server string, loginId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "loginId", loginId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/logins/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSendNotificationRequest calls the generic SendNotification builder with application/json body
func NewSendNotificationRequest(server string, body SendNotificationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSendNotificationRequestWithBody(server, "application/json", bodyReader)
}

// NewSendNotificationRequestWithBody constructs an http.Request for the SendNotification method, with any body, and a specified content type
func NewSendNotificationRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/notifications")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// HealthzWithResponse ヘルスチェック
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /healthz (the `Healthz` operationId).
	HealthzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthzResponse, error)

	// RegisterDeviceWithBodyWithResponse 端末を登録 / 更新する
	//
	// `installationId` をキーに端末を upsert し、`loginId` をその端末に紐付ける。
	// 端末とログイン ID は多対多 (1 端末に複数アカウント、1 アカウントに複数端末)。
	// 既に紐付いている場合は端末情報 (トークン等) だけ更新する。Web アプリのログイン時にアプリが呼び出す。
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/devices (the `RegisterDevice` operationId).
	RegisterDeviceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterDeviceResponse, error)

	// RegisterDeviceWithResponse 端末を登録 / 更新する
	//
	// `installationId` をキーに端末を upsert し、`loginId` をその端末に紐付ける。
	// 端末とログイン ID は多対多 (1 端末に複数アカウント、1 アカウントに複数端末)。
	// 既に紐付いている場合は端末情報 (トークン等) だけ更新する。Web アプリのログイン時にアプリが呼び出す。
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/devices (the `RegisterDevice` operationId).
	RegisterDeviceWithResponse(ctx context.Context, body RegisterDeviceJSONRequestBody, reqEditors ...RequestEditorFn) (*RegisterDeviceResponse, error)

	// UnregisterDeviceWithResponse 端末の登録を解除する (全ログイン ID の紐付けごと削除)
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /v1/devices/{installationId} (the `UnregisterDevice` operationId).
	UnregisterDeviceWithResponse(ctx context.Context, installationId InstallationId, reqEditors ...RequestEditorFn) (*UnregisterDeviceResponse, error)

	// GetDeviceWithResponse 端末を取得する
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/devices/{installationId} (the `GetDevice` operationId).
	GetDeviceWithResponse(ctx context.Context, installationId InstallationId, reqEditors ...RequestEditorFn) (*GetDeviceResponse, error)

	// UnregisterDeviceLoginWithResponse 端末から特定のログイン ID の紐付けだけを外す (そのユーザーのログアウト時)
	//
	// 端末自体とトークンは残るので、別のアカウントでログイン中ならそちらの通知は届き続ける。
	// アプリから呼ぶほか、Web アプリのバックエンドがセッション失効時に API キーで呼んでもよい
	// (installationId は bridge の `ready` イベントで Web アプリに渡る)。
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /v1/devices/{installationId}/logins/{loginId} (the `UnregisterDeviceLogin` operationId).
	UnregisterDeviceLoginWithResponse(ctx context.Context, installationId InstallationId, loginId string, reqEditors ...RequestEditorFn) (*UnregisterDeviceLoginResponse, error)

	// UnregisterLoginWithResponse ログイン ID を全端末から外す (サーバー間)
	//
	// Web アプリ側でセッションが失効・無効化された (全端末ログアウト、退会など) ときに
	// Web アプリのバックエンドから呼ぶ。以後そのログイン ID 宛の通知はどの端末にも届かない。
	// 端末自体とトークンは残る (別アカウントの通知には影響しない)。
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /v1/logins/{loginId} (the `UnregisterLogin` operationId).
	UnregisterLoginWithResponse(ctx context.Context, loginId string, reqEditors ...RequestEditorFn) (*UnregisterLoginResponse, error)

	// SendNotificationWithBodyWithResponse プッシュ通知を送る (ログイン ID / installationId / 全端末)
	//
	// 宛先は `loginIds` (そのログイン ID に紐づく全端末)、`installationIds` (端末を直接指定)、
	// `broadcast: true` (登録済みの全端末) のいずれか。`loginIds` と `installationIds` は併用でき、
	// その場合は和集合を端末単位で重複排除して 1 端末 1 通だけ送る。`broadcast` は他の宛先と併用できない。
	// `filter` で宛先をプラットフォームやロケールで絞り込める。
	// `url` を指定するとアプリは通知タップ時にその URL を WebView で開く。
	// TTL・優先度・サイレント通知などの配信オプションは `SendNotificationRequest` を参照。
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/notifications (the `SendNotification` operationId).
	SendNotificationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SendNotificationResponse, error)

	// SendNotificationWithResponse プッシュ通知を送る (ログイン ID / installationId / 全端末)
	//
	// 宛先は `loginIds` (そのログイン ID に紐づく全端末)、`installationIds` (端末を直接指定)、
	// `broadcast: true` (登録済みの全端末) のいずれか。`loginIds` と `installationIds` は併用でき、
	// その場合は和集合を端末単位で重複排除して 1 端末 1 通だけ送る。`broadcast` は他の宛先と併用できない。
	// `filter` で宛先をプラットフォームやロケールで絞り込める。
	// `url` を指定するとアプリは通知タップ時にその URL を WebView で開く。
	// TTL・優先度・サイレント通知などの配信オプションは `SendNotificationRequest` を参照。
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/notifications (the `SendNotification` operationId).
	SendNotificationWithResponse(ctx context.Context, body SendNotificationJSONRequestBody, reqEditors ...RequestEditorFn) (*SendNotificationResponse, error)
}

type HealthzResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Health
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r HealthzResponse) GetJSON200() *Health {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r HealthzResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r HealthzResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthzResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r HealthzResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RegisterDeviceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Device
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r RegisterDeviceResponse) GetJSON200() *Device {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r RegisterDeviceResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r RegisterDeviceResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetBody returns the raw response body bytes
func (r RegisterDeviceResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r RegisterDeviceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RegisterDeviceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RegisterDeviceResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UnregisterDeviceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r UnregisterDeviceResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetBody returns the raw response body bytes
func (r UnregisterDeviceResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r UnregisterDeviceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UnregisterDeviceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UnregisterDeviceResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetDeviceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Device
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetDeviceResponse) GetJSON200() *Device {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetDeviceResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetDeviceResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r GetDeviceResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetDeviceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDeviceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetDeviceResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UnregisterDeviceLoginResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r UnregisterDeviceLoginResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetBody returns the raw response body bytes
func (r UnregisterDeviceLoginResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r UnregisterDeviceLoginResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UnregisterDeviceLoginResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UnregisterDeviceLoginResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UnregisterLoginResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Removed 紐付けを外した端末数 (0 でも 200)
		Removed int `json:"removed"`
	}
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r UnregisterLoginResponse) GetJSON200() *struct {
	// Removed 紐付けを外した端末数 (0 でも 200)
	Removed int `json:"removed"`
} {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r UnregisterLoginResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetBody returns the raw response body bytes
func (r UnregisterLoginResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r UnregisterLoginResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UnregisterLoginResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UnregisterLoginResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type SendNotificationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *SendNotificationResult
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r SendNotificationResponse) GetJSON200() *SendNotificationResult {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r SendNotificationResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r SendNotificationResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetBody returns the raw response body bytes
func (r SendNotificationResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r SendNotificationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SendNotificationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SendNotificationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// HealthzWithResponse ヘルスチェック
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /healthz (the `Healthz` operationId).
func (c *ClientWithResponses) HealthzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthzResponse, error) {
	rsp, err := c.Healthz(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthzResponse(rsp)
}

// RegisterDeviceWithBodyWithResponse 端末を登録 / 更新する
//
// `installationId` をキーに端末を upsert し、`loginId` をその端末に紐付ける。
// 端末とログイン ID は多対多 (1 端末に複数アカウント、1 アカウントに複数端末)。
// 既に紐付いている場合は端末情報 (トークン等) だけ更新する。Web アプリのログイン時にアプリが呼び出す。
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/devices (the `RegisterDevice` operationId).
func (c *ClientWithResponses) RegisterDeviceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterDeviceResponse, error) {
	rsp, err := c.RegisterDeviceWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterDeviceResponse(rsp)
}

// RegisterDeviceWithResponse 端末を登録 / 更新する
//
// `installationId` をキーに端末を upsert し、`loginId` をその端末に紐付ける。
// 端末とログイン ID は多対多 (1 端末に複数アカウント、1 アカウントに複数端末)。
// 既に紐付いている場合は端末情報 (トークン等) だけ更新する。Web アプリのログイン時にアプリが呼び出す。
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/devices (the `RegisterDevice` operationId).
func (c *ClientWithResponses) RegisterDeviceWithResponse(ctx context.Context, body RegisterDeviceJSONRequestBody, reqEditors ...RequestEditorFn) (*RegisterDeviceResponse, error) {
	rsp, err := c.RegisterDevice(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterDeviceResponse(rsp)
}

// UnregisterDeviceWithResponse 端末の登録を解除する (全ログイン ID の紐付けごと削除)
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /v1/devices/{installationId} (the `UnregisterDevice` operationId).
func (c *ClientWithResponses) UnregisterDeviceWithResponse(ctx context.Context, installationId InstallationId, reqEditors ...RequestEditorFn) (*UnregisterDeviceResponse, error) {
	rsp, err := c.UnregisterDevice(ctx, installationId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUnregisterDeviceResponse(rsp)
}

// GetDeviceWithResponse 端末を取得する
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/devices/{installationId} (the `GetDevice` operationId).
func (c *ClientWithResponses) GetDeviceWithResponse(ctx context.Context, installationId InstallationId, reqEditors ...RequestEditorFn) (*GetDeviceResponse, error) {
	rsp, err := c.GetDevice(ctx, installationId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDeviceResponse(rsp)
}

// UnregisterDeviceLoginWithResponse 端末から特定のログイン ID の紐付けだけを外す (そのユーザーのログアウト時)
//
// 端末自体とトークンは残るので、別のアカウントでログイン中ならそちらの通知は届き続ける。
// アプリから呼ぶほか、Web アプリのバックエンドがセッション失効時に API キーで呼んでもよい
// (installationId は bridge の `ready` イベントで Web アプリに渡る)。
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /v1/devices/{installationId}/logins/{loginId} (the `UnregisterDeviceLogin` operationId).
func (c *ClientWithResponses) UnregisterDeviceLoginWithResponse(ctx context.Context, installationId InstallationId, loginId string, reqEditors ...RequestEditorFn) (*UnregisterDeviceLoginResponse, error) {
	rsp, err := c.UnregisterDeviceLogin(ctx, installationId, loginId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUnregisterDeviceLoginResponse(rsp)
}

// UnregisterLoginWithResponse ログイン ID を全端末から外す (サーバー間)
//
// Web アプリ側でセッションが失効・無効化された (全端末ログアウト、退会など) ときに
// Web アプリのバックエンドから呼ぶ。以後そのログイン ID 宛の通知はどの端末にも届かない。
// 端末自体とトークンは残る (別アカウントの通知には影響しない)。
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /v1/logins/{loginId} (the `UnregisterLogin` operationId).
func (c *ClientWithResponses) UnregisterLoginWithResponse(ctx context.Context, loginId string, reqEditors ...RequestEditorFn) (*UnregisterLoginResponse, error) {
	rsp, err := c.UnregisterLogin(ctx, loginId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUnregisterLoginResponse(rsp)
}

// SendNotificationWithBodyWithResponse プッシュ通知を送る (ログイン ID / installationId / 全端末)
//
// 宛先は `loginIds` (そのログイン ID に紐づく全端末)、`installationIds` (端末を直接指定)、
// `broadcast: true` (登録済みの全端末) のいずれか。`loginIds` と `installationIds` は併用でき、
// その場合は和集合を端末単位で重複排除して 1 端末 1 通だけ送る。`broadcast` は他の宛先と併用できない。
// `filter` で宛先をプラットフォームやロケールで絞り込める。
// `url` を指定するとアプリは通知タップ時にその URL を WebView で開く。
// TTL・優先度・サイレント通知などの配信オプションは `SendNotificationRequest` を参照。
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/notifications (the `SendNotification` operationId).
func (c *ClientWithResponses) SendNotificationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SendNotificationResponse, error) {
	rsp, err := c.SendNotificationWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSendNotificationResponse(rsp)
}

// SendNotificationWithResponse プッシュ通知を送る (ログイン ID / installationId / 全端末)
//
// 宛先は `loginIds` (そのログイン ID に紐づく全端末)、`installationIds` (端末を直接指定)、
// `broadcast: true` (登録済みの全端末) のいずれか。`loginIds` と `installationIds` は併用でき、
// その場合は和集合を端末単位で重複排除して 1 端末 1 通だけ送る。`broadcast` は他の宛先と併用できない。
// `filter` で宛先をプラットフォームやロケールで絞り込める。
// `url` を指定するとアプリは通知タップ時にその URL を WebView で開く。
// TTL・優先度・サイレント通知などの配信オプションは `SendNotificationRequest` を参照。
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/notifications (the `SendNotification` operationId).
func (c *ClientWithResponses) SendNotificationWithResponse(ctx context.Context, body SendNotificationJSONRequestBody, reqEditors ...RequestEditorFn) (*SendNotificationResponse, error) {
	rsp, err := c.SendNotification(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSendNotificationResponse(rsp)
}

// ParseHealthzResponse parses an HTTP response from a HealthzWithResponse call
func ParseHealthzResponse(rsp *http.Response) (*HealthzResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthzResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Health
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseRegisterDeviceResponse parses an HTTP response from a RegisterDeviceWithResponse call
func ParseRegisterDeviceResponse(rsp *http.Response) (*RegisterDeviceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RegisterDeviceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Device
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseUnregisterDeviceResponse parses an HTTP response from a UnregisterDeviceWithResponse call
func ParseUnregisterDeviceResponse(rsp *http.Response) (*UnregisterDeviceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UnregisterDeviceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseGetDeviceResponse parses an HTTP response from a GetDeviceWithResponse call
func ParseGetDeviceResponse(rsp *http.Response) (*GetDeviceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDeviceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Device
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseUnregisterDeviceLoginResponse parses an HTTP response from a UnregisterDeviceLoginWithResponse call
func ParseUnregisterDeviceLoginResponse(rsp *http.Response) (*UnregisterDeviceLoginResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UnregisterDeviceLoginResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseUnregisterLoginResponse parses an HTTP response from a UnregisterLoginWithResponse call
func ParseUnregisterLoginResponse(rsp *http.Response) (*UnregisterLoginResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UnregisterLoginResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Removed 紐付けを外した端末数 (0 でも 200)
			Removed int `json:"removed"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseSendNotificationResponse parses an HTTP response from a SendNotificationWithResponse call
func ParseSendNotificationResponse(rsp *http.Response) (*SendNotificationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SendNotificationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SendNotificationResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Healthz ヘルスチェック
	// (GET /healthz)
	Healthz(w http.ResponseWriter, r *http.Request)
	// RegisterDevice 端末を登録 / 更新する
	// (POST /v1/devices)
	RegisterDevice(w http.ResponseWriter, r *http.Request)
	// UnregisterDevice 端末の登録を解除する (全ログイン ID の紐付けごと削除)
	// (DELETE /v1/devices/{installationId})
	UnregisterDevice(w http.ResponseWriter, r *http.Request, installationId InstallationId)
	// GetDevice 端末を取得する
	// (GET /v1/devices/{installationId})
	GetDevice(w http.ResponseWriter, r *http.Request, installationId InstallationId)
	// UnregisterDeviceLogin 端末から特定のログイン ID の紐付けだけを外す (そのユーザーのログアウト時)
	// (DELETE /v1/devices/{installationId}/logins/{loginId})
	UnregisterDeviceLogin(w http.ResponseWriter, r *http.Request, installationId InstallationId, loginId string)
	// UnregisterLogin ログイン ID を全端末から外す (サーバー間)
	// (DELETE /v1/logins/{loginId})
	UnregisterLogin(w http.ResponseWriter, r *http.Request, loginId string)
	// SendNotification プッシュ通知を送る (ログイン ID / installationId / 全端末)
	// (POST /v1/notifications)
	SendNotification(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Healthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterDevice operation middleware
func (siw *ServerInterfaceWrapper) RegisterDevice(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterDevice(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UnregisterDevice operation middleware
func (siw *ServerInterfaceWrapper) UnregisterDevice(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "installationId" -------------
	var installationId InstallationId

	err = runtime.BindStyledParameterWithOptions("simple", "installationId", r.PathValue("installationId"), &installationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "installationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UnregisterDevice(w, r, installationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDevice operation middleware
func (siw *ServerInterfaceWrapper) GetDevice(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "installationId" -------------
	var installationId InstallationId

	err = runtime.BindStyledParameterWithOptions("simple", "installationId", r.PathValue("installationId"), &installationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "installationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDevice(w, r, installationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UnregisterDeviceLogin operation middleware
func (siw *ServerInterfaceWrapper) UnregisterDeviceLogin(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "installationId" -------------
	var installationId InstallationId

	err = runtime.BindStyledParameterWithOptions("simple", "installationId", r.PathValue("installationId"), &installationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "installationId", Err: err})
		return
	}

	// ------------- Path parameter "loginId" -------------
	var loginId string

	err = runtime.BindStyledParameterWithOptions("simple", "loginId", r.PathValue("loginId"), &loginId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "loginId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UnregisterDeviceLogin(w, r, installationId, loginId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UnregisterLogin operation middleware
func (siw *ServerInterfaceWrapper) UnregisterLogin(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "loginId" -------------
	var loginId string

	err = runtime.BindStyledParameterWithOptions("simple", "loginId", r.PathValue("loginId"), &loginId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "loginId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UnregisterLogin(w, r, loginId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendNotification operation middleware
func (siw *ServerInterfaceWrapper) SendNotification(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendNotification(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.Healthz)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/devices", wrapper.RegisterDevice)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/devices/{installationId}", wrapper.UnregisterDevice)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/devices/{installationId}", wrapper.GetDevice)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/devices/{installationId}/logins/{loginId}", wrapper.UnregisterDeviceLogin)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/logins/{loginId}", wrapper.UnregisterLogin)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/notifications", wrapper.SendNotification)

	return m
}

type BadRequestJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type HealthzRequestObject struct {
}

type HealthzResponseObject interface {
	VisitHealthzResponse(w http.ResponseWriter) error
}

type Healthz200JSONResponse Health

func (response Healthz200JSONResponse) VisitHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterDeviceRequestObject struct {
	Body *RegisterDeviceJSONRequestBody
}

type RegisterDeviceResponseObject interface {
	VisitRegisterDeviceResponse(w http.ResponseWriter) error
}

type RegisterDevice200JSONResponse Device

func (response RegisterDevice200JSONResponse) VisitRegisterDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterDevice400JSONResponse struct{ BadRequestJSONResponse }

func (response RegisterDevice400JSONResponse) VisitRegisterDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterDevice401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RegisterDevice401JSONResponse) VisitRegisterDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UnregisterDeviceRequestObject struct {
	InstallationId InstallationId `json:"installationId"`
}

type UnregisterDeviceResponseObject interface {
	VisitUnregisterDeviceResponse(w http.ResponseWriter) error
}

type UnregisterDevice204Response struct {
}

func (response UnregisterDevice204Response) VisitUnregisterDeviceResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UnregisterDevice401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UnregisterDevice401JSONResponse) VisitUnregisterDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetDeviceRequestObject struct {
	InstallationId InstallationId `json:"installationId"`
}

type GetDeviceResponseObject interface {
	VisitGetDeviceResponse(w http.ResponseWriter) error
}

type GetDevice200JSONResponse Device

func (response GetDevice200JSONResponse) VisitGetDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetDevice401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetDevice401JSONResponse) VisitGetDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetDevice404JSONResponse struct{ NotFoundJSONResponse }

func (response GetDevice404JSONResponse) VisitGetDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UnregisterDeviceLoginRequestObject struct {
	InstallationId InstallationId `json:"installationId"`
	LoginId        string         `json:"loginId"`
}

type UnregisterDeviceLoginResponseObject interface {
	VisitUnregisterDeviceLoginResponse(w http.ResponseWriter) error
}

type UnregisterDeviceLogin204Response struct {
}

func (response UnregisterDeviceLogin204Response) VisitUnregisterDeviceLoginResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UnregisterDeviceLogin401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UnregisterDeviceLogin401JSONResponse) VisitUnregisterDeviceLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UnregisterLoginRequestObject struct {
	LoginId string `json:"loginId"`
}

type UnregisterLoginResponseObject interface {
	VisitUnregisterLoginResponse(w http.ResponseWriter) error
}

type UnregisterLogin200JSONResponse struct {
	// Removed 紐付けを外した端末数 (0 でも 200)
	Removed int `json:"removed"`
}

func (response UnregisterLogin200JSONResponse) VisitUnregisterLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UnregisterLogin401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UnregisterLogin401JSONResponse) VisitUnregisterLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SendNotificationRequestObject struct {
	Body *SendNotificationJSONRequestBody
}

type SendNotificationResponseObject interface {
	VisitSendNotificationResponse(w http.ResponseWriter) error
}

type SendNotification200JSONResponse SendNotificationResult

func (response SendNotification200JSONResponse) VisitSendNotificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SendNotification400JSONResponse struct{ BadRequestJSONResponse }

func (response SendNotification400JSONResponse) VisitSendNotificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SendNotification401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SendNotification401JSONResponse) VisitSendNotificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Healthz ヘルスチェック
	// (GET /healthz)
	Healthz(ctx context.Context, request HealthzRequestObject) (HealthzResponseObject, error)
	// RegisterDevice 端末を登録 / 更新する
	// (POST /v1/devices)
	RegisterDevice(ctx context.Context, request RegisterDeviceRequestObject) (RegisterDeviceResponseObject, error)
	// UnregisterDevice 端末の登録を解除する (全ログイン ID の紐付けごと削除)
	// (DELETE /v1/devices/{installationId})
	UnregisterDevice(ctx context.Context, request UnregisterDeviceRequestObject) (UnregisterDeviceResponseObject, error)
	// GetDevice 端末を取得する
	// (GET /v1/devices/{installationId})
	GetDevice(ctx context.Context, request GetDeviceRequestObject) (GetDeviceResponseObject, error)
	// UnregisterDeviceLogin 端末から特定のログイン ID の紐付けだけを外す (そのユーザーのログアウト時)
	// (DELETE /v1/devices/{installationId}/logins/{loginId})
	UnregisterDeviceLogin(ctx context.Context, request UnregisterDeviceLoginRequestObject) (UnregisterDeviceLoginResponseObject, error)
	// UnregisterLogin ログイン ID を全端末から外す (サーバー間)
	// (DELETE /v1/logins/{loginId})
	UnregisterLogin(ctx context.Context, request UnregisterLoginRequestObject) (UnregisterLoginResponseObject, error)
	// SendNotification プッシュ通知を送る (ログイン ID / installationId / 全端末)
	// (POST /v1/notifications)
	SendNotification(ctx context.Context, request SendNotificationRequestObject) (SendNotificationResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Healthz operation middleware
func (sh *strictHandler) Healthz(w http.ResponseWriter, r *http.Request) {
	var request HealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Healthz(ctx, request.(HealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Healthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthzResponseObject); ok {
		if err := validResponse.VisitHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterDevice operation middleware
func (sh *strictHandler) RegisterDevice(w http.ResponseWriter, r *http.Request) {
	var request RegisterDeviceRequestObject

	var body RegisterDeviceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterDevice(ctx, request.(RegisterDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterDevice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterDeviceResponseObject); ok {
		if err := validResponse.VisitRegisterDeviceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UnregisterDevice operation middleware
func (sh *strictHandler) UnregisterDevice(w http.ResponseWriter, r *http.Request, installationId InstallationId) {
	var request UnregisterDeviceRequestObject

	request.InstallationId = installationId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UnregisterDevice(ctx, request.(UnregisterDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UnregisterDevice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UnregisterDeviceResponseObject); ok {
		if err := validResponse.VisitUnregisterDeviceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDevice operation middleware
func (sh *strictHandler) GetDevice(w http.ResponseWriter, r *http.Request, installationId InstallationId) {
	var request GetDeviceRequestObject

	request.InstallationId = installationId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDevice(ctx, request.(GetDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDevice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDeviceResponseObject); ok {
		if err := validResponse.VisitGetDeviceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UnregisterDeviceLogin operation middleware
func (sh *strictHandler) UnregisterDeviceLogin(w http.ResponseWriter, r *http.Request, installationId InstallationId, loginId string) {
	var request UnregisterDeviceLoginRequestObject

	request.InstallationId = installationId
	request.LoginId = loginId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UnregisterDeviceLogin(ctx, request.(UnregisterDeviceLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UnregisterDeviceLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UnregisterDeviceLoginResponseObject); ok {
		if err := validResponse.VisitUnregisterDeviceLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UnregisterLogin operation middleware
func (sh *strictHandler) UnregisterLogin(w http.ResponseWriter, r *http.Request, loginId string) {
	var request UnregisterLoginRequestObject

	request.LoginId = loginId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UnregisterLogin(ctx, request.(UnregisterLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UnregisterLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UnregisterLoginResponseObject); ok {
		if err := validResponse.VisitUnregisterLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SendNotification operation middleware
func (sh *strictHandler) SendNotification(w http.ResponseWriter, r *http.Request) {
	var request SendNotificationRequestObject

	var body SendNotificationJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SendNotification(ctx, request.(SendNotificationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SendNotification")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SendNotificationResponseObject); ok {
		if err := validResponse.VisitSendNotificationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
