//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for DeliveryResultStatus.
const (
	DeliveryResultStatusError DeliveryResultStatus = "error"
	DeliveryResultStatusOk    DeliveryResultStatus = "ok"
)

// Valid indicates whether the value is a known member of the DeliveryResultStatus enum.
func (e DeliveryResultStatus) Valid() bool {
	switch e {
	case DeliveryResultStatusError:
		return true
	case DeliveryResultStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for Platform.
const (
	Android Platform = "android"
	Ios     Platform = "ios"
)

// Valid indicates whether the value is a known member of the Platform enum.
func (e Platform) Valid() bool {
	switch e {
	case Android:
		return true
	case Ios:
		return true
	default:
		return false
	}
}

// DeliveryResult defines model for DeliveryResult.
type DeliveryResult struct {
	// Error プッシュサービスからのエラー内容
	Error          *string              `json:"error,omitempty"`
	InstallationId string               `json:"installationId"`
	LoginId        string               `json:"loginId"`
	Status         DeliveryResultStatus `json:"status"`

	// Unregistered トークン失効により端末登録を削除した場合 true
	Unregistered *bool `json:"unregistered,omitempty"`
}

// DeliveryResultStatus defines model for DeliveryResult.Status.
type DeliveryResultStatus string

// Device defines model for Device.
type Device struct {
	// AppId バンドル ID / パッケージ名
	AppId       *string   `json:"appId,omitempty"`
	AppVersion  *string   `json:"appVersion,omitempty"`
	BuildNumber *string   `json:"buildNumber,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
	DeviceModel *string   `json:"deviceModel,omitempty"`

	// DeviceToken ネイティブのデバイストークン (Android は FCM registration token、iOS は APNs device token の hex)。`PUSH_PROVIDER=native` で使う
	DeviceToken *string `json:"deviceToken,omitempty"`
	Id          int64   `json:"id"`

	// InstallationId アプリインストールごとに生成される安定した ID
	InstallationId string  `json:"installationId"`
	Locale         *string `json:"locale,omitempty"`

	// LoginId Web アプリのログイン ID (postMessage で受け取ったもの)
	LoginId   string   `json:"loginId"`
	OsVersion *string  `json:"osVersion,omitempty"`
	Platform  Platform `json:"platform"`

	// PushToken Expo Push Token (`ExponentPushToken[...]`)。`PUSH_PROVIDER=expo` で使う
	PushToken *string   `json:"pushToken,omitempty"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// DeviceRegistration `pushToken` (Expo Push Token) と `deviceToken` (FCM / APNs のネイティブトークン) は
// どちらか一方以上が必須。バックエンドの `PUSH_PROVIDER` が `expo` なら pushToken、
// `native` なら deviceToken が送信に使われる。
type DeviceRegistration struct {
	// AppId バンドル ID / パッケージ名
	AppId       *string `json:"appId,omitempty"`
	AppVersion  *string `json:"appVersion,omitempty"`
	BuildNumber *string `json:"buildNumber,omitempty"`
	DeviceModel *string `json:"deviceModel,omitempty"`

	// DeviceToken ネイティブのデバイストークン (Android は FCM registration token、iOS は APNs device token の hex)。`PUSH_PROVIDER=native` で使う
	DeviceToken *string `json:"deviceToken,omitempty"`

	// InstallationId アプリインストールごとに生成される安定した ID
	InstallationId string  `json:"installationId"`
	Locale         *string `json:"locale,omitempty"`

	// LoginId Web アプリのログイン ID (postMessage で受け取ったもの)
	LoginId   string   `json:"loginId"`
	OsVersion *string  `json:"osVersion,omitempty"`
	Platform  Platform `json:"platform"`

	// PushToken Expo Push Token (`ExponentPushToken[...]`)。`PUSH_PROVIDER=expo` で使う
	PushToken *string `json:"pushToken,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Code Example: invalid_request
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	// Status Example: ok
	Status string `json:"status"`
}

// Platform defines model for Platform.
type Platform string

// SendNotificationRequest defines model for SendNotificationRequest.
type SendNotificationRequest struct {
	Badge *int    `json:"badge,omitempty"`
	Body  *string `json:"body,omitempty"`

	// ChannelId Android の通知チャンネル ID
	ChannelId *string `json:"channelId,omitempty"`

	// Data 任意の付加データ (アプリ側に `data` としてそのまま渡る)
	Data     *map[string]interface{} `json:"data,omitempty"`
	LoginIds []string                `json:"loginIds"`

	// Sound iOS のサウンド ("default" など)
	Sound *string `json:"sound,omitempty"`
	Title string  `json:"title"`

	// Url 通知タップ時に WebView で開く URL
	Url *string `json:"url,omitempty"`
}

// SendNotificationResult defines model for SendNotificationResult.
type SendNotificationResult struct {
	Failed int `json:"failed"`

	// Requested 宛先端末数
	Requested int              `json:"requested"`
	Results   []DeliveryResult `json:"results"`
	Sent      int              `json:"sent"`
}

// InstallationId defines model for InstallationId.
type InstallationId = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// RegisterDeviceJSONRequestBody defines body for RegisterDevice for application/json ContentType.
type RegisterDeviceJSONRequestBody = DeviceRegistration

// SendNotificationJSONRequestBody defines body for SendNotification for application/json ContentType.
type SendNotificationJSONRequestBody = SendNotificationRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// Healthz ヘルスチェック
	//
	// Corresponds with GET /healthz (the `Healthz` operationId).
	Healthz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RegisterDeviceWithBody 端末を登録 / 更新する
	//
	// `installationId` をキーに upsert する。同じ端末で別のログイン ID になった場合は
	// ログイン ID が付け替えられる。Web アプリのログイン時にアプリが呼び出す。
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/devices (the `RegisterDevice` operationId).
	RegisterDeviceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RegisterDevice 端末を登録 / 更新する
	//
	// `installationId` をキーに upsert する。同じ端末で別のログイン ID になった場合は
	// ログイン ID が付け替えられる。Web アプリのログイン時にアプリが呼び出す。
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/devices (the `RegisterDevice` operationId).
	RegisterDevice(ctx context.Context, body RegisterDeviceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UnregisterDevice 端末の登録を解除する (ログアウト時)
	//
	// Corresponds with DELETE /v1/devices/{installationId} (the `UnregisterDevice` operationId).
	UnregisterDevice(ctx context.Context, installationId InstallationId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDevice 端末を取得する
	//
	// Corresponds with GET /v1/devices/{installationId} (the `GetDevice` operationId).
	GetDevice(ctx context.Context, installationId InstallationId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SendNotificationWithBody ログイン ID 宛にプッシュ通知を送る
	//
	// 指定したログイン ID に紐づく全端末へ通知を送る。
	// `url` を指定するとアプリは通知タップ時にその URL を WebView で開く。
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/notifications (the `SendNotification` operationId).
	SendNotificationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SendNotification ログイン ID 宛にプッシュ通知を送る
	//
	// 指定したログイン ID に紐づく全端末へ通知を送る。
	// `url` を指定するとアプリは通知タップ時にその URL を WebView で開く。
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/notifications (the `SendNotification` operationId).
	SendNotification(ctx context.Context, body SendNotificationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// Healthz ヘルスチェック
//
// Corresponds with GET /healthz (the `Healthz` operationId).
func (c *Client) Healthz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthzRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RegisterDeviceWithBody 端末を登録 / 更新する
//
// `installationId` をキーに upsert する。同じ端末で別のログイン ID になった場合は
// ログイン ID が付け替えられる。Web アプリのログイン時にアプリが呼び出す。
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/devices (the `RegisterDevice` operationId).
func (c *Client) RegisterDeviceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterDeviceRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RegisterDevice 端末を登録 / 更新する
//
// `installationId` をキーに upsert する。同じ端末で別のログイン ID になった場合は
// ログイン ID が付け替えられる。Web アプリのログイン時にアプリが呼び出す。
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/devices (the `RegisterDevice` operationId).
func (c *Client) RegisterDevice(ctx context.Context, body RegisterDeviceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterDeviceRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UnregisterDevice 端末の登録を解除する (ログアウト時)
//
// Corresponds with DELETE /v1/devices/{installationId} (the `UnregisterDevice` operationId).
func (c *Client) UnregisterDevice(ctx context.Context, installationId InstallationId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUnregisterDeviceRequest(c.Server, installationId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetDevice 端末を取得する
//
// Corresponds with GET /v1/devices/{installationId} (the `GetDevice` operationId).
func (c *Client) GetDevice(ctx context.Context, installationId InstallationId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDeviceRequest(c.Server, installationId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SendNotificationWithBody ログイン ID 宛にプッシュ通知を送る
//
// 指定したログイン ID に紐づく全端末へ通知を送る。
// `url` を指定するとアプリは通知タップ時にその URL を WebView で開く。
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/notifications (the `SendNotification` operationId).
func (c *Client) SendNotificationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendNotificationRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SendNotification ログイン ID 宛にプッシュ通知を送る
//
// 指定したログイン ID に紐づく全端末へ通知を送る。
// `url` を指定するとアプリは通知タップ時にその URL を WebView で開く。
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/notifications (the `SendNotification` operationId).
func (c *Client) SendNotification(ctx context.Context, body SendNotificationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendNotificationRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewHealthzRequest constructs an http.Request for the Healthz method
func NewHealthzRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/healthz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRegisterDeviceRequest calls the generic RegisterDevice builder with application/json body
func NewRegisterDeviceRequest(server string, body RegisterDeviceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRegisterDeviceRequestWithBody(server, "application/json", bodyReader)
}

// NewRegisterDeviceRequestWithBody constructs an http.Request for the RegisterDevice method, with any body, and a specified content type
func NewRegisterDeviceRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/devices")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUnregisterDeviceRequest constructs an http.Request for the UnregisterDevice method
func NewUnregisterDeviceRequest(server string, installationId InstallationId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "installationId", installationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/devices/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDeviceRequest constructs an http.Request for the GetDevice method
func NewGetDeviceRequest(server string, installationId InstallationId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "installationId", installationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/devices/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSendNotificationRequest calls the generic SendNotification builder with application/json body
func NewSendNotificationRequest(server string, body SendNotificationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSendNotificationRequestWithBody(server, "application/json", bodyReader)
}

// NewSendNotificationRequestWithBody constructs an http.Request for the SendNotification method, with any body, and a specified content type
func NewSendNotificationRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/notifications")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// HealthzWithResponse ヘルスチェック
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /healthz (the `Healthz` operationId).
	HealthzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthzResponse, error)

	// RegisterDeviceWithBodyWithResponse 端末を登録 / 更新する
	//
	// `installationId` をキーに upsert する。同じ端末で別のログイン ID になった場合は
	// ログイン ID が付け替えられる。Web アプリのログイン時にアプリが呼び出す。
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/devices (the `RegisterDevice` operationId).
	RegisterDeviceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterDeviceResponse, error)

	// RegisterDeviceWithResponse 端末を登録 / 更新する
	//
	// `installationId` をキーに upsert する。同じ端末で別のログイン ID になった場合は
	// ログイン ID が付け替えられる。Web アプリのログイン時にアプリが呼び出す。
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/devices (the `RegisterDevice` operationId).
	RegisterDeviceWithResponse(ctx context.Context, body RegisterDeviceJSONRequestBody, reqEditors ...RequestEditorFn) (*RegisterDeviceResponse, error)

	// UnregisterDeviceWithResponse 端末の登録を解除する (ログアウト時)
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /v1/devices/{installationId} (the `UnregisterDevice` operationId).
	UnregisterDeviceWithResponse(ctx context.Context, installationId InstallationId, reqEditors ...RequestEditorFn) (*UnregisterDeviceResponse, error)

	// GetDeviceWithResponse 端末を取得する
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/devices/{installationId} (the `GetDevice` operationId).
	GetDeviceWithResponse(ctx context.Context, installationId InstallationId, reqEditors ...RequestEditorFn) (*GetDeviceResponse, error)

	// SendNotificationWithBodyWithResponse ログイン ID 宛にプッシュ通知を送る
	//
	// 指定したログイン ID に紐づく全端末へ通知を送る。
	// `url` を指定するとアプリは通知タップ時にその URL を WebView で開く。
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/notifications (the `SendNotification` operationId).
	SendNotificationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SendNotificationResponse, error)

	// SendNotificationWithResponse ログイン ID 宛にプッシュ通知を送る
	//
	// 指定したログイン ID に紐づく全端末へ通知を送る。
	// `url` を指定するとアプリは通知タップ時にその URL を WebView で開く。
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/notifications (the `SendNotification` operationId).
	SendNotificationWithResponse(ctx context.Context, body SendNotificationJSONRequestBody, reqEditors ...RequestEditorFn) (*SendNotificationResponse, error)
}

type HealthzResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Health
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r HealthzResponse) GetJSON200() *Health {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r HealthzResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r HealthzResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthzResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r HealthzResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RegisterDeviceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Device
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r RegisterDeviceResponse) GetJSON200() *Device {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r RegisterDeviceResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r RegisterDeviceResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetBody returns the raw response body bytes
func (r RegisterDeviceResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r RegisterDeviceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RegisterDeviceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RegisterDeviceResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UnregisterDeviceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r UnregisterDeviceResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetBody returns the raw response body bytes
func (r UnregisterDeviceResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r UnregisterDeviceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UnregisterDeviceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UnregisterDeviceResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetDeviceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Device
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetDeviceResponse) GetJSON200() *Device {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetDeviceResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetDeviceResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r GetDeviceResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetDeviceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDeviceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetDeviceResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type SendNotificationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *SendNotificationResult
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r SendNotificationResponse) GetJSON200() *SendNotificationResult {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r SendNotificationResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r SendNotificationResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetBody returns the raw response body bytes
func (r SendNotificationResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r SendNotificationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SendNotificationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SendNotificationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// HealthzWithResponse ヘルスチェック
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /healthz (the `Healthz` operationId).
func (c *ClientWithResponses) HealthzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthzResponse, error) {
	rsp, err := c.Healthz(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthzResponse(rsp)
}

// RegisterDeviceWithBodyWithResponse 端末を登録 / 更新する
//
// `installationId` をキーに upsert する。同じ端末で別のログイン ID になった場合は
// ログイン ID が付け替えられる。Web アプリのログイン時にアプリが呼び出す。
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/devices (the `RegisterDevice` operationId).
func (c *ClientWithResponses) RegisterDeviceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterDeviceResponse, error) {
	rsp, err := c.RegisterDeviceWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterDeviceResponse(rsp)
}

// RegisterDeviceWithResponse 端末を登録 / 更新する
//
// `installationId` をキーに upsert する。同じ端末で別のログイン ID になった場合は
// ログイン ID が付け替えられる。Web アプリのログイン時にアプリが呼び出す。
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/devices (the `RegisterDevice` operationId).
func (c *ClientWithResponses) RegisterDeviceWithResponse(ctx context.Context, body RegisterDeviceJSONRequestBody, reqEditors ...RequestEditorFn) (*RegisterDeviceResponse, error) {
	rsp, err := c.RegisterDevice(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterDeviceResponse(rsp)
}

// UnregisterDeviceWithResponse 端末の登録を解除する (ログアウト時)
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /v1/devices/{installationId} (the `UnregisterDevice` operationId).
func (c *ClientWithResponses) UnregisterDeviceWithResponse(ctx context.Context, installationId InstallationId, reqEditors ...RequestEditorFn) (*UnregisterDeviceResponse, error) {
	rsp, err := c.UnregisterDevice(ctx, installationId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUnregisterDeviceResponse(rsp)
}

// GetDeviceWithResponse 端末を取得する
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/devices/{installationId} (the `GetDevice` operationId).
func (c *ClientWithResponses) GetDeviceWithResponse(ctx context.Context, installationId InstallationId, reqEditors ...RequestEditorFn) (*GetDeviceResponse, error) {
	rsp, err := c.GetDevice(ctx, installationId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDeviceResponse(rsp)
}

// SendNotificationWithBodyWithResponse ログイン ID 宛にプッシュ通知を送る
//
// 指定したログイン ID に紐づく全端末へ通知を送る。
// `url` を指定するとアプリは通知タップ時にその URL を WebView で開く。
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/notifications (the `SendNotification` operationId).
func (c *ClientWithResponses) SendNotificationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SendNotificationResponse, error) {
	rsp, err := c.SendNotificationWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSendNotificationResponse(rsp)
}

// SendNotificationWithResponse ログイン ID 宛にプッシュ通知を送る
//
// 指定したログイン ID に紐づく全端末へ通知を送る。
// `url` を指定するとアプリは通知タップ時にその URL を WebView で開く。
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/notifications (the `SendNotification` operationId).
func (c *ClientWithResponses) SendNotificationWithResponse(ctx context.Context, body SendNotificationJSONRequestBody, reqEditors ...RequestEditorFn) (*SendNotificationResponse, error) {
	rsp, err := c.SendNotification(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSendNotificationResponse(rsp)
}

// ParseHealthzResponse parses an HTTP response from a HealthzWithResponse call
func ParseHealthzResponse(rsp *http.Response) (*HealthzResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthzResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Health
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseRegisterDeviceResponse parses an HTTP response from a RegisterDeviceWithResponse call
func ParseRegisterDeviceResponse(rsp *http.Response) (*RegisterDeviceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RegisterDeviceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Device
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseUnregisterDeviceResponse parses an HTTP response from a UnregisterDeviceWithResponse call
func ParseUnregisterDeviceResponse(rsp *http.Response) (*UnregisterDeviceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UnregisterDeviceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseGetDeviceResponse parses an HTTP response from a GetDeviceWithResponse call
func ParseGetDeviceResponse(rsp *http.Response) (*GetDeviceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDeviceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Device
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseSendNotificationResponse parses an HTTP response from a SendNotificationWithResponse call
func ParseSendNotificationResponse(rsp *http.Response) (*SendNotificationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SendNotificationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SendNotificationResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Healthz ヘルスチェック
	// (GET /healthz)
	Healthz(w http.ResponseWriter, r *http.Request)
	// RegisterDevice 端末を登録 / 更新する
	// (POST /v1/devices)
	RegisterDevice(w http.ResponseWriter, r *http.Request)
	// UnregisterDevice 端末の登録を解除する (ログアウト時)
	// (DELETE /v1/devices/{installationId})
	UnregisterDevice(w http.ResponseWriter, r *http.Request, installationId InstallationId)
	// GetDevice 端末を取得する
	// (GET /v1/devices/{installationId})
	GetDevice(w http.ResponseWriter, r *http.Request, installationId InstallationId)
	// SendNotification ログイン ID 宛にプッシュ通知を送る
	// (POST /v1/notifications)
	SendNotification(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Healthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterDevice operation middleware
func (siw *ServerInterfaceWrapper) RegisterDevice(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterDevice(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UnregisterDevice operation middleware
func (siw *ServerInterfaceWrapper) UnregisterDevice(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "installationId" -------------
	var installationId InstallationId

	err = runtime.BindStyledParameterWithOptions("simple", "installationId", r.PathValue("installationId"), &installationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "installationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UnregisterDevice(w, r, installationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDevice operation middleware
func (siw *ServerInterfaceWrapper) GetDevice(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "installationId" -------------
	var installationId InstallationId

	err = runtime.BindStyledParameterWithOptions("simple", "installationId", r.PathValue("installationId"), &installationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "installationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDevice(w, r, installationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendNotification operation middleware
func (siw *ServerInterfaceWrapper) SendNotification(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendNotification(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.Healthz)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/devices", wrapper.RegisterDevice)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/devices/{installationId}", wrapper.UnregisterDevice)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/devices/{installationId}", wrapper.GetDevice)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/notifications", wrapper.SendNotification)

	return m
}

type BadRequestJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type HealthzRequestObject struct {
}

type HealthzResponseObject interface {
	VisitHealthzResponse(w http.ResponseWriter) error
}

type Healthz200JSONResponse Health

func (response Healthz200JSONResponse) VisitHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterDeviceRequestObject struct {
	Body *RegisterDeviceJSONRequestBody
}

type RegisterDeviceResponseObject interface {
	VisitRegisterDeviceResponse(w http.ResponseWriter) error
}

type RegisterDevice200JSONResponse Device

func (response RegisterDevice200JSONResponse) VisitRegisterDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterDevice400JSONResponse struct{ BadRequestJSONResponse }

func (response RegisterDevice400JSONResponse) VisitRegisterDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterDevice401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RegisterDevice401JSONResponse) VisitRegisterDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UnregisterDeviceRequestObject struct {
	InstallationId InstallationId `json:"installationId"`
}

type UnregisterDeviceResponseObject interface {
	VisitUnregisterDeviceResponse(w http.ResponseWriter) error
}

type UnregisterDevice204Response struct {
}

func (response UnregisterDevice204Response) VisitUnregisterDeviceResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UnregisterDevice401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UnregisterDevice401JSONResponse) VisitUnregisterDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetDeviceRequestObject struct {
	InstallationId InstallationId `json:"installationId"`
}

type GetDeviceResponseObject interface {
	VisitGetDeviceResponse(w http.ResponseWriter) error
}

type GetDevice200JSONResponse Device

func (response GetDevice200JSONResponse) VisitGetDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetDevice401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetDevice401JSONResponse) VisitGetDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetDevice404JSONResponse struct{ NotFoundJSONResponse }

func (response GetDevice404JSONResponse) VisitGetDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type SendNotificationRequestObject struct {
	Body *SendNotificationJSONRequestBody
}

type SendNotificationResponseObject interface {
	VisitSendNotificationResponse(w http.ResponseWriter) error
}

type SendNotification200JSONResponse SendNotificationResult

func (response SendNotification200JSONResponse) VisitSendNotificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SendNotification400JSONResponse struct{ BadRequestJSONResponse }

func (response SendNotification400JSONResponse) VisitSendNotificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SendNotification401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SendNotification401JSONResponse) VisitSendNotificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Healthz ヘルスチェック
	// (GET /healthz)
	Healthz(ctx context.Context, request HealthzRequestObject) (HealthzResponseObject, error)
	// RegisterDevice 端末を登録 / 更新する
	// (POST /v1/devices)
	RegisterDevice(ctx context.Context, request RegisterDeviceRequestObject) (RegisterDeviceResponseObject, error)
	// UnregisterDevice 端末の登録を解除する (ログアウト時)
	// (DELETE /v1/devices/{installationId})
	UnregisterDevice(ctx context.Context, request UnregisterDeviceRequestObject) (UnregisterDeviceResponseObject, error)
	// GetDevice 端末を取得する
	// (GET /v1/devices/{installationId})
	GetDevice(ctx context.Context, request GetDeviceRequestObject) (GetDeviceResponseObject, error)
	// SendNotification ログイン ID 宛にプッシュ通知を送る
	// (POST /v1/notifications)
	SendNotification(ctx context.Context, request SendNotificationRequestObject) (SendNotificationResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Healthz operation middleware
func (sh *strictHandler) Healthz(w http.ResponseWriter, r *http.Request) {
	var request HealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Healthz(ctx, request.(HealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Healthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthzResponseObject); ok {
		if err := validResponse.VisitHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterDevice operation middleware
func (sh *strictHandler) RegisterDevice(w http.ResponseWriter, r *http.Request) {
	var request RegisterDeviceRequestObject

	var body RegisterDeviceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterDevice(ctx, request.(RegisterDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterDevice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterDeviceResponseObject); ok {
		if err := validResponse.VisitRegisterDeviceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UnregisterDevice operation middleware
func (sh *strictHandler) UnregisterDevice(w http.ResponseWriter, r *http.Request, installationId InstallationId) {
	var request UnregisterDeviceRequestObject

	request.InstallationId = installationId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UnregisterDevice(ctx, request.(UnregisterDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UnregisterDevice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UnregisterDeviceResponseObject); ok {
		if err := validResponse.VisitUnregisterDeviceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDevice operation middleware
func (sh *strictHandler) GetDevice(w http.ResponseWriter, r *http.Request, installationId InstallationId) {
	var request GetDeviceRequestObject

	request.InstallationId = installationId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDevice(ctx, request.(GetDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDevice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDeviceResponseObject); ok {
		if err := validResponse.VisitGetDeviceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SendNotification operation middleware
func (sh *strictHandler) SendNotification(w http.ResponseWriter, r *http.Request) {
	var request SendNotificationRequestObject

	var body SendNotificationJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SendNotification(ctx, request.(SendNotificationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SendNotification")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SendNotificationResponseObject); ok {
		if err := validResponse.VisitSendNotificationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xFlvUxRHGv8qXX33YrFWdiHEym3VvSAnSSgT3YJo7kood2AadpLZmcnMLAdSW0XPiK4CBaKCqIkioMiW",
	"i57mgoGT73LNLPItrrp7Znb+AbEqeu9Ytv88f37P7/k9veNwUC1pqoIU04C5cagJulBCJtLZp27FMAVZ",
	"FkxJVbpF+h9JgTmoCWYRpqEilBDMQSm8KA119GNZ0pEIc6ZeRmloDBZRSaC7S8Lo10gZNosw19b+WRqW",
	"JMX/nIbmmEbPM0xdUoZhpVKhRxmaqhiIWfO5IPagH8vIMOmnQVUxkcL+FDRNlgaZAZnvDVWh/2te+mcd",
	"DcEc/FOm6WmGf2tkunRd1flVIjIGdUmjh8AcJPYGsTaJtU6sN8Su7m3NNJ6vwEoanlXNL9SyIn54E949",
	"mSJ4leApYl0neIPgK/T+84pQNouqLl1GH8OGjZl36zs0DPYzYu9AusLdRM88jWRpBOljPcgoy8wGTVc1",
	"pJsSzxhi5+bGY8FdJLZNrF+JvUasX4i9Q+xbNNCur3X/QufqpFN/A2PYSEdRlxuPL5HVYemw7wxTMMvc",
	"RqVcgrmLUP0Bpl2D+xPuKys6GpYME+lITPKoSr2wNon9yll96dx4Q3CNWFVi3divbTYe1PaXtg+m/0Ws",
	"eef6jYOlVYIXCX7oPHrtzFUBrZKmiwOqKiNBgZVKsJIuxsvMc893pmm2OvA9GjSp2afRiDSIGDpk+dwQ",
	"zF08Ggl8fQ9zVWd3wUo6mtZBHQkmEjtZxodUvSSYMAdFwUQnTamEEtMlhtZKinmqo7lOUkw0jHQWZ018",
	"v7OjYaIBaRoYPDAen34/QiGPY+ktaGWj+K36A1IKINU1qqkgXzaKgP2nBRC8DgoiO8Zb88XfvgEZ0Jk/",
	"awAKZ3uGWKvEvkqsFWIvBMFCd2/2KQQ/I3iZgX9qb2uisfBmb3ttb+sGwdPO7uTBoyqZsIg9x6qGsZL9",
	"iti0UkAhf773q0v5nnMXuk939RQAwdOggEY1lf65QazrwLedTOA+paAIpjSC/G8DdtO9BxN4b3eZ4Nre",
	"f3aJNUusaWJNkQmrT4HpCAoETetOLIU51zq7BrpPgwwg9k1m+Evm9ZYzNwPTwVbQ/umpBMQImnYB6Yab",
	"j8DyUx0JqwfKkiyeLZcGkP57lnOvv1FFJCf1pUPWsygleRxOL034NRoGa5V3Dz/bINWpiLoqiTTrgIJE",
	"D+AOmG6WpHO9bAHDD7+af0fBBIpotIVMWOHE/7WZ1qc0dfhqOMYd2b+cOqbfJnFqxFHrMaPuDebuq6Zz",
	"do3g2wSvE1zbv/2wUZ0j+A6HjlO/7tTvcboD3adhOhbrY2yS1UFBRpEkfdKePpLuw2Z/hwZA03SanefE",
	"esF9oAhNaaphfoMMQxhGNH7O7CLBN53ZBYJXCH5ILIvgeksCZo8xXTXeA8CaLJiU7o5r1XlvHd3jVXbc",
	"5whJgVSha5Qflfc2XWxtbe0vJEDJY49EIH3a1n6cbgsTcrNNxTqY73NS5+rytEOk96giQwMaFUqazJvH",
	"iCBL4iXd1YYJwS3x5CYogYix7PTm+iS7vkKCbBbjhgUUhW8a0xRH33hE784HIOGpFEk1YBoKnEUShUov",
	"UsSzqikNuVIwIJnDBg8IYigkgSY8oIpjEdByAondNlgUFAXJSWXXpLr6wcS9/YdrxMbEXmHNYYY3h6Rc",
	"iYLJ9KogihI9SZDzAbP5RBG+aG97u3FlluD63vZd58YjRr47xNoFKb/qHfya4Boo0MMptNcZIz0h+CfK",
	"B/gtwW8bW8vEmmqBCYlwIcyiJpmoZCRKypIw2s2/bMtms6xIvM/+mYKuC2N0seHNEGFXOPPXqSi2nvA2",
	"ClJ9UERDQlk2+yDr2vhZS1LgTMmMEWVyay3rcvxqN0fWLu3V9mJjyaIR+w4NXJDQPykbHCxMETwLzvd8",
	"DdNNZVbWJfg7KcCAnpFJaI/jNnmmGBIkGYnJuHUpIEmhO/X7zmSVi/HGnReJ2lNnV4bTfLRYDo0/lYQ0",
	"u6NZ9K5IgJp2u1vSnptNo+IxY+cPlnXJHOulFnmyTDqDxjrLZjEeBG/YmiP2zsHCrYOJe3u7y/u310Fn",
	"vhsQ6zmxd0Bqf/6F89h2Vq837rwAhc5896UzXf8otDAChzlYRIKI9Ob4//eTnfnuk2fQWDOk3ARGJEjQ",
	"kZ5sTKQtTwfbsou+SGOmJcqUhF/xQXHFVGpcJLPSr4NCpzc26wXg1B++W5mkJ64+oPMtXiLWFEgx5rhD",
	"rGdU0NhVgje97zcIXmzxZDBLPxvVmHdNv4umqfEpWlKG1ESPeTHR2dZmsngnEIF1jyYTdP7Bwi2C687a",
	"zf3XV5gdfcpJcOKEvxv89+o8iO88cSIHInF+GowzDyfjwxk6sU7gqDgieL1PASA4snMz92+vE1x3C8qe",
	"dB69JNa8O+a68Szkz/V+CzIjbRkuYg2mNrwbHjOKq/JUv3u6wsbiJW/coN410xzA7RGexmy35nnZU9c4",
	"4cfcINb8wQQm1hT1MmCxEqAibnezRqg02v3p3fNffZnrpoTgWwyUd4i1zMyo8ScN8KUKQj6kVEGTTlK1",
	"MexNkN+OaaiXgQUwPD9j48Nj5l3V+XmqT0mpGlLoPgo3jiu6tb63tdxYeEPwdER7e3h1GwOFX6emgSDJ",
	"0sKHaTji6VTY1pptzTLxyu+COfhJa7b1E5hmr36MYTJFJoEu07+HEeM3StD+2OBKpMsw8n7Xns3+YS9W",
	"/IqkJ6tzZzgzlkslQR9j49ldmgg6rGBiPeW4oWERhg2mwMYME5VgP90VwCrrPCoXTpHXgLCQLVCcecCo",
	"gbJmIN0EPpSduWmC7/I6ocNFdS1hBGEA3eDzBn8V4s8CsWXTe9t3Cb7ZuL9LcJW+F3iZPmrI4SUW5Frn",
	"5g7Br5xrv1EzXZiEc9jjvna5D0h+b/3clYZ/SBaTXpvCvZHqvcoHxJHrXgKOOJU1tqoE7/pERyujI5s9",
	"7FTfzEzgrZptaTt+S+hlN9jc6aMdfYQLNtOL/ZX+IMhdfHkMDDKgcf91Y+EFh2EA7R66o3DPjIdRXeG4",
	"l5GJ4gV+3n8MDcAjlKGOeNl4FM+eAlLO87vOAy7DNyhJBqFvWaA929HyUSOH6/4TbbAXgZRXSM121ZIY",
	"znQyF36JzMNi9FFQHIDte0eSbuo4fpP/k0g09CEteihindkF5+3iEUBNh36VOuQBu7kkE/nVqtLvIj3U",
	"0g+n98b0Nf/JKoGn91/PEbxG8Kwzue5hZyuiJRilFsq6zHqDdyBrCHg9wMObiUMXn0rpoEV3x0ewZMKO",
	"zk8fiLIPe174yLx9yLSYUAH8RXv/l7nGzw/+b/R9ZCVEQebU71MUHC5VA1USxnR/hV+sj3ilEn2pZirF",
	"qhG7drAwtb/0G3RfA9jskstk2HNrUTXM3GfZz7Kw0u9fNe4NfK5eqqSjpwd/6Qq8vXAJzBTHv1uac6NX",
	"3/FzuLc8byAV1M1sCnoaOyochEp/5X8DAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
