// Package openapivalidate provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapivalidate

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1FptTxvH9v8qo/n/X5jIiU2aRr2W7gt6k7YobYKSpr1XAdULO+Bt7V13d82FIkueXUh4FIQkEGjaPEEg",
	"WJikSVsoNHyXO14bf4urmdld7xMGpCRXfYMwnoczc37nd875DSOwT8nlFRnJugZTIzAvqEIO6Uhlnzpl",
	"TReyWUGXFLlTpH+RZJiCeUHPwDiUhRyCKSj5B8Whir4vSCoSYUpXCygOtb4Mygl0dk4Y+hzJA3oGptrP",
	"fhSHOUl2P8ehPpyn62m6KskDsFgs0qW0vCJriFnzsSBeRd8XkKbTT32KrCOZ/Srk81mpjxmQ+FZTZPq3",
	"5qb/r6J+mIL/l2ieNMG/1RIXVVVR+VYi0vpUKU8XgSlIzA1ibBFjnRg7xByvbs/UNp/CYhxeVvRPlIIs",
	"vnsTDp5NEbxC8BQxJgjeIHiU7n9dFgp6RlGlH9D7sGFj5mB9j16D+ZyYe5COsCfRNS+grDSI1OGrSCtk",
	"mQ3+6fXyVu1BmeC7BK8TXGmUcHX/cf3XudrPD0jJsOamCb7vjCkfrNyq3XtBcMWq/GiNjRNzkxgviLFC",
	"zFeg8wIgePrg+S/Wn3cIXiT4GTEM0A4apWWCywS/oRsYmBhTMA7zqpJHqi5x1CB2tpBpxFwkpkmM34m5",
	"SoxfiblHzDvU2fZ9V9xDWzfHrMoODOEzHkR+aiQ8JKsMSHKnqEUZ4EMYwRXgDAZ0e3yT4MekhAm+Q3DF",
	"vaX667nq7n2CR+kd0J8PiWEQXIFxKOkop0VaYf9BUFVhmH7WdEEv8NuRCzmYugGV72DcvqqeiJMWZBUN",
	"SJqOVCRGHWWc3p+xRcxX1spLa3KHOsUYJ8Ykt7u+tNuY/oUY89bEZGNphXnwofXotTU3DihHNC+3V1Gy",
	"SJBhsejlkRthknEv1j1N026l91vUp1O7L6BBqQ+x4Mhmr/TD1I3WgcDHd8r9CizGRwJI6lORoCOxgwG9",
	"X1Fzgg5TUBR0dFqXcigSIaJvrCTr5881x0myjgaQegROWvvfmAoGSsxaWba23lgry20nAkUhL57seEEX",
	"BdzSvC7v2mEv9bh+Yvd+CInUzDHr0UsQC9GCMW/NcQagFAn4SlcZWlUGl7YQJQj5fKcYyEdnPzwf4T8h",
	"n/8KqZqkyIHh589FjO4tSFnxciHXi9TjDBeZqV8oIspGJcdDxn+pfIeC1pxL/u38sfjpRAmYerNPyKLA",
	"xA/ORoxUtBPcUz4r6BRgR6WlLmccnVPQMlFH/7D97JHADHKHu//hlOEFUBiSadeaNIhdHMoroKugZQD7",
	"SxsgeB2kPc5Kg9gn//gCJEBH12XO7eYMA/BNYjwl5oKXPunsrW6Z4OeU/Wkimqpul2oLO9Xd1er2JMHT",
	"1v5Y49E4KRnEnGMZjOUQ8xUxadYC6a7r1z77puvqla86L1y8mqZpE6TRUF6hv24QYwK4tpMS7pbTsqBL",
	"g8j91mM3nctTNsHl6p/7xJglxjRlnJLRLR8eVcHkMGdbZ5ZpwCYAMW8zw1+yU29bczMw/tcOxeCJ/e6l",
	"Dr9Fr8FYsXO9420Q65BFVZFE6nVAQaJ6cAd020vSlWtsAMMP35p/R8EEMmiojZQMv+P/3nTrGnUdvgnj",
	"YcY4IvzD/BE4qPGElVEbnI6bhzPdmq9cv/uwNj5H8D0OHasyYVWWeQEAOi/AeOiu3xol2akobPbXqBc0",
	"TceVYEqJ5RVN/wJpmjCA6P1Zs4sE37ZmFwh+6tZbbRGYPcL098uR/jMHSArE0heH+FJdzqQbZ86c6UlH",
	"QMlhj0ggMf5t3cf52dhxS/yEvHzRqeMDRZkiMjSgISGXz/KqalDISuI3qt0rRlxujjs3oiwKGMtWb46P",
	"suszJGT1TNgwT43tmsaq7NY7tihmuzyQcOp2SdFgHAqcRSJL92tIFi8rutRvt4aeFtpvcK8g+q7EU532",
	"KuLw8UqOvowgyygbFXZNqqs0Ssv1h6vExMR8ypLDDE8OUb4SBZ31r4IoSnQlIdvlMZsrDP6Nqru7tdFZ",
	"givV3fvW5CNGvnvE2AcxN+ot/JrgMkjTxSm01+2mEv/EWq83BL+pbT8mxlQbjHCEt1g/vL7OCUOd/Mv2",
	"ZDLJgsT5HNGROZqC/yic+Su0QTWe8TQKYt1QRP1CIat3Q5a18fO2qIvTJT1ElNGptaBmw1vbPjL2aa42",
	"F2tLBr2xr1HvVxL6N2WDxsIUwbPg+tXPYbzZLxRUCR6TAjToGBmF9jBuHY3BD9t+QcoiMRq3NgVE9axc",
	"ZLB7i3svIpsylW3pd3Pr7tEnh0Q13rZUE9wrcEFNu+0pceeYTaPCd8bW7yuokj58jVrklGXSJTTcUdAz",
	"4UtwhI85Yu41Fu40SstUn7m7Djq6OgExNom5B2L1+RfWE9NamajdewHSHV2d31y6+K806y3pGhkkiEht",
	"yoH/PN3R1Xn6EhpuXik3gREJElSkRhsTSMvT3rRsoy+QmGmIskrCjXhvccWq1HCRzEK/AtIdjoympoFV",
	"eXjwdIyuuPKA6l14iRhTtNe8Rcx7xHhOCxoq0Ww5328QvNjmlMHM/Uy8YKdrnjuj63muqkmRna0bTFRn",
	"MllZvOe5gXWHJiPq/MYCVQWs1dv116PMjm75NDh1yp0N/nNzHoRnnjqVAoF7XvPeM79OxoczVMMp4bAM",
	"t94tA+CVz7iZ9bvrrk7Bm3VizNvCj32f6a4r174EicH2BC9iNVZtODs8YRQ3zl19sPaUCUVLTrtBT9d0",
	"swe3LU4apRVwbRGXbcIPHYMY840SFRLpKT0Wyx4q4nY3Y4SWRvs/HWz+7pa5tku4dsMw9JiZUebyIvhU",
	"Ab4zxBQhL52m1caA00F+OZxH1xhYAMPzc7oAddsrYo5bP091yzElj2Q6j8KN44pOrVS3H9cWdgieDtTe",
	"Dl7txEDh15HPAy/J0sCHcTjo1Kmw/UzyTJIVr3wvmIIfnEme+YBWa4KeYQyTyLAS6Af6+wBi/EYJ2m0b",
	"7BLpBxjQ888mk29NweZbREnYVy5xZizkcoI6zNqz+9QRtFnBxFjjuKHXIgxorAIb1nSUgz10lgerLPMo",
	"WoTKnfYXsmmKMwcYZVu4M+ZBIa8hVQcUeCWctnMgH8zKjpDEd9vxmfPNejgYt1yxD8TaQVBLpzFVdiqH",
	"cVLC7SD4N2csn8o5rbb4JFJp5IotwVtBSa5JuvXNCYrBRwTfrv34urbwwg3hVl0Xj3kv+Vu39wh+Zd36",
	"g863cesH1VVbkLYlXjfZf2zXqm8FVhFiUNGfrGkBWnyHwLaPFwFszq217XGC91340FA9l0wetqprZsLz",
	"mMamtB89xff05K02qKxO5XJvdr/RU+zxRp0bB9xskABefHjCzwm3YPwlRvxhVuSBmEU6CjPOdfe9wgMP",
	"n4fOhePYyTlMm4hZm/etB7wv2KCszXp/OwIMA5xNnmt7rzeHK+4rijc5gpg1FsELlSaJMCWGP7y0Rd5z",
	"PJq1P0X6YZf3XuDtwfOJr5hOOnf0JPcxN+gTX9V8KJSt2QXrzWILBMd97+mHvD01hyQC7+3FniNCIMGy",
	"iJYYsbNJICaiLvTg1kaVvqGu+0plvFWrTFGept3vGilha3yV/h5MFr5isbq9yUVjlr+4Wu209njLejlJ",
	"8Ez9t2VPIvMwPC2DGMn/RvAu/VjC4QwRLnynibHrVGxr7nOj3R74KjK6uHGHmmwY9C0Sj3bLMf/9MVG1",
	"V5VE1k5UQFpFgjhMU/IKMZfcMwcr5rItDUTnpSD1fE5d8xfjn/ixAoD5sD6xwwTdSmsOogUBjZiVBYKX",
	"QMwWWsxnDIK/0Z+4Em4E2t5JVMUj/42lqUse6/9XjhZ83eg9SZD6oMZa1bUA4mlxxN/Yzd366GNrcsea",
	"XrBrfIabsXXbP/7rJCXcKJWqe8u2ZATcLq9bPk7keQK2ZFR3V603044X/Y63Kj96eYA9ZTWLW2IYjBmm",
	"+Hutp75tzUwgRikpyEfuNmXKOH++bDzcdyJm9Mj4PCQyT5bc/GKUinLKYJTc5KnpeRDQIHfVJxBLAs5U",
	"4Gwy2RYhRoUEIr5PhAhUjLegFXfHt0MdLVkiqvt2scnh5LCBX4Y6ZtS/1xj2tf+Ht4K16Vvu81aYEGlL",
	"RfAqwbOei9gO6A4MtemCmmWtobMga6LwuidItyIFWh6SVJSls8NybXRMBLXWd9RNHfYU8Z5bqkOU5YjQ",
	"8f7D2v+sszpRkDHyLbeQtTyx5cd0T5FvrA46ARZ81WaFlVEmZrmxMFVf+gPaLwdM50wlEuxpNqNoeuqj",
	"5EdJWOxxtxpxAtTWVorx4Ore/xPzvNN4005bM84dVgivw0/L/RYiFrsq9C3lv4RiT/G/AwA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
