// Code generated by ent, DO NOT EDIT.

package device

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the device type in the database.
	Label = "device"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInstallationID holds the string denoting the installation_id field in the database.
	FieldInstallationID = "installation_id"
	// FieldLoginID holds the string denoting the login_id field in the database.
	FieldLoginID = "login_id"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldPushToken holds the string denoting the push_token field in the database.
	FieldPushToken = "push_token"
	// FieldDeviceToken holds the string denoting the device_token field in the database.
	FieldDeviceToken = "device_token"
	// FieldAppID holds the string denoting the app_id field in the database.
	FieldAppID = "app_id"
	// FieldAppVersion holds the string denoting the app_version field in the database.
	FieldAppVersion = "app_version"
	// FieldBuildNumber holds the string denoting the build_number field in the database.
	FieldBuildNumber = "build_number"
	// FieldOsVersion holds the string denoting the os_version field in the database.
	FieldOsVersion = "os_version"
	// FieldDeviceModel holds the string denoting the device_model field in the database.
	FieldDeviceModel = "device_model"
	// FieldLocale holds the string denoting the locale field in the database.
	FieldLocale = "locale"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the device in the database.
	Table = "devices"
)

// Columns holds all SQL columns for device fields.
var Columns = []string{
	FieldID,
	FieldInstallationID,
	FieldLoginID,
	FieldPlatform,
	FieldPushToken,
	FieldDeviceToken,
	FieldAppID,
	FieldAppVersion,
	FieldBuildNumber,
	FieldOsVersion,
	FieldDeviceModel,
	FieldLocale,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// InstallationIDValidator is a validator for the "installation_id" field. It is called by the builders before save.
	InstallationIDValidator func(string) error
	// LoginIDValidator is a validator for the "login_id" field. It is called by the builders before save.
	LoginIDValidator func(string) error
	// PushTokenValidator is a validator for the "push_token" field. It is called by the builders before save.
	PushTokenValidator func(string) error
	// DeviceTokenValidator is a validator for the "device_token" field. It is called by the builders before save.
	DeviceTokenValidator func(string) error
	// AppIDValidator is a validator for the "app_id" field. It is called by the builders before save.
	AppIDValidator func(string) error
	// AppVersionValidator is a validator for the "app_version" field. It is called by the builders before save.
	AppVersionValidator func(string) error
	// BuildNumberValidator is a validator for the "build_number" field. It is called by the builders before save.
	BuildNumberValidator func(string) error
	// OsVersionValidator is a validator for the "os_version" field. It is called by the builders before save.
	OsVersionValidator func(string) error
	// DeviceModelValidator is a validator for the "device_model" field. It is called by the builders before save.
	DeviceModelValidator func(string) error
	// LocaleValidator is a validator for the "locale" field. It is called by the builders before save.
	LocaleValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Platform defines the type for the "platform" enum field.
type Platform string

// Platform values.
const (
	PlatformIos     Platform = "ios"
	PlatformAndroid Platform = "android"
)

func (pl Platform) String() string {
	return string(pl)
}

// PlatformValidator is a validator for the "platform" field enum values. It is called by the builders before save.
func PlatformValidator(pl Platform) error {
	switch pl {
	case PlatformIos, PlatformAndroid:
		return nil
	default:
		return fmt.Errorf("device: invalid enum value for platform field: %q", pl)
	}
}

// OrderOption defines the ordering options for the Device queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInstallationID orders the results by the installation_id field.
func ByInstallationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstallationID, opts...).ToFunc()
}

// ByLoginID orders the results by the login_id field.
func ByLoginID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLoginID, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByPushToken orders the results by the push_token field.
func ByPushToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPushToken, opts...).ToFunc()
}

// ByDeviceToken orders the results by the device_token field.
func ByDeviceToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceToken, opts...).ToFunc()
}

// ByAppID orders the results by the app_id field.
func ByAppID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppID, opts...).ToFunc()
}

// ByAppVersion orders the results by the app_version field.
func ByAppVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppVersion, opts...).ToFunc()
}

// ByBuildNumber orders the results by the build_number field.
func ByBuildNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuildNumber, opts...).ToFunc()
}

// ByOsVersion orders the results by the os_version field.
func ByOsVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOsVersion, opts...).ToFunc()
}

// ByDeviceModel orders the results by the device_model field.
func ByDeviceModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceModel, opts...).ToFunc()
}

// ByLocale orders the results by the locale field.
func ByLocale(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocale, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
