// Code generated by ent, DO NOT EDIT.

package devicelogin

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the devicelogin type in the database.
	Label = "device_login"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLoginID holds the string denoting the login_id field in the database.
	FieldLoginID = "login_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeDevice holds the string denoting the device edge name in mutations.
	EdgeDevice = "device"
	// Table holds the table name of the devicelogin in the database.
	Table = "device_logins"
	// DeviceTable is the table that holds the device relation/edge.
	DeviceTable = "device_logins"
	// DeviceInverseTable is the table name for the Device entity.
	// It exists in this package in order to avoid circular dependency with the "device" package.
	DeviceInverseTable = "devices"
	// DeviceColumn is the table column denoting the device relation/edge.
	DeviceColumn = "device_logins"
)

// Columns holds all SQL columns for devicelogin fields.
var Columns = []string{
	FieldID,
	FieldLoginID,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "device_logins"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"device_logins",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// LoginIDValidator is a validator for the "login_id" field. It is called by the builders before save.
	LoginIDValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the DeviceLogin queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLoginID orders the results by the login_id field.
func ByLoginID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLoginID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByDeviceField orders the results by device field.
func ByDeviceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDeviceStep(), sql.OrderByField(field, opts...))
	}
}
func newDeviceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DeviceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DeviceTable, DeviceColumn),
	)
}
