// Code generated by ent, DO NOT EDIT.

package devicelogin

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/nonchan7720/pushshell/backend/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldLTE(FieldID, id))
}

// LoginID applies equality check predicate on the "login_id" field. It's identical to LoginIDEQ.
func LoginID(v string) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldEQ(FieldLoginID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldEQ(FieldCreatedAt, v))
}

// LoginIDEQ applies the EQ predicate on the "login_id" field.
func LoginIDEQ(v string) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldEQ(FieldLoginID, v))
}

// LoginIDNEQ applies the NEQ predicate on the "login_id" field.
func LoginIDNEQ(v string) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldNEQ(FieldLoginID, v))
}

// LoginIDIn applies the In predicate on the "login_id" field.
func LoginIDIn(vs ...string) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldIn(FieldLoginID, vs...))
}

// LoginIDNotIn applies the NotIn predicate on the "login_id" field.
func LoginIDNotIn(vs ...string) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldNotIn(FieldLoginID, vs...))
}

// LoginIDGT applies the GT predicate on the "login_id" field.
func LoginIDGT(v string) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldGT(FieldLoginID, v))
}

// LoginIDGTE applies the GTE predicate on the "login_id" field.
func LoginIDGTE(v string) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldGTE(FieldLoginID, v))
}

// LoginIDLT applies the LT predicate on the "login_id" field.
func LoginIDLT(v string) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldLT(FieldLoginID, v))
}

// LoginIDLTE applies the LTE predicate on the "login_id" field.
func LoginIDLTE(v string) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldLTE(FieldLoginID, v))
}

// LoginIDContains applies the Contains predicate on the "login_id" field.
func LoginIDContains(v string) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldContains(FieldLoginID, v))
}

// LoginIDHasPrefix applies the HasPrefix predicate on the "login_id" field.
func LoginIDHasPrefix(v string) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldHasPrefix(FieldLoginID, v))
}

// LoginIDHasSuffix applies the HasSuffix predicate on the "login_id" field.
func LoginIDHasSuffix(v string) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldHasSuffix(FieldLoginID, v))
}

// LoginIDEqualFold applies the EqualFold predicate on the "login_id" field.
func LoginIDEqualFold(v string) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldEqualFold(FieldLoginID, v))
}

// LoginIDContainsFold applies the ContainsFold predicate on the "login_id" field.
func LoginIDContainsFold(v string) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldContainsFold(FieldLoginID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.FieldLTE(FieldCreatedAt, v))
}

// HasDevice applies the HasEdge predicate on the "device" edge.
func HasDevice() predicate.DeviceLogin {
	return predicate.DeviceLogin(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DeviceTable, DeviceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeviceWith applies the HasEdge predicate on the "device" edge with a given conditions (other predicates).
func HasDeviceWith(preds ...predicate.Device) predicate.DeviceLogin {
	return predicate.DeviceLogin(func(s *sql.Selector) {
		step := newDeviceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DeviceLogin) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DeviceLogin) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DeviceLogin) predicate.DeviceLogin {
	return predicate.DeviceLogin(sql.NotPredicates(p))
}
