-- Create "devices" table
CREATE TABLE "devices" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "installation_id" character varying NOT NULL, "login_id" character varying NOT NULL, "platform" character varying NOT NULL, "push_token" character varying NOT NULL, "device_token" character varying NULL, "app_id" character varying NULL, "app_version" character varying NULL, "build_number" character varying NULL, "os_version" character varying NULL, "device_model" character varying NULL, "locale" character varying NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "device_login_id" to table: "devices"
CREATE INDEX "device_login_id" ON "devices" ("login_id");
-- Create index "device_push_token" to table: "devices"
CREATE INDEX "device_push_token" ON "devices" ("push_token");
-- Create index "devices_installation_id_key" to table: "devices"
CREATE UNIQUE INDEX "devices_installation_id_key" ON "devices" ("installation_id");
