// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DevicesColumns holds the columns for the "devices" table.
	DevicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "installation_id", Type: field.TypeString, Unique: true, Size: 128},
		{Name: "login_id", Type: field.TypeString, Size: 256},
		{Name: "platform", Type: field.TypeEnum, Enums: []string{"ios", "android"}},
		{Name: "push_token", Type: field.TypeString, Size: 512},
		{Name: "device_token", Type: field.TypeString, Nullable: true, Size: 4096},
		{Name: "app_id", Type: field.TypeString, Nullable: true, Size: 256},
		{Name: "app_version", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "build_number", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "os_version", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "device_model", Type: field.TypeString, Nullable: true, Size: 128},
		{Name: "locale", Type: field.TypeString, Nullable: true, Size: 32},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// DevicesTable holds the schema information for the "devices" table.
	DevicesTable = &schema.Table{
		Name:       "devices",
		Columns:    DevicesColumns,
		PrimaryKey: []*schema.Column{DevicesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "device_login_id",
				Unique:  false,
				Columns: []*schema.Column{DevicesColumns[2]},
			},
			{
				Name:    "device_push_token",
				Unique:  false,
				Columns: []*schema.Column{DevicesColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DevicesTable,
	}
)

func init() {
}
