-- Generated by backend/worker/sync-migrations.sh from
-- backend/migrations/sqlite/20260928122212_init.sql. Do not edit by hand:
-- re-run `mise run worker:migrations:sync` instead.
CREATE TABLE `devices` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `installation_id` text NOT NULL, `login_id` text NOT NULL, `platform` text NOT NULL, `push_token` text NOT NULL, `device_token` text NULL, `app_id` text NULL, `app_version` text NULL, `build_number` text NULL, `os_version` text NULL, `device_model` text NULL, `locale` text NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL);
CREATE UNIQUE INDEX `devices_installation_id_key` ON `devices` (`installation_id`);
CREATE INDEX `device_login_id` ON `devices` (`login_id`);
CREATE INDEX `device_push_token` ON `devices` (`push_token`);
