// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nonchan7720/webapp-notification/backend/internal/ent/device"
)

// DeviceCreate is the builder for creating a Device entity.
type DeviceCreate struct {
	config
	mutation *DeviceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetInstallationID sets the "installation_id" field.
func (_c *DeviceCreate) SetInstallationID(v string) *DeviceCreate {
	_c.mutation.SetInstallationID(v)
	return _c
}

// SetLoginID sets the "login_id" field.
func (_c *DeviceCreate) SetLoginID(v string) *DeviceCreate {
	_c.mutation.SetLoginID(v)
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *DeviceCreate) SetPlatform(v device.Platform) *DeviceCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetPushToken sets the "push_token" field.
func (_c *DeviceCreate) SetPushToken(v string) *DeviceCreate {
	_c.mutation.SetPushToken(v)
	return _c
}

// SetNillablePushToken sets the "push_token" field if the given value is not nil.
func (_c *DeviceCreate) SetNillablePushToken(v *string) *DeviceCreate {
	if v != nil {
		_c.SetPushToken(*v)
	}
	return _c
}

// SetDeviceToken sets the "device_token" field.
func (_c *DeviceCreate) SetDeviceToken(v string) *DeviceCreate {
	_c.mutation.SetDeviceToken(v)
	return _c
}

// SetNillableDeviceToken sets the "device_token" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableDeviceToken(v *string) *DeviceCreate {
	if v != nil {
		_c.SetDeviceToken(*v)
	}
	return _c
}

// SetAppID sets the "app_id" field.
func (_c *DeviceCreate) SetAppID(v string) *DeviceCreate {
	_c.mutation.SetAppID(v)
	return _c
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableAppID(v *string) *DeviceCreate {
	if v != nil {
		_c.SetAppID(*v)
	}
	return _c
}

// SetAppVersion sets the "app_version" field.
func (_c *DeviceCreate) SetAppVersion(v string) *DeviceCreate {
	_c.mutation.SetAppVersion(v)
	return _c
}

// SetNillableAppVersion sets the "app_version" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableAppVersion(v *string) *DeviceCreate {
	if v != nil {
		_c.SetAppVersion(*v)
	}
	return _c
}

// SetBuildNumber sets the "build_number" field.
func (_c *DeviceCreate) SetBuildNumber(v string) *DeviceCreate {
	_c.mutation.SetBuildNumber(v)
	return _c
}

// SetNillableBuildNumber sets the "build_number" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableBuildNumber(v *string) *DeviceCreate {
	if v != nil {
		_c.SetBuildNumber(*v)
	}
	return _c
}

// SetOsVersion sets the "os_version" field.
func (_c *DeviceCreate) SetOsVersion(v string) *DeviceCreate {
	_c.mutation.SetOsVersion(v)
	return _c
}

// SetNillableOsVersion sets the "os_version" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableOsVersion(v *string) *DeviceCreate {
	if v != nil {
		_c.SetOsVersion(*v)
	}
	return _c
}

// SetDeviceModel sets the "device_model" field.
func (_c *DeviceCreate) SetDeviceModel(v string) *DeviceCreate {
	_c.mutation.SetDeviceModel(v)
	return _c
}

// SetNillableDeviceModel sets the "device_model" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableDeviceModel(v *string) *DeviceCreate {
	if v != nil {
		_c.SetDeviceModel(*v)
	}
	return _c
}

// SetLocale sets the "locale" field.
func (_c *DeviceCreate) SetLocale(v string) *DeviceCreate {
	_c.mutation.SetLocale(v)
	return _c
}

// SetNillableLocale sets the "locale" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableLocale(v *string) *DeviceCreate {
	if v != nil {
		_c.SetLocale(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DeviceCreate) SetCreatedAt(v time.Time) *DeviceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableCreatedAt(v *time.Time) *DeviceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DeviceCreate) SetUpdatedAt(v time.Time) *DeviceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableUpdatedAt(v *time.Time) *DeviceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the DeviceMutation object of the builder.
func (_c *DeviceCreate) Mutation() *DeviceMutation {
	return _c.mutation
}

// Save creates the Device in the database.
func (_c *DeviceCreate) Save(ctx context.Context) (*Device, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeviceCreate) SaveX(ctx context.Context) *Device {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DeviceCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := device.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := device.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeviceCreate) check() error {
	if _, ok := _c.mutation.InstallationID(); !ok {
		return &ValidationError{Name: "installation_id", err: errors.New(`ent: missing required field "Device.installation_id"`)}
	}
	if v, ok := _c.mutation.InstallationID(); ok {
		if err := device.InstallationIDValidator(v); err != nil {
			return &ValidationError{Name: "installation_id", err: fmt.Errorf(`ent: validator failed for field "Device.installation_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LoginID(); !ok {
		return &ValidationError{Name: "login_id", err: errors.New(`ent: missing required field "Device.login_id"`)}
	}
	if v, ok := _c.mutation.LoginID(); ok {
		if err := device.LoginIDValidator(v); err != nil {
			return &ValidationError{Name: "login_id", err: fmt.Errorf(`ent: validator failed for field "Device.login_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "Device.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := device.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Device.platform": %w`, err)}
		}
	}
	if v, ok := _c.mutation.PushToken(); ok {
		if err := device.PushTokenValidator(v); err != nil {
			return &ValidationError{Name: "push_token", err: fmt.Errorf(`ent: validator failed for field "Device.push_token": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DeviceToken(); ok {
		if err := device.DeviceTokenValidator(v); err != nil {
			return &ValidationError{Name: "device_token", err: fmt.Errorf(`ent: validator failed for field "Device.device_token": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AppID(); ok {
		if err := device.AppIDValidator(v); err != nil {
			return &ValidationError{Name: "app_id", err: fmt.Errorf(`ent: validator failed for field "Device.app_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AppVersion(); ok {
		if err := device.AppVersionValidator(v); err != nil {
			return &ValidationError{Name: "app_version", err: fmt.Errorf(`ent: validator failed for field "Device.app_version": %w`, err)}
		}
	}
	if v, ok := _c.mutation.BuildNumber(); ok {
		if err := device.BuildNumberValidator(v); err != nil {
			return &ValidationError{Name: "build_number", err: fmt.Errorf(`ent: validator failed for field "Device.build_number": %w`, err)}
		}
	}
	if v, ok := _c.mutation.OsVersion(); ok {
		if err := device.OsVersionValidator(v); err != nil {
			return &ValidationError{Name: "os_version", err: fmt.Errorf(`ent: validator failed for field "Device.os_version": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DeviceModel(); ok {
		if err := device.DeviceModelValidator(v); err != nil {
			return &ValidationError{Name: "device_model", err: fmt.Errorf(`ent: validator failed for field "Device.device_model": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Locale(); ok {
		if err := device.LocaleValidator(v); err != nil {
			return &ValidationError{Name: "locale", err: fmt.Errorf(`ent: validator failed for field "Device.locale": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Device.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Device.updated_at"`)}
	}
	return nil
}

func (_c *DeviceCreate) sqlSave(ctx context.Context) (*Device, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeviceCreate) createSpec() (*Device, *sqlgraph.CreateSpec) {
	var (
		_node = &Device{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(device.Table, sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.InstallationID(); ok {
		_spec.SetField(device.FieldInstallationID, field.TypeString, value)
		_node.InstallationID = value
	}
	if value, ok := _c.mutation.LoginID(); ok {
		_spec.SetField(device.FieldLoginID, field.TypeString, value)
		_node.LoginID = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(device.FieldPlatform, field.TypeEnum, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.PushToken(); ok {
		_spec.SetField(device.FieldPushToken, field.TypeString, value)
		_node.PushToken = value
	}
	if value, ok := _c.mutation.DeviceToken(); ok {
		_spec.SetField(device.FieldDeviceToken, field.TypeString, value)
		_node.DeviceToken = value
	}
	if value, ok := _c.mutation.AppID(); ok {
		_spec.SetField(device.FieldAppID, field.TypeString, value)
		_node.AppID = value
	}
	if value, ok := _c.mutation.AppVersion(); ok {
		_spec.SetField(device.FieldAppVersion, field.TypeString, value)
		_node.AppVersion = value
	}
	if value, ok := _c.mutation.BuildNumber(); ok {
		_spec.SetField(device.FieldBuildNumber, field.TypeString, value)
		_node.BuildNumber = value
	}
	if value, ok := _c.mutation.OsVersion(); ok {
		_spec.SetField(device.FieldOsVersion, field.TypeString, value)
		_node.OsVersion = value
	}
	if value, ok := _c.mutation.DeviceModel(); ok {
		_spec.SetField(device.FieldDeviceModel, field.TypeString, value)
		_node.DeviceModel = value
	}
	if value, ok := _c.mutation.Locale(); ok {
		_spec.SetField(device.FieldLocale, field.TypeString, value)
		_node.Locale = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(device.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Device.Create().
//		SetInstallationID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeviceUpsert) {
//			SetInstallationID(v+v).
//		}).
//		Exec(ctx)
func (_c *DeviceCreate) OnConflict(opts ...sql.ConflictOption) *DeviceUpsertOne {
	_c.conflict = opts
	return &DeviceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Device.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DeviceCreate) OnConflictColumns(columns ...string) *DeviceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DeviceUpsertOne{
		create: _c,
	}
}

type (
	// DeviceUpsertOne is the builder for "upsert"-ing
	//  one Device node.
	DeviceUpsertOne struct {
		create *DeviceCreate
	}

	// DeviceUpsert is the "OnConflict" setter.
	DeviceUpsert struct {
		*sql.UpdateSet
	}
)

// SetInstallationID sets the "installation_id" field.
func (u *DeviceUpsert) SetInstallationID(v string) *DeviceUpsert {
	u.Set(device.FieldInstallationID, v)
	return u
}

// UpdateInstallationID sets the "installation_id" field to the value that was provided on create.
func (u *DeviceUpsert) UpdateInstallationID() *DeviceUpsert {
	u.SetExcluded(device.FieldInstallationID)
	return u
}

// SetLoginID sets the "login_id" field.
func (u *DeviceUpsert) SetLoginID(v string) *DeviceUpsert {
	u.Set(device.FieldLoginID, v)
	return u
}

// UpdateLoginID sets the "login_id" field to the value that was provided on create.
func (u *DeviceUpsert) UpdateLoginID() *DeviceUpsert {
	u.SetExcluded(device.FieldLoginID)
	return u
}

// SetPlatform sets the "platform" field.
func (u *DeviceUpsert) SetPlatform(v device.Platform) *DeviceUpsert {
	u.Set(device.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *DeviceUpsert) UpdatePlatform() *DeviceUpsert {
	u.SetExcluded(device.FieldPlatform)
	return u
}

// SetPushToken sets the "push_token" field.
func (u *DeviceUpsert) SetPushToken(v string) *DeviceUpsert {
	u.Set(device.FieldPushToken, v)
	return u
}

// UpdatePushToken sets the "push_token" field to the value that was provided on create.
func (u *DeviceUpsert) UpdatePushToken() *DeviceUpsert {
	u.SetExcluded(device.FieldPushToken)
	return u
}

// ClearPushToken clears the value of the "push_token" field.
func (u *DeviceUpsert) ClearPushToken() *DeviceUpsert {
	u.SetNull(device.FieldPushToken)
	return u
}

// SetDeviceToken sets the "device_token" field.
func (u *DeviceUpsert) SetDeviceToken(v string) *DeviceUpsert {
	u.Set(device.FieldDeviceToken, v)
	return u
}

// UpdateDeviceToken sets the "device_token" field to the value that was provided on create.
func (u *DeviceUpsert) UpdateDeviceToken() *DeviceUpsert {
	u.SetExcluded(device.FieldDeviceToken)
	return u
}

// ClearDeviceToken clears the value of the "device_token" field.
func (u *DeviceUpsert) ClearDeviceToken() *DeviceUpsert {
	u.SetNull(device.FieldDeviceToken)
	return u
}

// SetAppID sets the "app_id" field.
func (u *DeviceUpsert) SetAppID(v string) *DeviceUpsert {
	u.Set(device.FieldAppID, v)
	return u
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *DeviceUpsert) UpdateAppID() *DeviceUpsert {
	u.SetExcluded(device.FieldAppID)
	return u
}

// ClearAppID clears the value of the "app_id" field.
func (u *DeviceUpsert) ClearAppID() *DeviceUpsert {
	u.SetNull(device.FieldAppID)
	return u
}

// SetAppVersion sets the "app_version" field.
func (u *DeviceUpsert) SetAppVersion(v string) *DeviceUpsert {
	u.Set(device.FieldAppVersion, v)
	return u
}

// UpdateAppVersion sets the "app_version" field to the value that was provided on create.
func (u *DeviceUpsert) UpdateAppVersion() *DeviceUpsert {
	u.SetExcluded(device.FieldAppVersion)
	return u
}

// ClearAppVersion clears the value of the "app_version" field.
func (u *DeviceUpsert) ClearAppVersion() *DeviceUpsert {
	u.SetNull(device.FieldAppVersion)
	return u
}

// SetBuildNumber sets the "build_number" field.
func (u *DeviceUpsert) SetBuildNumber(v string) *DeviceUpsert {
	u.Set(device.FieldBuildNumber, v)
	return u
}

// UpdateBuildNumber sets the "build_number" field to the value that was provided on create.
func (u *DeviceUpsert) UpdateBuildNumber() *DeviceUpsert {
	u.SetExcluded(device.FieldBuildNumber)
	return u
}

// ClearBuildNumber clears the value of the "build_number" field.
func (u *DeviceUpsert) ClearBuildNumber() *DeviceUpsert {
	u.SetNull(device.FieldBuildNumber)
	return u
}

// SetOsVersion sets the "os_version" field.
func (u *DeviceUpsert) SetOsVersion(v string) *DeviceUpsert {
	u.Set(device.FieldOsVersion, v)
	return u
}

// UpdateOsVersion sets the "os_version" field to the value that was provided on create.
func (u *DeviceUpsert) UpdateOsVersion() *DeviceUpsert {
	u.SetExcluded(device.FieldOsVersion)
	return u
}

// ClearOsVersion clears the value of the "os_version" field.
func (u *DeviceUpsert) ClearOsVersion() *DeviceUpsert {
	u.SetNull(device.FieldOsVersion)
	return u
}

// SetDeviceModel sets the "device_model" field.
func (u *DeviceUpsert) SetDeviceModel(v string) *DeviceUpsert {
	u.Set(device.FieldDeviceModel, v)
	return u
}

// UpdateDeviceModel sets the "device_model" field to the value that was provided on create.
func (u *DeviceUpsert) UpdateDeviceModel() *DeviceUpsert {
	u.SetExcluded(device.FieldDeviceModel)
	return u
}

// ClearDeviceModel clears the value of the "device_model" field.
func (u *DeviceUpsert) ClearDeviceModel() *DeviceUpsert {
	u.SetNull(device.FieldDeviceModel)
	return u
}

// SetLocale sets the "locale" field.
func (u *DeviceUpsert) SetLocale(v string) *DeviceUpsert {
	u.Set(device.FieldLocale, v)
	return u
}

// UpdateLocale sets the "locale" field to the value that was provided on create.
func (u *DeviceUpsert) UpdateLocale() *DeviceUpsert {
	u.SetExcluded(device.FieldLocale)
	return u
}

// ClearLocale clears the value of the "locale" field.
func (u *DeviceUpsert) ClearLocale() *DeviceUpsert {
	u.SetNull(device.FieldLocale)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DeviceUpsert) SetUpdatedAt(v time.Time) *DeviceUpsert {
	u.Set(device.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DeviceUpsert) UpdateUpdatedAt() *DeviceUpsert {
	u.SetExcluded(device.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Device.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DeviceUpsertOne) UpdateNewValues() *DeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(device.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Device.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DeviceUpsertOne) Ignore() *DeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeviceUpsertOne) DoNothing() *DeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeviceCreate.OnConflict
// documentation for more info.
func (u *DeviceUpsertOne) Update(set func(*DeviceUpsert)) *DeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeviceUpsert{UpdateSet: update})
	}))
	return u
}

// SetInstallationID sets the "installation_id" field.
func (u *DeviceUpsertOne) SetInstallationID(v string) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetInstallationID(v)
	})
}

// UpdateInstallationID sets the "installation_id" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdateInstallationID() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateInstallationID()
	})
}

// SetLoginID sets the "login_id" field.
func (u *DeviceUpsertOne) SetLoginID(v string) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetLoginID(v)
	})
}

// UpdateLoginID sets the "login_id" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdateLoginID() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateLoginID()
	})
}

// SetPlatform sets the "platform" field.
func (u *DeviceUpsertOne) SetPlatform(v device.Platform) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdatePlatform() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdatePlatform()
	})
}

// SetPushToken sets the "push_token" field.
func (u *DeviceUpsertOne) SetPushToken(v string) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetPushToken(v)
	})
}

// UpdatePushToken sets the "push_token" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdatePushToken() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdatePushToken()
	})
}

// ClearPushToken clears the value of the "push_token" field.
func (u *DeviceUpsertOne) ClearPushToken() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearPushToken()
	})
}

// SetDeviceToken sets the "device_token" field.
func (u *DeviceUpsertOne) SetDeviceToken(v string) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetDeviceToken(v)
	})
}

// UpdateDeviceToken sets the "device_token" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdateDeviceToken() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateDeviceToken()
	})
}

// ClearDeviceToken clears the value of the "device_token" field.
func (u *DeviceUpsertOne) ClearDeviceToken() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearDeviceToken()
	})
}

// SetAppID sets the "app_id" field.
func (u *DeviceUpsertOne) SetAppID(v string) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetAppID(v)
	})
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdateAppID() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateAppID()
	})
}

// ClearAppID clears the value of the "app_id" field.
func (u *DeviceUpsertOne) ClearAppID() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearAppID()
	})
}

// SetAppVersion sets the "app_version" field.
func (u *DeviceUpsertOne) SetAppVersion(v string) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetAppVersion(v)
	})
}

// UpdateAppVersion sets the "app_version" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdateAppVersion() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateAppVersion()
	})
}

// ClearAppVersion clears the value of the "app_version" field.
func (u *DeviceUpsertOne) ClearAppVersion() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearAppVersion()
	})
}

// SetBuildNumber sets the "build_number" field.
func (u *DeviceUpsertOne) SetBuildNumber(v string) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetBuildNumber(v)
	})
}

// UpdateBuildNumber sets the "build_number" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdateBuildNumber() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateBuildNumber()
	})
}

// ClearBuildNumber clears the value of the "build_number" field.
func (u *DeviceUpsertOne) ClearBuildNumber() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearBuildNumber()
	})
}

// SetOsVersion sets the "os_version" field.
func (u *DeviceUpsertOne) SetOsVersion(v string) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetOsVersion(v)
	})
}

// UpdateOsVersion sets the "os_version" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdateOsVersion() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateOsVersion()
	})
}

// ClearOsVersion clears the value of the "os_version" field.
func (u *DeviceUpsertOne) ClearOsVersion() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearOsVersion()
	})
}

// SetDeviceModel sets the "device_model" field.
func (u *DeviceUpsertOne) SetDeviceModel(v string) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetDeviceModel(v)
	})
}

// UpdateDeviceModel sets the "device_model" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdateDeviceModel() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateDeviceModel()
	})
}

// ClearDeviceModel clears the value of the "device_model" field.
func (u *DeviceUpsertOne) ClearDeviceModel() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearDeviceModel()
	})
}

// SetLocale sets the "locale" field.
func (u *DeviceUpsertOne) SetLocale(v string) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetLocale(v)
	})
}

// UpdateLocale sets the "locale" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdateLocale() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateLocale()
	})
}

// ClearLocale clears the value of the "locale" field.
func (u *DeviceUpsertOne) ClearLocale() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearLocale()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DeviceUpsertOne) SetUpdatedAt(v time.Time) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdateUpdatedAt() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DeviceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeviceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeviceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DeviceUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DeviceUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DeviceCreateBulk is the builder for creating many Device entities in bulk.
type DeviceCreateBulk struct {
	config
	err      error
	builders []*DeviceCreate
	conflict []sql.ConflictOption
}

// Save creates the Device entities in the database.
func (_c *DeviceCreateBulk) Save(ctx context.Context) ([]*Device, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Device, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeviceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeviceCreateBulk) SaveX(ctx context.Context) []*Device {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Device.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeviceUpsert) {
//			SetInstallationID(v+v).
//		}).
//		Exec(ctx)
func (_c *DeviceCreateBulk) OnConflict(opts ...sql.ConflictOption) *DeviceUpsertBulk {
	_c.conflict = opts
	return &DeviceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Device.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DeviceCreateBulk) OnConflictColumns(columns ...string) *DeviceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DeviceUpsertBulk{
		create: _c,
	}
}

// DeviceUpsertBulk is the builder for "upsert"-ing
// a bulk of Device nodes.
type DeviceUpsertBulk struct {
	create *DeviceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Device.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DeviceUpsertBulk) UpdateNewValues() *DeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(device.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Device.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DeviceUpsertBulk) Ignore() *DeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeviceUpsertBulk) DoNothing() *DeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeviceCreateBulk.OnConflict
// documentation for more info.
func (u *DeviceUpsertBulk) Update(set func(*DeviceUpsert)) *DeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeviceUpsert{UpdateSet: update})
	}))
	return u
}

// SetInstallationID sets the "installation_id" field.
func (u *DeviceUpsertBulk) SetInstallationID(v string) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetInstallationID(v)
	})
}

// UpdateInstallationID sets the "installation_id" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdateInstallationID() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateInstallationID()
	})
}

// SetLoginID sets the "login_id" field.
func (u *DeviceUpsertBulk) SetLoginID(v string) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetLoginID(v)
	})
}

// UpdateLoginID sets the "login_id" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdateLoginID() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateLoginID()
	})
}

// SetPlatform sets the "platform" field.
func (u *DeviceUpsertBulk) SetPlatform(v device.Platform) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdatePlatform() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdatePlatform()
	})
}

// SetPushToken sets the "push_token" field.
func (u *DeviceUpsertBulk) SetPushToken(v string) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetPushToken(v)
	})
}

// UpdatePushToken sets the "push_token" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdatePushToken() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdatePushToken()
	})
}

// ClearPushToken clears the value of the "push_token" field.
func (u *DeviceUpsertBulk) ClearPushToken() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearPushToken()
	})
}

// SetDeviceToken sets the "device_token" field.
func (u *DeviceUpsertBulk) SetDeviceToken(v string) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetDeviceToken(v)
	})
}

// UpdateDeviceToken sets the "device_token" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdateDeviceToken() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateDeviceToken()
	})
}

// ClearDeviceToken clears the value of the "device_token" field.
func (u *DeviceUpsertBulk) ClearDeviceToken() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearDeviceToken()
	})
}

// SetAppID sets the "app_id" field.
func (u *DeviceUpsertBulk) SetAppID(v string) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetAppID(v)
	})
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdateAppID() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateAppID()
	})
}

// ClearAppID clears the value of the "app_id" field.
func (u *DeviceUpsertBulk) ClearAppID() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearAppID()
	})
}

// SetAppVersion sets the "app_version" field.
func (u *DeviceUpsertBulk) SetAppVersion(v string) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetAppVersion(v)
	})
}

// UpdateAppVersion sets the "app_version" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdateAppVersion() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateAppVersion()
	})
}

// ClearAppVersion clears the value of the "app_version" field.
func (u *DeviceUpsertBulk) ClearAppVersion() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearAppVersion()
	})
}

// SetBuildNumber sets the "build_number" field.
func (u *DeviceUpsertBulk) SetBuildNumber(v string) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetBuildNumber(v)
	})
}

// UpdateBuildNumber sets the "build_number" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdateBuildNumber() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateBuildNumber()
	})
}

// ClearBuildNumber clears the value of the "build_number" field.
func (u *DeviceUpsertBulk) ClearBuildNumber() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearBuildNumber()
	})
}

// SetOsVersion sets the "os_version" field.
func (u *DeviceUpsertBulk) SetOsVersion(v string) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetOsVersion(v)
	})
}

// UpdateOsVersion sets the "os_version" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdateOsVersion() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateOsVersion()
	})
}

// ClearOsVersion clears the value of the "os_version" field.
func (u *DeviceUpsertBulk) ClearOsVersion() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearOsVersion()
	})
}

// SetDeviceModel sets the "device_model" field.
func (u *DeviceUpsertBulk) SetDeviceModel(v string) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetDeviceModel(v)
	})
}

// UpdateDeviceModel sets the "device_model" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdateDeviceModel() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateDeviceModel()
	})
}

// ClearDeviceModel clears the value of the "device_model" field.
func (u *DeviceUpsertBulk) ClearDeviceModel() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearDeviceModel()
	})
}

// SetLocale sets the "locale" field.
func (u *DeviceUpsertBulk) SetLocale(v string) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetLocale(v)
	})
}

// UpdateLocale sets the "locale" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdateLocale() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateLocale()
	})
}

// ClearLocale clears the value of the "locale" field.
func (u *DeviceUpsertBulk) ClearLocale() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearLocale()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DeviceUpsertBulk) SetUpdatedAt(v time.Time) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdateUpdatedAt() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DeviceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DeviceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeviceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeviceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
