// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nonchan7720/pushshell/backend/internal/ent/device"
	"github.com/nonchan7720/pushshell/backend/internal/ent/devicelogin"
)

// DeviceLoginCreate is the builder for creating a DeviceLogin entity.
type DeviceLoginCreate struct {
	config
	mutation *DeviceLoginMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetLoginID sets the "login_id" field.
func (_c *DeviceLoginCreate) SetLoginID(v string) *DeviceLoginCreate {
	_c.mutation.SetLoginID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DeviceLoginCreate) SetCreatedAt(v time.Time) *DeviceLoginCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DeviceLoginCreate) SetNillableCreatedAt(v *time.Time) *DeviceLoginCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetDeviceID sets the "device" edge to the Device entity by ID.
func (_c *DeviceLoginCreate) SetDeviceID(id int) *DeviceLoginCreate {
	_c.mutation.SetDeviceID(id)
	return _c
}

// SetDevice sets the "device" edge to the Device entity.
func (_c *DeviceLoginCreate) SetDevice(v *Device) *DeviceLoginCreate {
	return _c.SetDeviceID(v.ID)
}

// Mutation returns the DeviceLoginMutation object of the builder.
func (_c *DeviceLoginCreate) Mutation() *DeviceLoginMutation {
	return _c.mutation
}

// Save creates the DeviceLogin in the database.
func (_c *DeviceLoginCreate) Save(ctx context.Context) (*DeviceLogin, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeviceLoginCreate) SaveX(ctx context.Context) *DeviceLogin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceLoginCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceLoginCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DeviceLoginCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := devicelogin.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeviceLoginCreate) check() error {
	if _, ok := _c.mutation.LoginID(); !ok {
		return &ValidationError{Name: "login_id", err: errors.New(`ent: missing required field "DeviceLogin.login_id"`)}
	}
	if v, ok := _c.mutation.LoginID(); ok {
		if err := devicelogin.LoginIDValidator(v); err != nil {
			return &ValidationError{Name: "login_id", err: fmt.Errorf(`ent: validator failed for field "DeviceLogin.login_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DeviceLogin.created_at"`)}
	}
	if len(_c.mutation.DeviceIDs()) == 0 {
		return &ValidationError{Name: "device", err: errors.New(`ent: missing required edge "DeviceLogin.device"`)}
	}
	return nil
}

func (_c *DeviceLoginCreate) sqlSave(ctx context.Context) (*DeviceLogin, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeviceLoginCreate) createSpec() (*DeviceLogin, *sqlgraph.CreateSpec) {
	var (
		_node = &DeviceLogin{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(devicelogin.Table, sqlgraph.NewFieldSpec(devicelogin.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.LoginID(); ok {
		_spec.SetField(devicelogin.FieldLoginID, field.TypeString, value)
		_node.LoginID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(devicelogin.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.DeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   devicelogin.DeviceTable,
			Columns: []string{devicelogin.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.device_logins = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DeviceLogin.Create().
//		SetLoginID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeviceLoginUpsert) {
//			SetLoginID(v+v).
//		}).
//		Exec(ctx)
func (_c *DeviceLoginCreate) OnConflict(opts ...sql.ConflictOption) *DeviceLoginUpsertOne {
	_c.conflict = opts
	return &DeviceLoginUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DeviceLogin.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DeviceLoginCreate) OnConflictColumns(columns ...string) *DeviceLoginUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DeviceLoginUpsertOne{
		create: _c,
	}
}

type (
	// DeviceLoginUpsertOne is the builder for "upsert"-ing
	//  one DeviceLogin node.
	DeviceLoginUpsertOne struct {
		create *DeviceLoginCreate
	}

	// DeviceLoginUpsert is the "OnConflict" setter.
	DeviceLoginUpsert struct {
		*sql.UpdateSet
	}
)

// SetLoginID sets the "login_id" field.
func (u *DeviceLoginUpsert) SetLoginID(v string) *DeviceLoginUpsert {
	u.Set(devicelogin.FieldLoginID, v)
	return u
}

// UpdateLoginID sets the "login_id" field to the value that was provided on create.
func (u *DeviceLoginUpsert) UpdateLoginID() *DeviceLoginUpsert {
	u.SetExcluded(devicelogin.FieldLoginID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.DeviceLogin.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DeviceLoginUpsertOne) UpdateNewValues() *DeviceLoginUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(devicelogin.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DeviceLogin.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DeviceLoginUpsertOne) Ignore() *DeviceLoginUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeviceLoginUpsertOne) DoNothing() *DeviceLoginUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeviceLoginCreate.OnConflict
// documentation for more info.
func (u *DeviceLoginUpsertOne) Update(set func(*DeviceLoginUpsert)) *DeviceLoginUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeviceLoginUpsert{UpdateSet: update})
	}))
	return u
}

// SetLoginID sets the "login_id" field.
func (u *DeviceLoginUpsertOne) SetLoginID(v string) *DeviceLoginUpsertOne {
	return u.Update(func(s *DeviceLoginUpsert) {
		s.SetLoginID(v)
	})
}

// UpdateLoginID sets the "login_id" field to the value that was provided on create.
func (u *DeviceLoginUpsertOne) UpdateLoginID() *DeviceLoginUpsertOne {
	return u.Update(func(s *DeviceLoginUpsert) {
		s.UpdateLoginID()
	})
}

// Exec executes the query.
func (u *DeviceLoginUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeviceLoginCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeviceLoginUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DeviceLoginUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DeviceLoginUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DeviceLoginCreateBulk is the builder for creating many DeviceLogin entities in bulk.
type DeviceLoginCreateBulk struct {
	config
	err      error
	builders []*DeviceLoginCreate
	conflict []sql.ConflictOption
}

// Save creates the DeviceLogin entities in the database.
func (_c *DeviceLoginCreateBulk) Save(ctx context.Context) ([]*DeviceLogin, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DeviceLogin, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeviceLoginMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeviceLoginCreateBulk) SaveX(ctx context.Context) []*DeviceLogin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceLoginCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceLoginCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DeviceLogin.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeviceLoginUpsert) {
//			SetLoginID(v+v).
//		}).
//		Exec(ctx)
func (_c *DeviceLoginCreateBulk) OnConflict(opts ...sql.ConflictOption) *DeviceLoginUpsertBulk {
	_c.conflict = opts
	return &DeviceLoginUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DeviceLogin.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DeviceLoginCreateBulk) OnConflictColumns(columns ...string) *DeviceLoginUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DeviceLoginUpsertBulk{
		create: _c,
	}
}

// DeviceLoginUpsertBulk is the builder for "upsert"-ing
// a bulk of DeviceLogin nodes.
type DeviceLoginUpsertBulk struct {
	create *DeviceLoginCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DeviceLogin.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DeviceLoginUpsertBulk) UpdateNewValues() *DeviceLoginUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(devicelogin.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DeviceLogin.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DeviceLoginUpsertBulk) Ignore() *DeviceLoginUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeviceLoginUpsertBulk) DoNothing() *DeviceLoginUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeviceLoginCreateBulk.OnConflict
// documentation for more info.
func (u *DeviceLoginUpsertBulk) Update(set func(*DeviceLoginUpsert)) *DeviceLoginUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeviceLoginUpsert{UpdateSet: update})
	}))
	return u
}

// SetLoginID sets the "login_id" field.
func (u *DeviceLoginUpsertBulk) SetLoginID(v string) *DeviceLoginUpsertBulk {
	return u.Update(func(s *DeviceLoginUpsert) {
		s.SetLoginID(v)
	})
}

// UpdateLoginID sets the "login_id" field to the value that was provided on create.
func (u *DeviceLoginUpsertBulk) UpdateLoginID() *DeviceLoginUpsertBulk {
	return u.Update(func(s *DeviceLoginUpsert) {
		s.UpdateLoginID()
	})
}

// Exec executes the query.
func (u *DeviceLoginUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DeviceLoginCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeviceLoginCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeviceLoginUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
