// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/nonchan7720/webapp-notification/backend/internal/ent/device"
)

// Device is the model entity for the Device schema.
type Device struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// アプリインストールごとに生成される安定した ID
	InstallationID string `json:"installation_id,omitempty"`
	// Web アプリのログイン ID
	LoginID string `json:"login_id,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform device.Platform `json:"platform,omitempty"`
	// Expo Push Token
	PushToken string `json:"push_token,omitempty"`
	// ネイティブのデバイストークン (APNs / FCM)
	DeviceToken string `json:"device_token,omitempty"`
	// AppID holds the value of the "app_id" field.
	AppID string `json:"app_id,omitempty"`
	// AppVersion holds the value of the "app_version" field.
	AppVersion string `json:"app_version,omitempty"`
	// BuildNumber holds the value of the "build_number" field.
	BuildNumber string `json:"build_number,omitempty"`
	// OsVersion holds the value of the "os_version" field.
	OsVersion string `json:"os_version,omitempty"`
	// DeviceModel holds the value of the "device_model" field.
	DeviceModel string `json:"device_model,omitempty"`
	// Locale holds the value of the "locale" field.
	Locale string `json:"locale,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Device) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case device.FieldID:
			values[i] = new(sql.NullInt64)
		case device.FieldInstallationID, device.FieldLoginID, device.FieldPlatform, device.FieldPushToken, device.FieldDeviceToken, device.FieldAppID, device.FieldAppVersion, device.FieldBuildNumber, device.FieldOsVersion, device.FieldDeviceModel, device.FieldLocale:
			values[i] = new(sql.NullString)
		case device.FieldCreatedAt, device.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Device fields.
func (_m *Device) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case device.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case device.FieldInstallationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field installation_id", values[i])
			} else if value.Valid {
				_m.InstallationID = value.String
			}
		case device.FieldLoginID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field login_id", values[i])
			} else if value.Valid {
				_m.LoginID = value.String
			}
		case device.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = device.Platform(value.String)
			}
		case device.FieldPushToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field push_token", values[i])
			} else if value.Valid {
				_m.PushToken = value.String
			}
		case device.FieldDeviceToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device_token", values[i])
			} else if value.Valid {
				_m.DeviceToken = value.String
			}
		case device.FieldAppID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field app_id", values[i])
			} else if value.Valid {
				_m.AppID = value.String
			}
		case device.FieldAppVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field app_version", values[i])
			} else if value.Valid {
				_m.AppVersion = value.String
			}
		case device.FieldBuildNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field build_number", values[i])
			} else if value.Valid {
				_m.BuildNumber = value.String
			}
		case device.FieldOsVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field os_version", values[i])
			} else if value.Valid {
				_m.OsVersion = value.String
			}
		case device.FieldDeviceModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device_model", values[i])
			} else if value.Valid {
				_m.DeviceModel = value.String
			}
		case device.FieldLocale:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field locale", values[i])
			} else if value.Valid {
				_m.Locale = value.String
			}
		case device.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case device.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Device.
// This includes values selected through modifiers, order, etc.
func (_m *Device) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Device.
// Note that you need to call Device.Unwrap() before calling this method if this Device
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Device) Update() *DeviceUpdateOne {
	return NewDeviceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Device entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Device) Unwrap() *Device {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Device is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Device) String() string {
	var builder strings.Builder
	builder.WriteString("Device(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("installation_id=")
	builder.WriteString(_m.InstallationID)
	builder.WriteString(", ")
	builder.WriteString("login_id=")
	builder.WriteString(_m.LoginID)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(fmt.Sprintf("%v", _m.Platform))
	builder.WriteString(", ")
	builder.WriteString("push_token=")
	builder.WriteString(_m.PushToken)
	builder.WriteString(", ")
	builder.WriteString("device_token=")
	builder.WriteString(_m.DeviceToken)
	builder.WriteString(", ")
	builder.WriteString("app_id=")
	builder.WriteString(_m.AppID)
	builder.WriteString(", ")
	builder.WriteString("app_version=")
	builder.WriteString(_m.AppVersion)
	builder.WriteString(", ")
	builder.WriteString("build_number=")
	builder.WriteString(_m.BuildNumber)
	builder.WriteString(", ")
	builder.WriteString("os_version=")
	builder.WriteString(_m.OsVersion)
	builder.WriteString(", ")
	builder.WriteString("device_model=")
	builder.WriteString(_m.DeviceModel)
	builder.WriteString(", ")
	builder.WriteString("locale=")
	builder.WriteString(_m.Locale)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Devices is a parsable slice of Device.
type Devices []*Device
