// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nonchan7720/webapp-notification/backend/internal/ent/device"
	"github.com/nonchan7720/webapp-notification/backend/internal/ent/devicelogin"
	"github.com/nonchan7720/webapp-notification/backend/internal/ent/predicate"
)

// DeviceUpdate is the builder for updating Device entities.
type DeviceUpdate struct {
	config
	hooks    []Hook
	mutation *DeviceMutation
}

// Where appends a list predicates to the DeviceUpdate builder.
func (_u *DeviceUpdate) Where(ps ...predicate.Device) *DeviceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetInstallationID sets the "installation_id" field.
func (_u *DeviceUpdate) SetInstallationID(v string) *DeviceUpdate {
	_u.mutation.SetInstallationID(v)
	return _u
}

// SetNillableInstallationID sets the "installation_id" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableInstallationID(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetInstallationID(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *DeviceUpdate) SetPlatform(v device.Platform) *DeviceUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillablePlatform(v *device.Platform) *DeviceUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetPushToken sets the "push_token" field.
func (_u *DeviceUpdate) SetPushToken(v string) *DeviceUpdate {
	_u.mutation.SetPushToken(v)
	return _u
}

// SetNillablePushToken sets the "push_token" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillablePushToken(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetPushToken(*v)
	}
	return _u
}

// ClearPushToken clears the value of the "push_token" field.
func (_u *DeviceUpdate) ClearPushToken() *DeviceUpdate {
	_u.mutation.ClearPushToken()
	return _u
}

// SetDeviceToken sets the "device_token" field.
func (_u *DeviceUpdate) SetDeviceToken(v string) *DeviceUpdate {
	_u.mutation.SetDeviceToken(v)
	return _u
}

// SetNillableDeviceToken sets the "device_token" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableDeviceToken(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetDeviceToken(*v)
	}
	return _u
}

// ClearDeviceToken clears the value of the "device_token" field.
func (_u *DeviceUpdate) ClearDeviceToken() *DeviceUpdate {
	_u.mutation.ClearDeviceToken()
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *DeviceUpdate) SetAppID(v string) *DeviceUpdate {
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableAppID(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// ClearAppID clears the value of the "app_id" field.
func (_u *DeviceUpdate) ClearAppID() *DeviceUpdate {
	_u.mutation.ClearAppID()
	return _u
}

// SetAppVersion sets the "app_version" field.
func (_u *DeviceUpdate) SetAppVersion(v string) *DeviceUpdate {
	_u.mutation.SetAppVersion(v)
	return _u
}

// SetNillableAppVersion sets the "app_version" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableAppVersion(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetAppVersion(*v)
	}
	return _u
}

// ClearAppVersion clears the value of the "app_version" field.
func (_u *DeviceUpdate) ClearAppVersion() *DeviceUpdate {
	_u.mutation.ClearAppVersion()
	return _u
}

// SetBuildNumber sets the "build_number" field.
func (_u *DeviceUpdate) SetBuildNumber(v string) *DeviceUpdate {
	_u.mutation.SetBuildNumber(v)
	return _u
}

// SetNillableBuildNumber sets the "build_number" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableBuildNumber(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetBuildNumber(*v)
	}
	return _u
}

// ClearBuildNumber clears the value of the "build_number" field.
func (_u *DeviceUpdate) ClearBuildNumber() *DeviceUpdate {
	_u.mutation.ClearBuildNumber()
	return _u
}

// SetOsVersion sets the "os_version" field.
func (_u *DeviceUpdate) SetOsVersion(v string) *DeviceUpdate {
	_u.mutation.SetOsVersion(v)
	return _u
}

// SetNillableOsVersion sets the "os_version" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableOsVersion(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetOsVersion(*v)
	}
	return _u
}

// ClearOsVersion clears the value of the "os_version" field.
func (_u *DeviceUpdate) ClearOsVersion() *DeviceUpdate {
	_u.mutation.ClearOsVersion()
	return _u
}

// SetDeviceModel sets the "device_model" field.
func (_u *DeviceUpdate) SetDeviceModel(v string) *DeviceUpdate {
	_u.mutation.SetDeviceModel(v)
	return _u
}

// SetNillableDeviceModel sets the "device_model" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableDeviceModel(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetDeviceModel(*v)
	}
	return _u
}

// ClearDeviceModel clears the value of the "device_model" field.
func (_u *DeviceUpdate) ClearDeviceModel() *DeviceUpdate {
	_u.mutation.ClearDeviceModel()
	return _u
}

// SetLocale sets the "locale" field.
func (_u *DeviceUpdate) SetLocale(v string) *DeviceUpdate {
	_u.mutation.SetLocale(v)
	return _u
}

// SetNillableLocale sets the "locale" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableLocale(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetLocale(*v)
	}
	return _u
}

// ClearLocale clears the value of the "locale" field.
func (_u *DeviceUpdate) ClearLocale() *DeviceUpdate {
	_u.mutation.ClearLocale()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeviceUpdate) SetUpdatedAt(v time.Time) *DeviceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddLoginIDs adds the "logins" edge to the DeviceLogin entity by IDs.
func (_u *DeviceUpdate) AddLoginIDs(ids ...int) *DeviceUpdate {
	_u.mutation.AddLoginIDs(ids...)
	return _u
}

// AddLogins adds the "logins" edges to the DeviceLogin entity.
func (_u *DeviceUpdate) AddLogins(v ...*DeviceLogin) *DeviceUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLoginIDs(ids...)
}

// Mutation returns the DeviceMutation object of the builder.
func (_u *DeviceUpdate) Mutation() *DeviceMutation {
	return _u.mutation
}

// ClearLogins clears all "logins" edges to the DeviceLogin entity.
func (_u *DeviceUpdate) ClearLogins() *DeviceUpdate {
	_u.mutation.ClearLogins()
	return _u
}

// RemoveLoginIDs removes the "logins" edge to DeviceLogin entities by IDs.
func (_u *DeviceUpdate) RemoveLoginIDs(ids ...int) *DeviceUpdate {
	_u.mutation.RemoveLoginIDs(ids...)
	return _u
}

// RemoveLogins removes "logins" edges to DeviceLogin entities.
func (_u *DeviceUpdate) RemoveLogins(v ...*DeviceLogin) *DeviceUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLoginIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeviceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeviceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeviceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := device.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceUpdate) check() error {
	if v, ok := _u.mutation.InstallationID(); ok {
		if err := device.InstallationIDValidator(v); err != nil {
			return &ValidationError{Name: "installation_id", err: fmt.Errorf(`ent: validator failed for field "Device.installation_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := device.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Device.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PushToken(); ok {
		if err := device.PushTokenValidator(v); err != nil {
			return &ValidationError{Name: "push_token", err: fmt.Errorf(`ent: validator failed for field "Device.push_token": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceToken(); ok {
		if err := device.DeviceTokenValidator(v); err != nil {
			return &ValidationError{Name: "device_token", err: fmt.Errorf(`ent: validator failed for field "Device.device_token": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AppID(); ok {
		if err := device.AppIDValidator(v); err != nil {
			return &ValidationError{Name: "app_id", err: fmt.Errorf(`ent: validator failed for field "Device.app_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AppVersion(); ok {
		if err := device.AppVersionValidator(v); err != nil {
			return &ValidationError{Name: "app_version", err: fmt.Errorf(`ent: validator failed for field "Device.app_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BuildNumber(); ok {
		if err := device.BuildNumberValidator(v); err != nil {
			return &ValidationError{Name: "build_number", err: fmt.Errorf(`ent: validator failed for field "Device.build_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OsVersion(); ok {
		if err := device.OsVersionValidator(v); err != nil {
			return &ValidationError{Name: "os_version", err: fmt.Errorf(`ent: validator failed for field "Device.os_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceModel(); ok {
		if err := device.DeviceModelValidator(v); err != nil {
			return &ValidationError{Name: "device_model", err: fmt.Errorf(`ent: validator failed for field "Device.device_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Locale(); ok {
		if err := device.LocaleValidator(v); err != nil {
			return &ValidationError{Name: "locale", err: fmt.Errorf(`ent: validator failed for field "Device.locale": %w`, err)}
		}
	}
	return nil
}

func (_u *DeviceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(device.Table, device.Columns, sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.InstallationID(); ok {
		_spec.SetField(device.FieldInstallationID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(device.FieldPlatform, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PushToken(); ok {
		_spec.SetField(device.FieldPushToken, field.TypeString, value)
	}
	if _u.mutation.PushTokenCleared() {
		_spec.ClearField(device.FieldPushToken, field.TypeString)
	}
	if value, ok := _u.mutation.DeviceToken(); ok {
		_spec.SetField(device.FieldDeviceToken, field.TypeString, value)
	}
	if _u.mutation.DeviceTokenCleared() {
		_spec.ClearField(device.FieldDeviceToken, field.TypeString)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(device.FieldAppID, field.TypeString, value)
	}
	if _u.mutation.AppIDCleared() {
		_spec.ClearField(device.FieldAppID, field.TypeString)
	}
	if value, ok := _u.mutation.AppVersion(); ok {
		_spec.SetField(device.FieldAppVersion, field.TypeString, value)
	}
	if _u.mutation.AppVersionCleared() {
		_spec.ClearField(device.FieldAppVersion, field.TypeString)
	}
	if value, ok := _u.mutation.BuildNumber(); ok {
		_spec.SetField(device.FieldBuildNumber, field.TypeString, value)
	}
	if _u.mutation.BuildNumberCleared() {
		_spec.ClearField(device.FieldBuildNumber, field.TypeString)
	}
	if value, ok := _u.mutation.OsVersion(); ok {
		_spec.SetField(device.FieldOsVersion, field.TypeString, value)
	}
	if _u.mutation.OsVersionCleared() {
		_spec.ClearField(device.FieldOsVersion, field.TypeString)
	}
	if value, ok := _u.mutation.DeviceModel(); ok {
		_spec.SetField(device.FieldDeviceModel, field.TypeString, value)
	}
	if _u.mutation.DeviceModelCleared() {
		_spec.ClearField(device.FieldDeviceModel, field.TypeString)
	}
	if value, ok := _u.mutation.Locale(); ok {
		_spec.SetField(device.FieldLocale, field.TypeString, value)
	}
	if _u.mutation.LocaleCleared() {
		_spec.ClearField(device.FieldLocale, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.LoginsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   device.LoginsTable,
			Columns: []string{device.LoginsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(devicelogin.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLoginsIDs(); len(nodes) > 0 && !_u.mutation.LoginsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   device.LoginsTable,
			Columns: []string{device.LoginsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(devicelogin.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LoginsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   device.LoginsTable,
			Columns: []string{device.LoginsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(devicelogin.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeviceUpdateOne is the builder for updating a single Device entity.
type DeviceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeviceMutation
}

// SetInstallationID sets the "installation_id" field.
func (_u *DeviceUpdateOne) SetInstallationID(v string) *DeviceUpdateOne {
	_u.mutation.SetInstallationID(v)
	return _u
}

// SetNillableInstallationID sets the "installation_id" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableInstallationID(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetInstallationID(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *DeviceUpdateOne) SetPlatform(v device.Platform) *DeviceUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillablePlatform(v *device.Platform) *DeviceUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetPushToken sets the "push_token" field.
func (_u *DeviceUpdateOne) SetPushToken(v string) *DeviceUpdateOne {
	_u.mutation.SetPushToken(v)
	return _u
}

// SetNillablePushToken sets the "push_token" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillablePushToken(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetPushToken(*v)
	}
	return _u
}

// ClearPushToken clears the value of the "push_token" field.
func (_u *DeviceUpdateOne) ClearPushToken() *DeviceUpdateOne {
	_u.mutation.ClearPushToken()
	return _u
}

// SetDeviceToken sets the "device_token" field.
func (_u *DeviceUpdateOne) SetDeviceToken(v string) *DeviceUpdateOne {
	_u.mutation.SetDeviceToken(v)
	return _u
}

// SetNillableDeviceToken sets the "device_token" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableDeviceToken(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetDeviceToken(*v)
	}
	return _u
}

// ClearDeviceToken clears the value of the "device_token" field.
func (_u *DeviceUpdateOne) ClearDeviceToken() *DeviceUpdateOne {
	_u.mutation.ClearDeviceToken()
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *DeviceUpdateOne) SetAppID(v string) *DeviceUpdateOne {
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableAppID(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// ClearAppID clears the value of the "app_id" field.
func (_u *DeviceUpdateOne) ClearAppID() *DeviceUpdateOne {
	_u.mutation.ClearAppID()
	return _u
}

// SetAppVersion sets the "app_version" field.
func (_u *DeviceUpdateOne) SetAppVersion(v string) *DeviceUpdateOne {
	_u.mutation.SetAppVersion(v)
	return _u
}

// SetNillableAppVersion sets the "app_version" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableAppVersion(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetAppVersion(*v)
	}
	return _u
}

// ClearAppVersion clears the value of the "app_version" field.
func (_u *DeviceUpdateOne) ClearAppVersion() *DeviceUpdateOne {
	_u.mutation.ClearAppVersion()
	return _u
}

// SetBuildNumber sets the "build_number" field.
func (_u *DeviceUpdateOne) SetBuildNumber(v string) *DeviceUpdateOne {
	_u.mutation.SetBuildNumber(v)
	return _u
}

// SetNillableBuildNumber sets the "build_number" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableBuildNumber(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetBuildNumber(*v)
	}
	return _u
}

// ClearBuildNumber clears the value of the "build_number" field.
func (_u *DeviceUpdateOne) ClearBuildNumber() *DeviceUpdateOne {
	_u.mutation.ClearBuildNumber()
	return _u
}

// SetOsVersion sets the "os_version" field.
func (_u *DeviceUpdateOne) SetOsVersion(v string) *DeviceUpdateOne {
	_u.mutation.SetOsVersion(v)
	return _u
}

// SetNillableOsVersion sets the "os_version" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableOsVersion(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetOsVersion(*v)
	}
	return _u
}

// ClearOsVersion clears the value of the "os_version" field.
func (_u *DeviceUpdateOne) ClearOsVersion() *DeviceUpdateOne {
	_u.mutation.ClearOsVersion()
	return _u
}

// SetDeviceModel sets the "device_model" field.
func (_u *DeviceUpdateOne) SetDeviceModel(v string) *DeviceUpdateOne {
	_u.mutation.SetDeviceModel(v)
	return _u
}

// SetNillableDeviceModel sets the "device_model" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableDeviceModel(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetDeviceModel(*v)
	}
	return _u
}

// ClearDeviceModel clears the value of the "device_model" field.
func (_u *DeviceUpdateOne) ClearDeviceModel() *DeviceUpdateOne {
	_u.mutation.ClearDeviceModel()
	return _u
}

// SetLocale sets the "locale" field.
func (_u *DeviceUpdateOne) SetLocale(v string) *DeviceUpdateOne {
	_u.mutation.SetLocale(v)
	return _u
}

// SetNillableLocale sets the "locale" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableLocale(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetLocale(*v)
	}
	return _u
}

// ClearLocale clears the value of the "locale" field.
func (_u *DeviceUpdateOne) ClearLocale() *DeviceUpdateOne {
	_u.mutation.ClearLocale()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeviceUpdateOne) SetUpdatedAt(v time.Time) *DeviceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddLoginIDs adds the "logins" edge to the DeviceLogin entity by IDs.
func (_u *DeviceUpdateOne) AddLoginIDs(ids ...int) *DeviceUpdateOne {
	_u.mutation.AddLoginIDs(ids...)
	return _u
}

// AddLogins adds the "logins" edges to the DeviceLogin entity.
func (_u *DeviceUpdateOne) AddLogins(v ...*DeviceLogin) *DeviceUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLoginIDs(ids...)
}

// Mutation returns the DeviceMutation object of the builder.
func (_u *DeviceUpdateOne) Mutation() *DeviceMutation {
	return _u.mutation
}

// ClearLogins clears all "logins" edges to the DeviceLogin entity.
func (_u *DeviceUpdateOne) ClearLogins() *DeviceUpdateOne {
	_u.mutation.ClearLogins()
	return _u
}

// RemoveLoginIDs removes the "logins" edge to DeviceLogin entities by IDs.
func (_u *DeviceUpdateOne) RemoveLoginIDs(ids ...int) *DeviceUpdateOne {
	_u.mutation.RemoveLoginIDs(ids...)
	return _u
}

// RemoveLogins removes "logins" edges to DeviceLogin entities.
func (_u *DeviceUpdateOne) RemoveLogins(v ...*DeviceLogin) *DeviceUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLoginIDs(ids...)
}

// Where appends a list predicates to the DeviceUpdate builder.
func (_u *DeviceUpdateOne) Where(ps ...predicate.Device) *DeviceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeviceUpdateOne) Select(field string, fields ...string) *DeviceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Device entity.
func (_u *DeviceUpdateOne) Save(ctx context.Context) (*Device, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceUpdateOne) SaveX(ctx context.Context) *Device {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeviceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeviceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := device.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceUpdateOne) check() error {
	if v, ok := _u.mutation.InstallationID(); ok {
		if err := device.InstallationIDValidator(v); err != nil {
			return &ValidationError{Name: "installation_id", err: fmt.Errorf(`ent: validator failed for field "Device.installation_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := device.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Device.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PushToken(); ok {
		if err := device.PushTokenValidator(v); err != nil {
			return &ValidationError{Name: "push_token", err: fmt.Errorf(`ent: validator failed for field "Device.push_token": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceToken(); ok {
		if err := device.DeviceTokenValidator(v); err != nil {
			return &ValidationError{Name: "device_token", err: fmt.Errorf(`ent: validator failed for field "Device.device_token": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AppID(); ok {
		if err := device.AppIDValidator(v); err != nil {
			return &ValidationError{Name: "app_id", err: fmt.Errorf(`ent: validator failed for field "Device.app_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AppVersion(); ok {
		if err := device.AppVersionValidator(v); err != nil {
			return &ValidationError{Name: "app_version", err: fmt.Errorf(`ent: validator failed for field "Device.app_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BuildNumber(); ok {
		if err := device.BuildNumberValidator(v); err != nil {
			return &ValidationError{Name: "build_number", err: fmt.Errorf(`ent: validator failed for field "Device.build_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OsVersion(); ok {
		if err := device.OsVersionValidator(v); err != nil {
			return &ValidationError{Name: "os_version", err: fmt.Errorf(`ent: validator failed for field "Device.os_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceModel(); ok {
		if err := device.DeviceModelValidator(v); err != nil {
			return &ValidationError{Name: "device_model", err: fmt.Errorf(`ent: validator failed for field "Device.device_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Locale(); ok {
		if err := device.LocaleValidator(v); err != nil {
			return &ValidationError{Name: "locale", err: fmt.Errorf(`ent: validator failed for field "Device.locale": %w`, err)}
		}
	}
	return nil
}

func (_u *DeviceUpdateOne) sqlSave(ctx context.Context) (_node *Device, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(device.Table, device.Columns, sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Device.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, device.FieldID)
		for _, f := range fields {
			if !device.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != device.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.InstallationID(); ok {
		_spec.SetField(device.FieldInstallationID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(device.FieldPlatform, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PushToken(); ok {
		_spec.SetField(device.FieldPushToken, field.TypeString, value)
	}
	if _u.mutation.PushTokenCleared() {
		_spec.ClearField(device.FieldPushToken, field.TypeString)
	}
	if value, ok := _u.mutation.DeviceToken(); ok {
		_spec.SetField(device.FieldDeviceToken, field.TypeString, value)
	}
	if _u.mutation.DeviceTokenCleared() {
		_spec.ClearField(device.FieldDeviceToken, field.TypeString)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(device.FieldAppID, field.TypeString, value)
	}
	if _u.mutation.AppIDCleared() {
		_spec.ClearField(device.FieldAppID, field.TypeString)
	}
	if value, ok := _u.mutation.AppVersion(); ok {
		_spec.SetField(device.FieldAppVersion, field.TypeString, value)
	}
	if _u.mutation.AppVersionCleared() {
		_spec.ClearField(device.FieldAppVersion, field.TypeString)
	}
	if value, ok := _u.mutation.BuildNumber(); ok {
		_spec.SetField(device.FieldBuildNumber, field.TypeString, value)
	}
	if _u.mutation.BuildNumberCleared() {
		_spec.ClearField(device.FieldBuildNumber, field.TypeString)
	}
	if value, ok := _u.mutation.OsVersion(); ok {
		_spec.SetField(device.FieldOsVersion, field.TypeString, value)
	}
	if _u.mutation.OsVersionCleared() {
		_spec.ClearField(device.FieldOsVersion, field.TypeString)
	}
	if value, ok := _u.mutation.DeviceModel(); ok {
		_spec.SetField(device.FieldDeviceModel, field.TypeString, value)
	}
	if _u.mutation.DeviceModelCleared() {
		_spec.ClearField(device.FieldDeviceModel, field.TypeString)
	}
	if value, ok := _u.mutation.Locale(); ok {
		_spec.SetField(device.FieldLocale, field.TypeString, value)
	}
	if _u.mutation.LocaleCleared() {
		_spec.ClearField(device.FieldLocale, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.LoginsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   device.LoginsTable,
			Columns: []string{device.LoginsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(devicelogin.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLoginsIDs(); len(nodes) > 0 && !_u.mutation.LoginsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   device.LoginsTable,
			Columns: []string{device.LoginsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(devicelogin.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LoginsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   device.LoginsTable,
			Columns: []string{device.LoginsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(devicelogin.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Device{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
