// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/nonchan7720/webapp-notification/backend/internal/ent/device"
	"github.com/nonchan7720/webapp-notification/backend/internal/ent/devicelogin"
	"github.com/nonchan7720/webapp-notification/backend/internal/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeDevice      = "Device"
	TypeDeviceLogin = "DeviceLogin"
)

// DeviceMutation represents an operation that mutates the Device nodes in the graph.
type DeviceMutation struct {
	config
	op              Op
	typ             string
	id              *int
	installation_id *string
	platform        *device.Platform
	push_token      *string
	device_token    *string
	app_id          *string
	app_version     *string
	build_number    *string
	os_version      *string
	device_model    *string
	locale          *string
	created_at      *time.Time
	updated_at      *time.Time
	clearedFields   map[string]struct{}
	logins          map[int]struct{}
	removedlogins   map[int]struct{}
	clearedlogins   bool
	done            bool
	oldValue        func(context.Context) (*Device, error)
	predicates      []predicate.Device
}

var _ ent.Mutation = (*DeviceMutation)(nil)

// deviceOption allows management of the mutation configuration using functional options.
type deviceOption func(*DeviceMutation)

// newDeviceMutation creates new mutation for the Device entity.
func newDeviceMutation(c config, op Op, opts ...deviceOption) *DeviceMutation {
	m := &DeviceMutation{
		config:        c,
		op:            op,
		typ:           TypeDevice,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withDeviceID sets the ID field of the mutation.
func withDeviceID(id int) deviceOption {
	return func(m *DeviceMutation) {
		var (
			err   error
			once  sync.Once
			value *Device
		)
		m.oldValue = func(ctx context.Context) (*Device, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Device.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withDevice sets the old Device of the mutation.
func withDevice(node *Device) deviceOption {
	return func(m *DeviceMutation) {
		m.oldValue = func(context.Context) (*Device, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m DeviceMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m DeviceMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *DeviceMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *DeviceMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Device.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetInstallationID sets the "installation_id" field.
func (m *DeviceMutation) SetInstallationID(s string) {
	m.installation_id = &s
}

// InstallationID returns the value of the "installation_id" field in the mutation.
func (m *DeviceMutation) InstallationID() (r string, exists bool) {
	v := m.installation_id
	if v == nil {
		return
	}
	return *v, true
}

// OldInstallationID returns the old "installation_id" field's value of the Device entity.
// If the Device object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeviceMutation) OldInstallationID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldInstallationID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldInstallationID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldInstallationID: %w", err)
	}
	return oldValue.InstallationID, nil
}

// ResetInstallationID resets all changes to the "installation_id" field.
func (m *DeviceMutation) ResetInstallationID() {
	m.installation_id = nil
}

// SetPlatform sets the "platform" field.
func (m *DeviceMutation) SetPlatform(d device.Platform) {
	m.platform = &d
}

// Platform returns the value of the "platform" field in the mutation.
func (m *DeviceMutation) Platform() (r device.Platform, exists bool) {
	v := m.platform
	if v == nil {
		return
	}
	return *v, true
}

// OldPlatform returns the old "platform" field's value of the Device entity.
// If the Device object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeviceMutation) OldPlatform(ctx context.Context) (v device.Platform, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPlatform is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPlatform requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPlatform: %w", err)
	}
	return oldValue.Platform, nil
}

// ResetPlatform resets all changes to the "platform" field.
func (m *DeviceMutation) ResetPlatform() {
	m.platform = nil
}

// SetPushToken sets the "push_token" field.
func (m *DeviceMutation) SetPushToken(s string) {
	m.push_token = &s
}

// PushToken returns the value of the "push_token" field in the mutation.
func (m *DeviceMutation) PushToken() (r string, exists bool) {
	v := m.push_token
	if v == nil {
		return
	}
	return *v, true
}

// OldPushToken returns the old "push_token" field's value of the Device entity.
// If the Device object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeviceMutation) OldPushToken(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPushToken is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPushToken requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPushToken: %w", err)
	}
	return oldValue.PushToken, nil
}

// ClearPushToken clears the value of the "push_token" field.
func (m *DeviceMutation) ClearPushToken() {
	m.push_token = nil
	m.clearedFields[device.FieldPushToken] = struct{}{}
}

// PushTokenCleared returns if the "push_token" field was cleared in this mutation.
func (m *DeviceMutation) PushTokenCleared() bool {
	_, ok := m.clearedFields[device.FieldPushToken]
	return ok
}

// ResetPushToken resets all changes to the "push_token" field.
func (m *DeviceMutation) ResetPushToken() {
	m.push_token = nil
	delete(m.clearedFields, device.FieldPushToken)
}

// SetDeviceToken sets the "device_token" field.
func (m *DeviceMutation) SetDeviceToken(s string) {
	m.device_token = &s
}

// DeviceToken returns the value of the "device_token" field in the mutation.
func (m *DeviceMutation) DeviceToken() (r string, exists bool) {
	v := m.device_token
	if v == nil {
		return
	}
	return *v, true
}

// OldDeviceToken returns the old "device_token" field's value of the Device entity.
// If the Device object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeviceMutation) OldDeviceToken(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDeviceToken is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDeviceToken requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDeviceToken: %w", err)
	}
	return oldValue.DeviceToken, nil
}

// ClearDeviceToken clears the value of the "device_token" field.
func (m *DeviceMutation) ClearDeviceToken() {
	m.device_token = nil
	m.clearedFields[device.FieldDeviceToken] = struct{}{}
}

// DeviceTokenCleared returns if the "device_token" field was cleared in this mutation.
func (m *DeviceMutation) DeviceTokenCleared() bool {
	_, ok := m.clearedFields[device.FieldDeviceToken]
	return ok
}

// ResetDeviceToken resets all changes to the "device_token" field.
func (m *DeviceMutation) ResetDeviceToken() {
	m.device_token = nil
	delete(m.clearedFields, device.FieldDeviceToken)
}

// SetAppID sets the "app_id" field.
func (m *DeviceMutation) SetAppID(s string) {
	m.app_id = &s
}

// AppID returns the value of the "app_id" field in the mutation.
func (m *DeviceMutation) AppID() (r string, exists bool) {
	v := m.app_id
	if v == nil {
		return
	}
	return *v, true
}

// OldAppID returns the old "app_id" field's value of the Device entity.
// If the Device object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeviceMutation) OldAppID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAppID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAppID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAppID: %w", err)
	}
	return oldValue.AppID, nil
}

// ClearAppID clears the value of the "app_id" field.
func (m *DeviceMutation) ClearAppID() {
	m.app_id = nil
	m.clearedFields[device.FieldAppID] = struct{}{}
}

// AppIDCleared returns if the "app_id" field was cleared in this mutation.
func (m *DeviceMutation) AppIDCleared() bool {
	_, ok := m.clearedFields[device.FieldAppID]
	return ok
}

// ResetAppID resets all changes to the "app_id" field.
func (m *DeviceMutation) ResetAppID() {
	m.app_id = nil
	delete(m.clearedFields, device.FieldAppID)
}

// SetAppVersion sets the "app_version" field.
func (m *DeviceMutation) SetAppVersion(s string) {
	m.app_version = &s
}

// AppVersion returns the value of the "app_version" field in the mutation.
func (m *DeviceMutation) AppVersion() (r string, exists bool) {
	v := m.app_version
	if v == nil {
		return
	}
	return *v, true
}

// OldAppVersion returns the old "app_version" field's value of the Device entity.
// If the Device object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeviceMutation) OldAppVersion(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAppVersion is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAppVersion requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAppVersion: %w", err)
	}
	return oldValue.AppVersion, nil
}

// ClearAppVersion clears the value of the "app_version" field.
func (m *DeviceMutation) ClearAppVersion() {
	m.app_version = nil
	m.clearedFields[device.FieldAppVersion] = struct{}{}
}

// AppVersionCleared returns if the "app_version" field was cleared in this mutation.
func (m *DeviceMutation) AppVersionCleared() bool {
	_, ok := m.clearedFields[device.FieldAppVersion]
	return ok
}

// ResetAppVersion resets all changes to the "app_version" field.
func (m *DeviceMutation) ResetAppVersion() {
	m.app_version = nil
	delete(m.clearedFields, device.FieldAppVersion)
}

// SetBuildNumber sets the "build_number" field.
func (m *DeviceMutation) SetBuildNumber(s string) {
	m.build_number = &s
}

// BuildNumber returns the value of the "build_number" field in the mutation.
func (m *DeviceMutation) BuildNumber() (r string, exists bool) {
	v := m.build_number
	if v == nil {
		return
	}
	return *v, true
}

// OldBuildNumber returns the old "build_number" field's value of the Device entity.
// If the Device object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeviceMutation) OldBuildNumber(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBuildNumber is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBuildNumber requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBuildNumber: %w", err)
	}
	return oldValue.BuildNumber, nil
}

// ClearBuildNumber clears the value of the "build_number" field.
func (m *DeviceMutation) ClearBuildNumber() {
	m.build_number = nil
	m.clearedFields[device.FieldBuildNumber] = struct{}{}
}

// BuildNumberCleared returns if the "build_number" field was cleared in this mutation.
func (m *DeviceMutation) BuildNumberCleared() bool {
	_, ok := m.clearedFields[device.FieldBuildNumber]
	return ok
}

// ResetBuildNumber resets all changes to the "build_number" field.
func (m *DeviceMutation) ResetBuildNumber() {
	m.build_number = nil
	delete(m.clearedFields, device.FieldBuildNumber)
}

// SetOsVersion sets the "os_version" field.
func (m *DeviceMutation) SetOsVersion(s string) {
	m.os_version = &s
}

// OsVersion returns the value of the "os_version" field in the mutation.
func (m *DeviceMutation) OsVersion() (r string, exists bool) {
	v := m.os_version
	if v == nil {
		return
	}
	return *v, true
}

// OldOsVersion returns the old "os_version" field's value of the Device entity.
// If the Device object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeviceMutation) OldOsVersion(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOsVersion is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOsVersion requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOsVersion: %w", err)
	}
	return oldValue.OsVersion, nil
}

// ClearOsVersion clears the value of the "os_version" field.
func (m *DeviceMutation) ClearOsVersion() {
	m.os_version = nil
	m.clearedFields[device.FieldOsVersion] = struct{}{}
}

// OsVersionCleared returns if the "os_version" field was cleared in this mutation.
func (m *DeviceMutation) OsVersionCleared() bool {
	_, ok := m.clearedFields[device.FieldOsVersion]
	return ok
}

// ResetOsVersion resets all changes to the "os_version" field.
func (m *DeviceMutation) ResetOsVersion() {
	m.os_version = nil
	delete(m.clearedFields, device.FieldOsVersion)
}

// SetDeviceModel sets the "device_model" field.
func (m *DeviceMutation) SetDeviceModel(s string) {
	m.device_model = &s
}

// DeviceModel returns the value of the "device_model" field in the mutation.
func (m *DeviceMutation) DeviceModel() (r string, exists bool) {
	v := m.device_model
	if v == nil {
		return
	}
	return *v, true
}

// OldDeviceModel returns the old "device_model" field's value of the Device entity.
// If the Device object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeviceMutation) OldDeviceModel(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDeviceModel is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDeviceModel requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDeviceModel: %w", err)
	}
	return oldValue.DeviceModel, nil
}

// ClearDeviceModel clears the value of the "device_model" field.
func (m *DeviceMutation) ClearDeviceModel() {
	m.device_model = nil
	m.clearedFields[device.FieldDeviceModel] = struct{}{}
}

// DeviceModelCleared returns if the "device_model" field was cleared in this mutation.
func (m *DeviceMutation) DeviceModelCleared() bool {
	_, ok := m.clearedFields[device.FieldDeviceModel]
	return ok
}

// ResetDeviceModel resets all changes to the "device_model" field.
func (m *DeviceMutation) ResetDeviceModel() {
	m.device_model = nil
	delete(m.clearedFields, device.FieldDeviceModel)
}

// SetLocale sets the "locale" field.
func (m *DeviceMutation) SetLocale(s string) {
	m.locale = &s
}

// Locale returns the value of the "locale" field in the mutation.
func (m *DeviceMutation) Locale() (r string, exists bool) {
	v := m.locale
	if v == nil {
		return
	}
	return *v, true
}

// OldLocale returns the old "locale" field's value of the Device entity.
// If the Device object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeviceMutation) OldLocale(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLocale is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLocale requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLocale: %w", err)
	}
	return oldValue.Locale, nil
}

// ClearLocale clears the value of the "locale" field.
func (m *DeviceMutation) ClearLocale() {
	m.locale = nil
	m.clearedFields[device.FieldLocale] = struct{}{}
}

// LocaleCleared returns if the "locale" field was cleared in this mutation.
func (m *DeviceMutation) LocaleCleared() bool {
	_, ok := m.clearedFields[device.FieldLocale]
	return ok
}

// ResetLocale resets all changes to the "locale" field.
func (m *DeviceMutation) ResetLocale() {
	m.locale = nil
	delete(m.clearedFields, device.FieldLocale)
}

// SetCreatedAt sets the "created_at" field.
func (m *DeviceMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *DeviceMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Device entity.
// If the Device object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeviceMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *DeviceMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *DeviceMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *DeviceMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Device entity.
// If the Device object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeviceMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *DeviceMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// AddLoginIDs adds the "logins" edge to the DeviceLogin entity by ids.
func (m *DeviceMutation) AddLoginIDs(ids ...int) {
	if m.logins == nil {
		m.logins = make(map[int]struct{})
	}
	for i := range ids {
		m.logins[ids[i]] = struct{}{}
	}
}

// ClearLogins clears the "logins" edge to the DeviceLogin entity.
func (m *DeviceMutation) ClearLogins() {
	m.clearedlogins = true
}

// LoginsCleared reports if the "logins" edge to the DeviceLogin entity was cleared.
func (m *DeviceMutation) LoginsCleared() bool {
	return m.clearedlogins
}

// RemoveLoginIDs removes the "logins" edge to the DeviceLogin entity by IDs.
func (m *DeviceMutation) RemoveLoginIDs(ids ...int) {
	if m.removedlogins == nil {
		m.removedlogins = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.logins, ids[i])
		m.removedlogins[ids[i]] = struct{}{}
	}
}

// RemovedLogins returns the removed IDs of the "logins" edge to the DeviceLogin entity.
func (m *DeviceMutation) RemovedLoginsIDs() (ids []int) {
	for id := range m.removedlogins {
		ids = append(ids, id)
	}
	return
}

// LoginsIDs returns the "logins" edge IDs in the mutation.
func (m *DeviceMutation) LoginsIDs() (ids []int) {
	for id := range m.logins {
		ids = append(ids, id)
	}
	return
}

// ResetLogins resets all changes to the "logins" edge.
func (m *DeviceMutation) ResetLogins() {
	m.logins = nil
	m.clearedlogins = false
	m.removedlogins = nil
}

// Where appends a list predicates to the DeviceMutation builder.
func (m *DeviceMutation) Where(ps ...predicate.Device) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the DeviceMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *DeviceMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Device, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *DeviceMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *DeviceMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Device).
func (m *DeviceMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *DeviceMutation) Fields() []string {
	fields := make([]string, 0, 12)
	if m.installation_id != nil {
		fields = append(fields, device.FieldInstallationID)
	}
	if m.platform != nil {
		fields = append(fields, device.FieldPlatform)
	}
	if m.push_token != nil {
		fields = append(fields, device.FieldPushToken)
	}
	if m.device_token != nil {
		fields = append(fields, device.FieldDeviceToken)
	}
	if m.app_id != nil {
		fields = append(fields, device.FieldAppID)
	}
	if m.app_version != nil {
		fields = append(fields, device.FieldAppVersion)
	}
	if m.build_number != nil {
		fields = append(fields, device.FieldBuildNumber)
	}
	if m.os_version != nil {
		fields = append(fields, device.FieldOsVersion)
	}
	if m.device_model != nil {
		fields = append(fields, device.FieldDeviceModel)
	}
	if m.locale != nil {
		fields = append(fields, device.FieldLocale)
	}
	if m.created_at != nil {
		fields = append(fields, device.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, device.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *DeviceMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case device.FieldInstallationID:
		return m.InstallationID()
	case device.FieldPlatform:
		return m.Platform()
	case device.FieldPushToken:
		return m.PushToken()
	case device.FieldDeviceToken:
		return m.DeviceToken()
	case device.FieldAppID:
		return m.AppID()
	case device.FieldAppVersion:
		return m.AppVersion()
	case device.FieldBuildNumber:
		return m.BuildNumber()
	case device.FieldOsVersion:
		return m.OsVersion()
	case device.FieldDeviceModel:
		return m.DeviceModel()
	case device.FieldLocale:
		return m.Locale()
	case device.FieldCreatedAt:
		return m.CreatedAt()
	case device.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *DeviceMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case device.FieldInstallationID:
		return m.OldInstallationID(ctx)
	case device.FieldPlatform:
		return m.OldPlatform(ctx)
	case device.FieldPushToken:
		return m.OldPushToken(ctx)
	case device.FieldDeviceToken:
		return m.OldDeviceToken(ctx)
	case device.FieldAppID:
		return m.OldAppID(ctx)
	case device.FieldAppVersion:
		return m.OldAppVersion(ctx)
	case device.FieldBuildNumber:
		return m.OldBuildNumber(ctx)
	case device.FieldOsVersion:
		return m.OldOsVersion(ctx)
	case device.FieldDeviceModel:
		return m.OldDeviceModel(ctx)
	case device.FieldLocale:
		return m.OldLocale(ctx)
	case device.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case device.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Device field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DeviceMutation) SetField(name string, value ent.Value) error {
	switch name {
	case device.FieldInstallationID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetInstallationID(v)
		return nil
	case device.FieldPlatform:
		v, ok := value.(device.Platform)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPlatform(v)
		return nil
	case device.FieldPushToken:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPushToken(v)
		return nil
	case device.FieldDeviceToken:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDeviceToken(v)
		return nil
	case device.FieldAppID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAppID(v)
		return nil
	case device.FieldAppVersion:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAppVersion(v)
		return nil
	case device.FieldBuildNumber:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBuildNumber(v)
		return nil
	case device.FieldOsVersion:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOsVersion(v)
		return nil
	case device.FieldDeviceModel:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDeviceModel(v)
		return nil
	case device.FieldLocale:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLocale(v)
		return nil
	case device.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case device.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Device field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *DeviceMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *DeviceMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DeviceMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Device numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *DeviceMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(device.FieldPushToken) {
		fields = append(fields, device.FieldPushToken)
	}
	if m.FieldCleared(device.FieldDeviceToken) {
		fields = append(fields, device.FieldDeviceToken)
	}
	if m.FieldCleared(device.FieldAppID) {
		fields = append(fields, device.FieldAppID)
	}
	if m.FieldCleared(device.FieldAppVersion) {
		fields = append(fields, device.FieldAppVersion)
	}
	if m.FieldCleared(device.FieldBuildNumber) {
		fields = append(fields, device.FieldBuildNumber)
	}
	if m.FieldCleared(device.FieldOsVersion) {
		fields = append(fields, device.FieldOsVersion)
	}
	if m.FieldCleared(device.FieldDeviceModel) {
		fields = append(fields, device.FieldDeviceModel)
	}
	if m.FieldCleared(device.FieldLocale) {
		fields = append(fields, device.FieldLocale)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *DeviceMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *DeviceMutation) ClearField(name string) error {
	switch name {
	case device.FieldPushToken:
		m.ClearPushToken()
		return nil
	case device.FieldDeviceToken:
		m.ClearDeviceToken()
		return nil
	case device.FieldAppID:
		m.ClearAppID()
		return nil
	case device.FieldAppVersion:
		m.ClearAppVersion()
		return nil
	case device.FieldBuildNumber:
		m.ClearBuildNumber()
		return nil
	case device.FieldOsVersion:
		m.ClearOsVersion()
		return nil
	case device.FieldDeviceModel:
		m.ClearDeviceModel()
		return nil
	case device.FieldLocale:
		m.ClearLocale()
		return nil
	}
	return fmt.Errorf("unknown Device nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *DeviceMutation) ResetField(name string) error {
	switch name {
	case device.FieldInstallationID:
		m.ResetInstallationID()
		return nil
	case device.FieldPlatform:
		m.ResetPlatform()
		return nil
	case device.FieldPushToken:
		m.ResetPushToken()
		return nil
	case device.FieldDeviceToken:
		m.ResetDeviceToken()
		return nil
	case device.FieldAppID:
		m.ResetAppID()
		return nil
	case device.FieldAppVersion:
		m.ResetAppVersion()
		return nil
	case device.FieldBuildNumber:
		m.ResetBuildNumber()
		return nil
	case device.FieldOsVersion:
		m.ResetOsVersion()
		return nil
	case device.FieldDeviceModel:
		m.ResetDeviceModel()
		return nil
	case device.FieldLocale:
		m.ResetLocale()
		return nil
	case device.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case device.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Device field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *DeviceMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.logins != nil {
		edges = append(edges, device.EdgeLogins)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *DeviceMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case device.EdgeLogins:
		ids := make([]ent.Value, 0, len(m.logins))
		for id := range m.logins {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *DeviceMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedlogins != nil {
		edges = append(edges, device.EdgeLogins)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *DeviceMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case device.EdgeLogins:
		ids := make([]ent.Value, 0, len(m.removedlogins))
		for id := range m.removedlogins {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *DeviceMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedlogins {
		edges = append(edges, device.EdgeLogins)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *DeviceMutation) EdgeCleared(name string) bool {
	switch name {
	case device.EdgeLogins:
		return m.clearedlogins
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *DeviceMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Device unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *DeviceMutation) ResetEdge(name string) error {
	switch name {
	case device.EdgeLogins:
		m.ResetLogins()
		return nil
	}
	return fmt.Errorf("unknown Device edge %s", name)
}

// DeviceLoginMutation represents an operation that mutates the DeviceLogin nodes in the graph.
type DeviceLoginMutation struct {
	config
	op            Op
	typ           string
	id            *int
	login_id      *string
	created_at    *time.Time
	clearedFields map[string]struct{}
	device        *int
	cleareddevice bool
	done          bool
	oldValue      func(context.Context) (*DeviceLogin, error)
	predicates    []predicate.DeviceLogin
}

var _ ent.Mutation = (*DeviceLoginMutation)(nil)

// deviceloginOption allows management of the mutation configuration using functional options.
type deviceloginOption func(*DeviceLoginMutation)

// newDeviceLoginMutation creates new mutation for the DeviceLogin entity.
func newDeviceLoginMutation(c config, op Op, opts ...deviceloginOption) *DeviceLoginMutation {
	m := &DeviceLoginMutation{
		config:        c,
		op:            op,
		typ:           TypeDeviceLogin,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withDeviceLoginID sets the ID field of the mutation.
func withDeviceLoginID(id int) deviceloginOption {
	return func(m *DeviceLoginMutation) {
		var (
			err   error
			once  sync.Once
			value *DeviceLogin
		)
		m.oldValue = func(ctx context.Context) (*DeviceLogin, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().DeviceLogin.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withDeviceLogin sets the old DeviceLogin of the mutation.
func withDeviceLogin(node *DeviceLogin) deviceloginOption {
	return func(m *DeviceLoginMutation) {
		m.oldValue = func(context.Context) (*DeviceLogin, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m DeviceLoginMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m DeviceLoginMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *DeviceLoginMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *DeviceLoginMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().DeviceLogin.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetLoginID sets the "login_id" field.
func (m *DeviceLoginMutation) SetLoginID(s string) {
	m.login_id = &s
}

// LoginID returns the value of the "login_id" field in the mutation.
func (m *DeviceLoginMutation) LoginID() (r string, exists bool) {
	v := m.login_id
	if v == nil {
		return
	}
	return *v, true
}

// OldLoginID returns the old "login_id" field's value of the DeviceLogin entity.
// If the DeviceLogin object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeviceLoginMutation) OldLoginID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLoginID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLoginID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLoginID: %w", err)
	}
	return oldValue.LoginID, nil
}

// ResetLoginID resets all changes to the "login_id" field.
func (m *DeviceLoginMutation) ResetLoginID() {
	m.login_id = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *DeviceLoginMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *DeviceLoginMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the DeviceLogin entity.
// If the DeviceLogin object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeviceLoginMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *DeviceLoginMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetDeviceID sets the "device" edge to the Device entity by id.
func (m *DeviceLoginMutation) SetDeviceID(id int) {
	m.device = &id
}

// ClearDevice clears the "device" edge to the Device entity.
func (m *DeviceLoginMutation) ClearDevice() {
	m.cleareddevice = true
}

// DeviceCleared reports if the "device" edge to the Device entity was cleared.
func (m *DeviceLoginMutation) DeviceCleared() bool {
	return m.cleareddevice
}

// DeviceID returns the "device" edge ID in the mutation.
func (m *DeviceLoginMutation) DeviceID() (id int, exists bool) {
	if m.device != nil {
		return *m.device, true
	}
	return
}

// DeviceIDs returns the "device" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// DeviceID instead. It exists only for internal usage by the builders.
func (m *DeviceLoginMutation) DeviceIDs() (ids []int) {
	if id := m.device; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetDevice resets all changes to the "device" edge.
func (m *DeviceLoginMutation) ResetDevice() {
	m.device = nil
	m.cleareddevice = false
}

// Where appends a list predicates to the DeviceLoginMutation builder.
func (m *DeviceLoginMutation) Where(ps ...predicate.DeviceLogin) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the DeviceLoginMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *DeviceLoginMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.DeviceLogin, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *DeviceLoginMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *DeviceLoginMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (DeviceLogin).
func (m *DeviceLoginMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *DeviceLoginMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.login_id != nil {
		fields = append(fields, devicelogin.FieldLoginID)
	}
	if m.created_at != nil {
		fields = append(fields, devicelogin.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *DeviceLoginMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case devicelogin.FieldLoginID:
		return m.LoginID()
	case devicelogin.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *DeviceLoginMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case devicelogin.FieldLoginID:
		return m.OldLoginID(ctx)
	case devicelogin.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown DeviceLogin field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DeviceLoginMutation) SetField(name string, value ent.Value) error {
	switch name {
	case devicelogin.FieldLoginID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLoginID(v)
		return nil
	case devicelogin.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown DeviceLogin field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *DeviceLoginMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *DeviceLoginMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DeviceLoginMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown DeviceLogin numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *DeviceLoginMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *DeviceLoginMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *DeviceLoginMutation) ClearField(name string) error {
	return fmt.Errorf("unknown DeviceLogin nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *DeviceLoginMutation) ResetField(name string) error {
	switch name {
	case devicelogin.FieldLoginID:
		m.ResetLoginID()
		return nil
	case devicelogin.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown DeviceLogin field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *DeviceLoginMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.device != nil {
		edges = append(edges, devicelogin.EdgeDevice)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *DeviceLoginMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case devicelogin.EdgeDevice:
		if id := m.device; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *DeviceLoginMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *DeviceLoginMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *DeviceLoginMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.cleareddevice {
		edges = append(edges, devicelogin.EdgeDevice)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *DeviceLoginMutation) EdgeCleared(name string) bool {
	switch name {
	case devicelogin.EdgeDevice:
		return m.cleareddevice
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *DeviceLoginMutation) ClearEdge(name string) error {
	switch name {
	case devicelogin.EdgeDevice:
		m.ClearDevice()
		return nil
	}
	return fmt.Errorf("unknown DeviceLogin unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *DeviceLoginMutation) ResetEdge(name string) error {
	switch name {
	case devicelogin.EdgeDevice:
		m.ResetDevice()
		return nil
	}
	return fmt.Errorf("unknown DeviceLogin edge %s", name)
}
