// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/nonchan7720/webapp-notification/backend/internal/ent/device"
	"github.com/nonchan7720/webapp-notification/backend/internal/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	deviceFields := schema.Device{}.Fields()
	_ = deviceFields
	// deviceDescInstallationID is the schema descriptor for installation_id field.
	deviceDescInstallationID := deviceFields[0].Descriptor()
	// device.InstallationIDValidator is a validator for the "installation_id" field. It is called by the builders before save.
	device.InstallationIDValidator = func() func(string) error {
		validators := deviceDescInstallationID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(installation_id string) error {
			for _, fn := range fns {
				if err := fn(installation_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// deviceDescLoginID is the schema descriptor for login_id field.
	deviceDescLoginID := deviceFields[1].Descriptor()
	// device.LoginIDValidator is a validator for the "login_id" field. It is called by the builders before save.
	device.LoginIDValidator = func() func(string) error {
		validators := deviceDescLoginID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(login_id string) error {
			for _, fn := range fns {
				if err := fn(login_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// deviceDescPushToken is the schema descriptor for push_token field.
	deviceDescPushToken := deviceFields[3].Descriptor()
	// device.PushTokenValidator is a validator for the "push_token" field. It is called by the builders before save.
	device.PushTokenValidator = func() func(string) error {
		validators := deviceDescPushToken.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(push_token string) error {
			for _, fn := range fns {
				if err := fn(push_token); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// deviceDescDeviceToken is the schema descriptor for device_token field.
	deviceDescDeviceToken := deviceFields[4].Descriptor()
	// device.DeviceTokenValidator is a validator for the "device_token" field. It is called by the builders before save.
	device.DeviceTokenValidator = deviceDescDeviceToken.Validators[0].(func(string) error)
	// deviceDescAppID is the schema descriptor for app_id field.
	deviceDescAppID := deviceFields[5].Descriptor()
	// device.AppIDValidator is a validator for the "app_id" field. It is called by the builders before save.
	device.AppIDValidator = deviceDescAppID.Validators[0].(func(string) error)
	// deviceDescAppVersion is the schema descriptor for app_version field.
	deviceDescAppVersion := deviceFields[6].Descriptor()
	// device.AppVersionValidator is a validator for the "app_version" field. It is called by the builders before save.
	device.AppVersionValidator = deviceDescAppVersion.Validators[0].(func(string) error)
	// deviceDescBuildNumber is the schema descriptor for build_number field.
	deviceDescBuildNumber := deviceFields[7].Descriptor()
	// device.BuildNumberValidator is a validator for the "build_number" field. It is called by the builders before save.
	device.BuildNumberValidator = deviceDescBuildNumber.Validators[0].(func(string) error)
	// deviceDescOsVersion is the schema descriptor for os_version field.
	deviceDescOsVersion := deviceFields[8].Descriptor()
	// device.OsVersionValidator is a validator for the "os_version" field. It is called by the builders before save.
	device.OsVersionValidator = deviceDescOsVersion.Validators[0].(func(string) error)
	// deviceDescDeviceModel is the schema descriptor for device_model field.
	deviceDescDeviceModel := deviceFields[9].Descriptor()
	// device.DeviceModelValidator is a validator for the "device_model" field. It is called by the builders before save.
	device.DeviceModelValidator = deviceDescDeviceModel.Validators[0].(func(string) error)
	// deviceDescLocale is the schema descriptor for locale field.
	deviceDescLocale := deviceFields[10].Descriptor()
	// device.LocaleValidator is a validator for the "locale" field. It is called by the builders before save.
	device.LocaleValidator = deviceDescLocale.Validators[0].(func(string) error)
	// deviceDescCreatedAt is the schema descriptor for created_at field.
	deviceDescCreatedAt := deviceFields[11].Descriptor()
	// device.DefaultCreatedAt holds the default value on creation for the created_at field.
	device.DefaultCreatedAt = deviceDescCreatedAt.Default.(func() time.Time)
	// deviceDescUpdatedAt is the schema descriptor for updated_at field.
	deviceDescUpdatedAt := deviceFields[12].Descriptor()
	// device.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	device.DefaultUpdatedAt = deviceDescUpdatedAt.Default.(func() time.Time)
	// device.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	device.UpdateDefaultUpdatedAt = deviceDescUpdatedAt.UpdateDefault.(func() time.Time)
}
