#!/usr/bin/env bash
# End-to-end smoke test of the *built* worker (build/worker.mjs + app.wasm)
# on the real Workers runtime (workerd, via `wrangler dev`) with a local D1:
# applies the D1 migrations, starts `wrangler dev`, drives the API with curl
# and asserts on status codes / response bodies. Exits non-zero on the first
# mismatch and prints wrangler's log.
#
# Run via `mise run worker:smoke` (after worker:install and worker:build), or
# from CI (.github/workflows/ci.yml, "worker" job). Uses PUSH_PROVIDER=log so
# it needs no network access beyond localhost; set SMOKE_EXPO=1 to also send
# one notification through PUSH_PROVIDER=expo with a dummy token (requires
# outbound access to exp.host; asserts Expo's DeviceNotRegistered reply,
# which proves the fetch-based HTTP client in internal/push works on workerd).
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

PORT="${SMOKE_PORT:-8787}"
API_KEY="smoke-key"
BASE="http://localhost:${PORT}"
export WRANGLER_SEND_METRICS=false

[ -f build/worker.mjs ] && [ -f build/app.wasm ] || { echo "smoke: build/ is missing; run ./build.sh (mise run worker:build) first" >&2; exit 2; }

provider=log
[ "${SMOKE_EXPO:-}" = "1" ] && provider=expo

# Run from a throwaway wrangler config + state directory (under .wrangler/,
# gitignored) instead of ./wrangler.toml: `wrangler dev --var` does not
# override [vars] from the config file, and a developer's .dev.vars (looked
# up next to the config file) would leak into the test otherwise. The
# separate --persist-to also gives every run a fresh, empty local D1.
SMOKE_DIR="$PWD/.wrangler/smoke"
rm -rf "$SMOKE_DIR"
mkdir -p "$SMOKE_DIR"
LOG="$SMOKE_DIR/wrangler.log"
compat=$(sed -n 's/^compatibility_date *= *"\(.*\)"/\1/p' wrangler.toml)
cat > "$SMOKE_DIR/wrangler.toml" <<TOML
# generated by smoke.sh — do not edit
name = "webapp-notification-api-smoke"
main = "$PWD/build/worker.mjs"
compatibility_date = "$compat"

[[d1_databases]]
binding = "DB"
database_name = "webapp-notification"
database_id = "smoke"
migrations_dir = "$PWD/migrations"

[vars]
PUSH_PROVIDER = "$provider"
LOG_LEVEL = "info"
API_KEY = "$API_KEY"
TOML
wr=(npx wrangler --config "$SMOKE_DIR/wrangler.toml")

"${wr[@]}" d1 migrations apply webapp-notification --local --persist-to "$SMOKE_DIR/state" >/dev/null
if curl -sf -m 2 "$BASE/healthz" >/dev/null 2>&1; then
  echo "smoke: something is already listening on $BASE (a leftover wrangler dev?); stop it or set SMOKE_PORT" >&2; exit 2
fi
# setsid: wrangler spawns workerd as a child; killing the process group (not
# just npx) on exit is what actually frees the port.
setsid "${wr[@]}" dev --port "$PORT" --persist-to "$SMOKE_DIR/state" >"$LOG" 2>&1 &
WRANGLER_PID=$!
cleanup() {
  kill -- "-$WRANGLER_PID" 2>/dev/null || kill "$WRANGLER_PID" 2>/dev/null || true
  wait "$WRANGLER_PID" 2>/dev/null || true
}
trap cleanup EXIT

for _ in $(seq 1 90); do
  curl -sf "$BASE/healthz" >/dev/null 2>&1 && break
  kill -0 "$WRANGLER_PID" 2>/dev/null || { echo "smoke: wrangler dev exited early" >&2; cat "$LOG" >&2; exit 1; }
  sleep 1
done
curl -sf "$BASE/healthz" >/dev/null || { echo "smoke: wrangler dev did not become ready on $BASE" >&2; cat "$LOG" >&2; exit 1; }

failures=0
body=""
status=""
# request <name> <method> <path> [curl args...]: sets $status / $body
request() {
  local name=$1 method=$2 path=$3; shift 3
  body=$(curl -s -o - -w '\n%{http_code}' -X "$method" "$BASE$path" "$@")
  status=${body##*$'\n'}
  body=${body%$'\n'*}
}
# expect <name> <expected status> [substring that must appear in body]...
expect() {
  local name=$1 want=$2; shift 2
  local bad=""
  [ "$status" != "$want" ] && bad=1
  local needle
  for needle in "$@"; do [[ "$body" == *"$needle"* ]] || bad=1; done
  if [ -n "$bad" ]; then
    echo "FAIL  $name: got $status ${body:0:300} (want $want${*:+ containing: $*})"
    failures=$((failures + 1))
  else
    echo "ok    $name: $status ${body:0:120}"
  fi
}
json=(-H 'Content-Type: application/json')
key=(-H "X-API-Key: $API_KEY")

request healthz GET /healthz;                                                     expect healthz 200 '"status":"ok"'
request register POST /v1/devices "${json[@]}" -d '{"installationId":"smoke-1","loginId":"u1","platform":"android","pushToken":"ExponentPushToken[smoke]"}'
                                                                                  expect "register u1" 200 '"loginIds":["u1"]'
request register2 POST /v1/devices "${json[@]}" -d '{"installationId":"smoke-1","loginId":"u2","platform":"android","pushToken":"ExponentPushToken[smoke]"}'
                                                                                  expect "register u2 (adds, does not replace)" 200 '"loginIds":["u1","u2"]'
request get GET /v1/devices/smoke-1;                                              expect "get device without API key" 401 '"code":"unauthorized"'
request get GET /v1/devices/smoke-1 "${key[@]}";                                  expect "get device (API key)" 200 '"installationId":"smoke-1"' '"loginIds":["u1","u2"]'
request badjson POST /v1/devices "${json[@]}" -d '{"installationId":1}';          expect "invalid body -> 400 (generated server)" 400 '"code":"invalid_request"'
request missing POST /v1/devices "${json[@]}" -d '{"installationId":"x"}';        expect "missing loginId -> 400" 400 '"code":"invalid_request"'
request notify0 POST /v1/notifications "${json[@]}" -d '{"loginIds":["u1"],"title":"t","body":"b"}'
                                                                                  expect "notify without API key" 401 '"code":"unauthorized"'
request unknown GET /nope;                                                        expect "unknown route" 404
request unlink DELETE /v1/devices/smoke-1/logins/u1;                              expect "unlink u1" 204
request get2 GET /v1/devices/smoke-1 "${key[@]}";                                 expect "u1 gone, u2 stays" 200 '"loginIds":["u2"]'
request unlinkall DELETE /v1/logins/u2 "${key[@]}";                               expect "unlink u2 everywhere (API key)" 200 '"removed":1'
request delete DELETE /v1/devices/smoke-1;                                        expect "delete device" 204
request get3 GET /v1/devices/smoke-1 "${key[@]}";                                 expect "deleted device -> 404" 404 '"code":"not_found"'

# Sending: one device linked to two logins gets exactly one message.
request register3 POST /v1/devices "${json[@]}" -d '{"installationId":"smoke-2","loginId":"u3","platform":"android","pushToken":"ExponentPushToken[smoke]"}'
                                                                                  expect "register u3" 200
request register4 POST /v1/devices "${json[@]}" -d '{"installationId":"smoke-2","loginId":"u4","platform":"android","pushToken":"ExponentPushToken[smoke]"}'
                                                                                  expect "register u4 (same device)" 200 '"loginIds":["u3","u4"]'
request notify2 POST /v1/notifications "${json[@]}" "${key[@]}" -d '{"loginIds":["nobody"],"title":"t","body":"b"}'
                                                                                  expect "notify unknown login" 200 '"requested":0' '"sent":0'
request notify1 POST /v1/notifications "${json[@]}" "${key[@]}" -d '{"loginIds":["u3","u4"],"title":"t","body":"b"}'
if [ "$provider" = log ]; then
                                                                                  expect "notify (log provider, two logins -> one device)" 200 '"requested":1' '"sent":1' '"failed":0' '"loginIds":["u3","u4"]'
  request delete2 DELETE /v1/devices/smoke-2;                                     expect "delete device 2" 204
  if grep -q '"msg":"push (log provider)"' "$LOG"; then
    echo "ok    worker log contains the log-provider push line"
  else
    echo "FAIL  worker log has no log-provider push line"; failures=$((failures + 1))
  fi
else
  # Real outbound fetch to exp.host through internal/push's fetch-based
  # HTTP client: Expo rejects the dummy token at the application level
  # (DeviceNotRegistered), and the backend then drops the device.
                                                                                  expect "notify via Expo API (dummy token -> DeviceNotRegistered)" 200 '"requested":1' '"failed":1' 'DeviceNotRegistered' '"unregistered":true'
  request get4 GET /v1/devices/smoke-2 "${key[@]}";                               expect "device dropped after DeviceNotRegistered" 404 '"code":"not_found"'
fi

if [ "$failures" -ne 0 ]; then
  echo "smoke: $failures failure(s)"; echo "--- $LOG"; cat "$LOG"; exit 1
fi
echo "smoke: all checks passed (provider=$provider)"
