#!/usr/bin/env bash
# Regenerates backend/worker/migrations/NNNN_<name>.sql (D1's
# `wrangler d1 migrations` naming) from backend/migrations/sqlite/*.sql (the
# Atlas-generated migrations cmd/server's sqlite path uses — see
# backend/README.md's "Migration (ent + Atlas)" section for how those are
# produced/regenerated from internal/ent/schema).
#
# Run via `mise run worker:migrations:sync` after regenerating
# backend/migrations/sqlite (`mise run db:diff <name> --dialect sqlite`):
# it always rewrites every backend/worker/migrations/*.sql file from
# scratch, in backend/migrations/sqlite's filename (timestamp) order, so it
# is safe (and expected) to re-run whenever that directory changes.
#
# The generated files are committed (unlike ../build/): D1 tracks which
# migrations it already applied by filename in a `d1_migrations` table, and
# regenerating filenames on every deploy would make it re-run them.
#
# Rewrites applied, beyond renumbering (see rewrite_statement below):
#   - `PRAGMA foreign_keys = off;` / `= on;` (Atlas's usual bracket around a
#     table-rebuild, e.g. to widen a column's nullability) becomes D1's own
#     `PRAGMA defer_foreign_keys = true;` / `= false;` — D1 rejects a bare
#     `PRAGMA foreign_keys = ...` statement inside a migration (it manages
#     that pragma itself), but does support defer_foreign_keys, which has
#     the same effect for a migration that stays within one transaction:
#     FK checks are deferred until the transaction commits instead of
#     disabled outright.
#   - Atlas's `-- comment` lines are dropped (cosmetic only; D1 does accept
#     them, but the numbered files read more easily without the noise of
#     Atlas's own migration-internal narration on top of this script's).
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

src_dir="../migrations/sqlite"
dst_dir="./migrations"

mkdir -p "$dst_dir"
rm -f "$dst_dir"/*.sql

n=0
for src in "$src_dir"/*.sql; do
  n=$((n + 1))
  base="$(basename "$src" .sql)"
  # Atlas names files "<timestamp>_<name>.sql"; keep "<name>", drop the
  # timestamp (D1 orders by the numeric prefix this script assigns instead).
  name="${base#*_}"
  dst="$dst_dir/$(printf '%04d' "$n")_${name}.sql"

  {
    echo "-- Generated by backend/worker/sync-migrations.sh from"
    echo "-- backend/migrations/sqlite/$(basename "$src"). Do not edit by hand:"
    echo "-- re-run \`mise run worker:migrations:sync\` instead."
  } >"$dst"

  while IFS= read -r line; do
    case "$line" in
    '--'*) continue ;; # drop Atlas's own comments
    'PRAGMA foreign_keys = off;') echo 'PRAGMA defer_foreign_keys = true;' >>"$dst" ;;
    'PRAGMA foreign_keys = on;') echo 'PRAGMA defer_foreign_keys = false;' >>"$dst" ;;
    '') continue ;; # drop the blank line left by a dropped comment
    *) echo "$line" >>"$dst" ;;
    esac
  done <"$src"

  echo "wrote $dst"
done
