/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ヘルスチェック */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 端末を登録 / 更新する
         * @description `installationId` をキーに upsert する。同じ端末で別のログイン ID になった場合は
         *     ログイン ID が付け替えられる。Web アプリのログイン時にアプリが呼び出す。
         */
        post: operations["registerDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{installationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                installationId: components["parameters"]["InstallationId"];
            };
            cookie?: never;
        };
        /** 端末を取得する */
        get: operations["getDevice"];
        put?: never;
        post?: never;
        /** 端末の登録を解除する (ログアウト時) */
        delete: operations["unregisterDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ログイン ID 宛にプッシュ通知を送る
         * @description 指定したログイン ID に紐づく全端末へ通知を送る。
         *     `url` を指定するとアプリは通知タップ時にその URL を WebView で開く。
         */
        post: operations["sendNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @example ok */
            status: string;
        };
        Error: {
            /** @example invalid_request */
            code: string;
            message: string;
        };
        /** @enum {string} */
        Platform: "ios" | "android";
        /**
         * @description `pushToken` (Expo Push Token) と `deviceToken` (FCM / APNs のネイティブトークン) は
         *     どちらか一方以上が必須。バックエンドの `PUSH_PROVIDER` が `expo` なら pushToken、
         *     `native` なら deviceToken が送信に使われる。
         */
        DeviceRegistration: {
            /** @description Web アプリのログイン ID (postMessage で受け取ったもの) */
            loginId: string;
            /** @description アプリインストールごとに生成される安定した ID */
            installationId: string;
            platform: components["schemas"]["Platform"];
            /** @description Expo Push Token (`ExponentPushToken[...]`)。`PUSH_PROVIDER=expo` で使う */
            pushToken?: string;
            /** @description ネイティブのデバイストークン (Android は FCM registration token、iOS は APNs device token の hex)。`PUSH_PROVIDER=native` で使う */
            deviceToken?: string;
            /** @description バンドル ID / パッケージ名 */
            appId?: string;
            appVersion?: string;
            buildNumber?: string;
            osVersion?: string;
            deviceModel?: string;
            locale?: string;
        };
        Device: components["schemas"]["DeviceRegistration"] & {
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SendNotificationRequest: {
            loginIds: string[];
            title: string;
            body?: string;
            /**
             * Format: uri
             * @description 通知タップ時に WebView で開く URL
             */
            url?: string;
            /** @description 任意の付加データ (アプリ側に `data` としてそのまま渡る) */
            data?: {
                [key: string]: unknown;
            };
            badge?: number;
            /** @description iOS のサウンド ("default" など) */
            sound?: string;
            /** @description Android の通知チャンネル ID */
            channelId?: string;
        };
        SendNotificationResult: {
            /** @description 宛先端末数 */
            requested: number;
            sent: number;
            failed: number;
            results: components["schemas"]["DeliveryResult"][];
        };
        DeliveryResult: {
            installationId: string;
            loginId: string;
            /** @enum {string} */
            status: "ok" | "error";
            /** @description プッシュサービスからのエラー内容 */
            error?: string;
            /** @description トークン失効により端末登録を削除した場合 true */
            unregistered?: boolean;
        };
    };
    responses: {
        /** @description リクエスト不正 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 認証エラー */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 見つからない */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        InstallationId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    registerDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceRegistration"];
            };
        };
        responses: {
            /** @description 登録済みの端末 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                installationId: components["parameters"]["InstallationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 端末 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    unregisterDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                installationId: components["parameters"]["InstallationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 解除した (存在しなかった場合も 204) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    sendNotification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendNotificationRequest"];
            };
        };
        responses: {
            /** @description 送信結果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendNotificationResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
}
