/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ヘルスチェック */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 端末を登録 / 更新する
         * @description `installationId` をキーに端末を upsert し、`loginId` をその端末に紐付ける。
         *     端末とログイン ID は多対多 (1 端末に複数アカウント、1 アカウントに複数端末)。
         *     既に紐付いている場合は端末情報 (トークン等) だけ更新する。Web アプリのログイン時にアプリが呼び出す。
         */
        post: operations["registerDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{installationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                installationId: components["parameters"]["InstallationId"];
            };
            cookie?: never;
        };
        /** 端末を取得する */
        get: operations["getDevice"];
        put?: never;
        post?: never;
        /** 端末の登録を解除する (全ログイン ID の紐付けごと削除) */
        delete: operations["unregisterDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{installationId}/logins/{loginId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                installationId: components["parameters"]["InstallationId"];
                loginId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 端末から特定のログイン ID の紐付けだけを外す (そのユーザーのログアウト時)
         * @description 端末自体とトークンは残るので、別のアカウントでログイン中ならそちらの通知は届き続ける。
         *     アプリから呼ぶほか、Web アプリのバックエンドがセッション失効時に API キーで呼んでもよい
         *     (installationId は bridge の `ready` イベントで Web アプリに渡る)。
         */
        delete: operations["unregisterDeviceLogin"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/logins/{loginId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loginId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * ログイン ID を全端末から外す (サーバー間)
         * @description Web アプリ側でセッションが失効・無効化された (全端末ログアウト、退会など) ときに
         *     Web アプリのバックエンドから呼ぶ。以後そのログイン ID 宛の通知はどの端末にも届かない。
         *     端末自体とトークンは残る (別アカウントの通知には影響しない)。
         */
        delete: operations["unregisterLogin"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * プッシュ通知を送る (ログイン ID / installationId / 全端末)
         * @description 宛先は `loginIds` (そのログイン ID に紐づく全端末)、`installationIds` (端末を直接指定)、
         *     `broadcast: true` (登録済みの全端末) のいずれか。`loginIds` と `installationIds` は併用でき、
         *     その場合は和集合を端末単位で重複排除して 1 端末 1 通だけ送る。`broadcast` は他の宛先と併用できない。
         *     `filter` で宛先をプラットフォームやロケールで絞り込める。
         *     `url` を指定するとアプリは通知タップ時にその URL を WebView で開く。
         *     TTL・優先度・サイレント通知などの配信オプションは `SendNotificationRequest` を参照。
         */
        post: operations["sendNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @example ok */
            status: string;
        };
        Error: {
            /** @example invalid_request */
            code: string;
            message: string;
        };
        /** @enum {string} */
        Platform: "ios" | "android";
        /**
         * @description `pushToken` (Expo Push Token) と `deviceToken` (FCM / APNs のネイティブトークン) は
         *     どちらか一方以上が必須。バックエンドの `PUSH_PROVIDER` が `expo` なら pushToken、
         *     `native` なら deviceToken が送信に使われる。
         */
        DeviceRegistration: {
            /** @description Web アプリのログイン ID (postMessage で受け取ったもの) */
            loginId: string;
            /** @description アプリインストールごとに生成される安定した ID */
            installationId: string;
            platform: components["schemas"]["Platform"];
            /** @description Expo Push Token (`ExponentPushToken[...]`)。`PUSH_PROVIDER=expo` で使う */
            pushToken?: string;
            /** @description ネイティブのデバイストークン (Android は FCM registration token、iOS は APNs device token の hex)。`PUSH_PROVIDER=native` で使う */
            deviceToken?: string;
            /** @description バンドル ID / パッケージ名 */
            appId?: string;
            appVersion?: string;
            buildNumber?: string;
            osVersion?: string;
            deviceModel?: string;
            locale?: string;
        };
        /** @description 端末情報 (ログイン ID を含まない DeviceRegistration) */
        DeviceInfo: {
            installationId: string;
            platform: components["schemas"]["Platform"];
            pushToken?: string;
            deviceToken?: string;
            appId?: string;
            appVersion?: string;
            buildNumber?: string;
            osVersion?: string;
            deviceModel?: string;
            locale?: string;
        };
        Device: components["schemas"]["DeviceInfo"] & {
            /** Format: int64 */
            id: number;
            /** @description この端末に紐付いているログイン ID (多対多) */
            loginIds: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /**
         * @description 宛先端末の絞り込み条件。指定した条件はすべて満たす (AND) 必要があり、
         *     各条件の配列内は「いずれかに一致」(OR) になる。
         */
        NotificationFilter: {
            /** @description このプラットフォームの端末だけに送る */
            platforms?: components["schemas"]["Platform"][];
            /**
             * @description 端末の `locale` に対する BCP 47 タグの前置一致 (大文字小文字を区別しない、タグ境界で判定)。
             *     `ja` は `ja` と `ja-JP` に一致するが `jav` には一致しない。`ja-JP` は `ja-JP` (と `ja-JP-...`) にだけ一致する。
             *     `locale` が未登録の端末はどのロケール指定にも一致しない
             */
            locales?: string[];
        };
        /**
         * @description 宛先は `loginIds` / `installationIds` / `broadcast: true` のうち少なくとも 1 つが必須。
         *     `broadcast: true` は `loginIds` / `installationIds` と併用できない (400)。
         *
         *     `silent` が false (既定) のときは `title` が必須。`silent: true` のときは `title` / `body` /
         *     `sound` / `badge` / `subtitle` / `image` を指定できない (データのみのサイレント通知)。
         */
        SendNotificationRequest: {
            /** @description このログイン ID に紐づく全端末に送る */
            loginIds?: string[];
            /**
             * @description この installationId の端末に直接送る。`loginIds` と併用した場合は和集合
             *     (同じ端末には 1 通だけ送る)。存在しない installationId は黙って無視する
             */
            installationIds?: string[];
            /** @description true なら登録済みの全端末に送る (`filter` で絞り込み可)。`loginIds` / `installationIds` とは併用できない */
            broadcast?: boolean;
            filter?: components["schemas"]["NotificationFilter"];
            /** @description 通知タイトル。`silent` が false のときは必須 */
            title?: string;
            body?: string;
            /**
             * Format: uri
             * @description 通知タップ時に WebView で開く URL
             */
            url?: string;
            /** @description 任意の付加データ (アプリ側に `data` としてそのまま渡る) */
            data?: {
                [key: string]: unknown;
            };
            badge?: number;
            /** @description iOS のサウンド ("default" など) */
            sound?: string;
            /** @description Android の通知チャンネル ID */
            channelId?: string;
            /**
             * @description 通知を保持する秒数 (0 〜 2419200 = 28 日)。この時間内に端末へ届けられなければ破棄される。
             *     Expo は `ttl`、FCM は `android.ttl`、APNs は `apns-expiration` (現在時刻 + ttl の UNIX 秒) に対応する。
             *     未指定ならプッシュサービスの既定値に従う
             */
            ttl?: number;
            /**
             * @description 配信優先度。`high` (既定、従来どおりの挙動) は即時配信、`normal` は省電力を優先して遅延することがある。
             *     Expo は `priority`、FCM は `android.priority` (`high` / `normal`)、APNs は `apns-priority` (10 / 5) に対応する。
             *     `silent: true` の APNs は Apple の要件により常に 5 になる
             * @default high
             * @enum {string}
             */
            priority: "high" | "normal";
            /**
             * @description 同じキーの未配信の通知を 1 つにまとめる (最新のものだけ残す)。
             *     FCM は `android.collapse_key`、APNs は `apns-collapse-id` に対応する。
             *     **Expo は非対応のため無視される**
             */
            collapseKey?: string;
            /**
             * Format: uri
             * @description 通知に表示する画像の URL (絶対 http(s) URL)。
             *     Expo は `richContent.image`、FCM は `notification.image` に対応する。
             *     **APNs は Notification Service Extension なしでは表示できないため無視される**
             */
            image?: string;
            /**
             * @description true ならサイレント通知 (データのみの通知)。画面には何も表示せず、`data` だけをアプリに届ける。
             *     Expo は `title` / `body` / `sound` / `badge` を省いて `_contentAvailable: true` を付け、
             *     FCM は `notification` を省いて `data` だけ送り、
             *     APNs は `apns-push-type: background` / `apns-priority: 5` / `aps.content-available: 1` で送る。
             *     `title` / `body` / `sound` / `badge` / `subtitle` / `image` とは併用できない (400)。`data` は空でもよい
             * @default false
             */
            silent: boolean;
            /**
             * @description 通知のサブタイトル (iOS)。Expo は `subtitle`、APNs は `aps.alert.subtitle` に対応する。
             *     **FCM (Android) は非対応のため無視される**
             */
            subtitle?: string;
            /**
             * @description iOS の通知グループ化 ID。APNs の `aps.thread-id` に対応する。
             *     **Expo と FCM は非対応のため無視される**
             */
            threadId?: string;
            /**
             * @description iOS 15 以降の割り込みレベル。Expo は `interruptionLevel`、APNs は `aps.interruption-level` に対応する。
             *     **FCM (Android) は非対応のため無視される**
             * @enum {string}
             */
            interruptionLevel?: "passive" | "active" | "time-sensitive" | "critical";
        };
        SendNotificationResult: {
            /** @description 宛先端末数 (`filter` 適用後) */
            requested: number;
            sent: number;
            failed: number;
            results: components["schemas"]["DeliveryResult"][];
        };
        /** @description 端末ごとの送信結果。同じ端末が複数の宛先 (ログイン ID / installationId) に該当しても 1 通にまとめる */
        DeliveryResult: {
            installationId: string;
            /**
             * @description リクエストの loginIds のうち、この端末に紐付いていたもの。
             *     `installationIds` / `broadcast` だけで選ばれた端末では空配列
             */
            loginIds: string[];
            /** @enum {string} */
            status: "ok" | "error";
            /** @description プッシュサービスからのエラー内容 */
            error?: string;
            /** @description トークン失効により端末登録を削除した場合 true */
            unregistered?: boolean;
        };
    };
    responses: {
        /** @description リクエスト不正 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 認証エラー */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 見つからない */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        InstallationId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    registerDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceRegistration"];
            };
        };
        responses: {
            /** @description 登録済みの端末 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                installationId: components["parameters"]["InstallationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 端末 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    unregisterDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                installationId: components["parameters"]["InstallationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 解除した (存在しなかった場合も 204) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    unregisterDeviceLogin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                installationId: components["parameters"]["InstallationId"];
                loginId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 解除した (存在しなかった場合も 204) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    unregisterLogin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loginId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 解除した端末数 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 紐付けを外した端末数 (0 でも 200) */
                        removed: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    sendNotification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendNotificationRequest"];
            };
        };
        responses: {
            /** @description 送信結果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendNotificationResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
}
